### ISSUE TITLE
Chests appear invisible when using shaders

### ISSUE THREAD

**Issue by kaleinthepot** [Asek3/Oculus#1]
when playing with the BSL shaderpack or Complementary, chests turn invisible

![2022-02-25_21 28 56](https://user-images.githubusercontent.com/77541397/155732540-cca5fe3a-46eb-4cef-8a10-0360abe5639b.png)
![2022-02-25_21 28 40](https://user-images.githubusercontent.com/77541397/155732569-4c1598db-d8f2-402a-9083-45c913d997e9.png)
![Uploading 2022-02-25_21.28.40.png…]()

**Comment by syelents** [comment]
This seems to happen when Flywheel is installed. You will also see that this happens to bells because Flywheel implements its own shader system for them.

**Comment by achaeus** [comment]
there's a temporary fix on Flywheel's side, https://github.com/Jozufozu/Flywheel/issues/115 

thanks to @syelents for the post

**Comment by Asek3** [comment]
Probably resolved in 1.2.4
