### ISSUE TITLE
[1.18.1] Crash when launching the game

### ISSUE THREAD

**Issue by Dr-WeiAL** [Asek3/Oculus#10]
[crash-2022-04-03_22.31.48-fml.txt](https://github.com/Asek3/Oculus/files/8404745/crash-2022-04-03_22.31.48-fml.txt)

**Comment by Sashad07** [comment]
I'm also having this problem, also I'm using the flywheel mod, IDK if the issue is because of that :/ if you find a resolution please let me know.

**Comment by msameer** [comment]
I have the same issue

**Comment by PenumbraStar** [comment]
Same issue, appears to be an issue with flywheel.

**Comment by PenumbraStar** [comment]
[crash-2022-04-05_22.47.15-fml.txt](https://github.com/Asek3/Oculus/files/8423161/crash-2022-04-05_22.47.15-fml.txt)

**Comment by Asek3** [comment]
Should be fixed in latest versions
