### ISSUE TITLE
Shader Glitch with Create Mod

### ISSUE THREAD

**Issue by enkido** [Asek3/Oculus#100]
### What happened?

With:
- ComplementaryShaders_v4.4 (PBR disabled, Profile: Extreme)
- create-mc1.16.5_v0.3.2g.jar
- flywheel-1.16-0.2.5.jar
- oculus-1.2.3-pre.jar
- rubidium-0.2.6.jar

![image](https://user-images.githubusercontent.com/6398971/173035450-40d2b256-329e-4af5-8191-74c51ff2ccc9.png)

With:
- ComplementaryShaders_v4.4 (PBR disabled, Profile: Extreme)
- create-mc1.16.5_v0.3.2g.jar
- flywheel-1.16-0.2.5.jar
- OptiFine_1.16.5_HD_U_G7.jar

![image](https://user-images.githubusercontent.com/6398971/173036716-b227d481-94cd-4936-a71d-45674fa31585.png)

### Minecraft Version

1.16.5

### Iris Version

oculus-1.2.3-pre.jar

### Sodium Version

rubidium-0.2.6.jar

### Operating System

Windows 10

### What is your GPU?

RTX 2070 Super

### Java Version

Java 1.8.0_51

**Comment by SmokePuddingEveryday** [comment]
This bug is also still present on the more recent 1.2.5 version of Oculus. Flywheel backend off simply stops the entities from rendering.

This is the only bug I've been able to see in terms of Oculus and Create/Flywheel as of 1.16.5. Hopefully someone knows of a solution :)

**Comment by Tomahawk101** [comment]
I also have this bug. Let me know if I can provide any helpful info, disabling flywheel also makes create things invisible. 
![image](https://user-images.githubusercontent.com/44147276/173458835-f0be9dc6-0145-4a75-833f-95e7395c49af.png)

**Comment by Enterprise12nx01** [comment]
Would love to see this fixed, I've been using optifine, but it can't be used with many of these performance mods

**Comment by Orthestral** [comment]
This issue also exists for me in 1.16.

In the meantime, until this is addressed, you can use Complementary Reimagined, which looks the most natural with Flywheel-affected stuff. Only the shadows are missing

**Comment by enkido** [comment]
> This issue also exists for me in 1.16.
> 
> In the meantime, until this is addressed, you can use Complementary Reimagined, which looks the most natural with Flywheel-affected stuff. Only the shadows are missing

Thanks, this is much better

**Comment by rocketstrong600** [comment]
issue exists for me too

**Comment by KlaraChaos** [comment]
Can confirm also i have the issue

**Comment by Asek3** [comment]
Fixed in 1.4.8
