### ISSUE TITLE
Glowing chests while using shaders

### ISSUE THREAD

**Issue by Chleb3k** [Asek3/Oculus#103]
### What happened?

As in the title, chests emit some weird glow. Some mobs' heads, weapons and dropped items do that as well. Doesn't matter which shaders I use. 
I only included a screenshot of a chest, but the rest has an indentical glow. This is on complementary shaders. Sildurs Vibrant for example glows blue.

### Screenshots

![image](https://user-images.githubusercontent.com/72503036/173665540-bb12156f-394f-4a91-863b-1acd14bb40f3.png)

### Minecraft Version

1.16.5

### Iris Version

oculus 1.2.5

### Sodium Version

magnesium 1.5

### Operating System

win 10

### What is your GPU?

RTX 3060

### Java Version

8

**Comment by tctfox** [comment]
Same behavior here

**Comment by mariobrosmania** [comment]
I am having the same issue on oculus 1.2.6

**Comment by michaelgosling** [comment]
Issue is not present on Oculus 1.2.6 for me but is present on 1.4.3

**Comment by michaelgosling** [comment]
disabling flywheel fixes this

**Comment by Asek3** [comment]
Should be fixed in 1.4.8
