### ISSUE TITLE
Flywheel Backend off 

### ISSUE THREAD

**Issue by f0kx** [Asek3/Oculus#104]
### What happened?

When i want to activate the flywheel backend game will crash. only if /flywheel backend off is active game will load to multiplayer Sever....Singleplayer it will work

### Relevant log output

```shell
https://pastebin.com/tF3Utda6
```

### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.5

### Sodium Version

Rubidium mc1.18.2-0.5.2a

### Operating System

Win 10

### What is your GPU?

1070 GTX

### Java Version

Java 16

**Comment by Asek3** [comment]
Should be fixed in latest Flywheel's versions
