### ISSUE TITLE
Weird glow on banners and items with shaders

### ISSUE THREAD

**Issue by fernandoarmengol** [Asek3/Oculus#113]
### What happened?

Weird glow on banners and items with shaders, using Sildurs Vibrant Shaders  v1.32

### Screenshots

![2022-06-24_14 55 43](https://user-images.githubusercontent.com/71931361/175540546-bad520a5-9f94-4938-910f-b9ae7d8566bb.png)

### Minecraft Version

1.16.5

### Iris Version

oculus-1.2.5

### Sodium Version

rubidium-0.2.7

### Operating System

Windows 10

### What is your GPU?

3060 Ti

### Java Version

Java 8

**Comment by fernandoarmengol** [comment]
I have found that the problem is related with flywheel, if I deactivate the flywheel backend it works correctly, but when I activate it the bug appears again
![2022-06-24_15 38 06](https://user-images.githubusercontent.com/71931361/175547471-66538764-6bf5-4a4c-9910-f0a4ab0df18a.png)
![2022-06-24_15 38 11](https://user-images.githubusercontent.com/71931361/175547525-75d44569-70cf-408b-90ac-48b4791fdb9f.png)

**Comment by Enterprise12nx01** [comment]
having the same issue

**Comment by fernandoarmengol** [comment]
it's fixed in the latest version of rubidium and oculus
