### ISSUE TITLE
White dots on screen with Create/Flywheel

### ISSUE THREAD

**Issue by SrParavel** [Asek3/Oculus#116]
### What happened?

A lot of white dots are rendered on screen when shadders are enabled, this is happening while using the Create/Flywheel mod. tested this on single player and multiplayer, my friends are reporting this issue aswell, so it seems you can reproduce this in a lot of machines.

### Screenshots

![image](https://user-images.githubusercontent.com/60823075/176369793-e8f79e8a-70d0-47ee-b144-975de314e3d3.png)
![image](https://user-images.githubusercontent.com/60823075/176370126-63d286c3-679b-428c-ae54-1735c63eec18.png)
![image](https://user-images.githubusercontent.com/60823075/176370391-49aa7bf4-b916-4797-8ad5-6ca6f73e7d3f.png)

### Minecraft Version

Minecraft 1.18.2 / Forge 40.1.0

### Iris Version

oculus-mc1.18.2-1.2.5

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 11

### What is your GPU?

GTX 1060

### Java Version

Java 17

### Additional context

How to reproduce: Install Rubidium, Cculus, Create Mod & enable any shadders.

**Comment by JosShepherd** [comment]
To fix this, type /flywheel backend off
This should hopefully work.

**Comment by Enterprise12nx01** [comment]
Any idea if this is going to be fixed eventually? this effects many items and entities including any of creates items, entities glow white and chests are effected too

**Comment by Asek3** [comment]
Should be fixed on latest Flywheel and Oculus versions. If not, plz tell
