### ISSUE TITLE
Bug with Custom Render Entity

### ISSUE THREAD

**Issue by Rumaruka** [Asek3/Oculus#121]
### What happened?

Entity transparency (look screenshots)

### Screenshots

![photo_2022-07-06_18-52-17](https://user-images.githubusercontent.com/8148679/177566776-8d75f738-af1d-4f4d-9467-21b1bb66f106.jpg)
![photo_2022-07-06_18-59-22](https://user-images.githubusercontent.com/8148679/177568027-a8472385-f1c1-4fc3-9dce-f2f7a63acd84.jpg)

### Minecraft Version

1.16.5

### Iris Version

oculus-1.2.5

### Sodium Version

rubidium-0.2.6

### Operating System

Windows 10

### What is your GPU?

Never ming

### Java Version

Java 1.8

### Additional context

-TimeCore and HammerCore for Renders Entity

**Comment by Rumaruka** [comment]
And found bug with ComputerCraft Monitor
![image](https://user-images.githubusercontent.com/8148679/177991455-7984896c-fa91-43bc-96d9-57d991426453.png)

**Comment by Asek3** [comment]
Проблемы с прозрачностью текстур должны быть решены в 1.2.6, релиз уже в течении месяца

**Comment by Asek3** [comment]
![image](https://user-images.githubusercontent.com/64613894/180414366-68e68413-52e7-41ff-a8d3-391e3f4ba121.png)
Касательно компьютеркрафта, вы можете зайти в его клиентский конфиг и заменить значение BEST на VBO

![image](https://user-images.githubusercontent.com/64613894/180414502-a5b629f1-d5c0-4bc9-ac97-2c7a7f6e48bb.png)

**Comment by Asek3** [comment]
Should be fixed already
