### ISSUE TITLE
Game crashes while running shaders while Create 0.5.0 blocks* are rendered.

### ISSUE THREAD

**Issue by xameryn** [Asek3/Oculus#124]
``* Specially shaped blocks like cogs and shafts, casing (full blocks) are fine``

### What happened?

Minecraft runs fine until enabling shaders while having Create blocks loaded/in view.

### Reproduction Steps

1. Add the following mods:
   a. Create 0.5.0
   b. Flywheel 1.18-0.6.3.81
   c. Rubidium 0.5.2a
   d. Oculus 1.2.5
3. Create/load a world with shaders disabled
4. Place a create block (ie. cogs and shafts)
5. Enable shaders (via 'k' or in video settings)
6. Game crashes

### Relevant log output

```shell
https://mclo.gs/3FK6R8c
```

### Minecraft Version

Minecraft 1.18.2

### Oculus Version

1.2.5

### Rubidium Version

0.5.2a

### Operating System

Windows 11

### What is your GPU?

RX 5700 XT

### Java Version

Java 17.0.3

### Additional context

[Create Bug Report](https://github.com/Creators-of-Create/Create/issues/3175)

**Comment by CzechHek** [comment]
Can confirm.

**Comment by absly** [comment]
You can solve this by editing the config file of FlyWheel : 
backend = "OFF"

**Comment by Asek3** [comment]
Update mods.
