### ISSUE TITLE
Graphical Artefacts with Minecolonies (Mod) UI Elements

### ISSUE THREAD

**Issue by razarelie** [Asek3/Oculus#126]
### What happened?

UI Elements used in the Minecolonies mod breaks Oculus.

Two issues.

The inworld UI elements above NPCs draw connected voids between each other across the screen. This issue disappears when F1 is used.

When using the Structurize build function (Bundled with the Minecolonies) the template distorts in a way where it is showing the backside of the blocks, almost in negative space. This issue remains when F1 is used.

Was able to isolate this to Oculus with a few levels of troubleshooting:

- With Oculus disabled the issue is gone
- Not related to shader pack choice as occurs on all shaders and even shaders disabled
- Have toggled pretty much every setting in Oculus and the Shader settings in hopes of finding a particular setting that is causing the issue but no luck

Attached are screenshots showing the draw issue.
![UI Screen Draws](https://user-images.githubusercontent.com/92236799/178233036-dc16a02e-cbfc-4b9f-aa67-8d49f6abc385.png)
![F1 - True](https://user-images.githubusercontent.com/92236799/178233073-db576342-fca8-4775-b496-c1de6d355032.png)
![F1 - False](https://user-images.githubusercontent.com/92236799/178233092-433864ff-a8e4-43e7-b1ed-6eb1fe7a9a57.png)

Screenshot of the Structurize build tool issue
![Structurize Build Tool Issue](https://user-images.githubusercontent.com/92236799/178233228-73fa42ad-5ef7-4a1a-9177-27b45480f9c1.png)

### Minecraft Version

1.18.2

### Iris Version

mc1.18.2-1.2.5 and 1.2.4 (Rolled back for testing)

### Sodium Version

Rubidium-0.5.2a

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 2070 Super

### Java Version

17.0.1

**Comment by Shadows-of-Fire** [comment]
Tracking via #84 (fix available, PR pending to minecolonies)

**Comment by Asek3** [comment]
Update Minecolonies, should be fixed
