### ISSUE TITLE
[1.18.2] Minecolonies building preview doesn't display properly with oculus installed.

### ISSUE THREAD

**Issue by DeshnVenks** [Asek3/Oculus#13]
Hello, while using minecolonies, aside from the icon bug, i noticed that the previews for the buildings in the mod do not work whilist i have oculus installed. Removing it fixes the issue immediately.

I have tested this with different versions of oculus and minecolonies (the latest ones as well of course), however the issue persists if both are paired together.

![2022-04-03_23 01 18](https://user-images.githubusercontent.com/102829081/161462006-f7f149db-c85d-46da-b4b0-bec5858ea71c.png)
![2022-04-03_23 03 34](https://user-images.githubusercontent.com/102829081/161462203-4ae802dc-a16f-4bdf-ab5f-0898de7ba906.png)
 
Wether the shaders are on or off does not affect the situation at all, only deactivating oculus.

**Comment by PenumbraStar** [comment]
I can also attest to this. Here is the log file and also the debug log, not sure if it will help, and not really had any bugs like this in the past to report. The only installed mods are Oculus, Rubidium and Minecolonies(With its requirements). There are also no resource packs present. Thank you for all your hard work! I have a decent pc, but this mod gives me an average framerate improvement of around 20fps, and that is after maxing nearly every setting, which I simply can not do, even with optifine normally. So here's hoping this helps a little bit! If there is a way you prefer to have bugs like this reported incase I run into more as I build my modpack?
[latest.log](https://github.com/Asek3/Oculus/files/8456778/latest.log)
[debug.log](https://github.com/Asek3/Oculus/files/8456777/debug.log)

**Comment by Asek3** [comment]
Update mods, should be fixed now

**Comment by TobiDoes** [comment]
I mean there is one other problem that I have seen on 1.19 and that is that some blocks (mostly any marked as replaceable ie. Grass) glows the color of the sky and water becomes opaque with animals standing out hard when a preview is open
