### ISSUE TITLE
1.16.5 - Complementary Reimagined r1.1.1 - Brightness increases after 30s-2m instantly on some blocks.

### ISSUE THREAD

**Issue by aLanaMaunz** [Asek3/Oculus#139]
### What happened?

After starting the client, everything is fine:
![1](https://user-images.githubusercontent.com/87087955/180917269-355118b1-13c1-48fd-b41a-a1898797f009.png)

After waiting for 30s to 2min, the following is happening:
![2](https://user-images.githubusercontent.com/87087955/180917337-2d53ba8f-8377-44a8-b5e5-c87382bd5827.png)
The brightness of some white blocks, signs and some entities like "white" llamas and white sheeps increases. Its not flickering or anything, it just stays like that. Its also not increasing gradually, it changes in 1 frame. 

Following versions (should be the newest available) were used:
![unknown](https://user-images.githubusercontent.com/87087955/180917622-a7124666-06ac-480e-80ae-72415ec06233.png)

On fabric with iris+sodium everything is fine:
![unknown](https://user-images.githubusercontent.com/87087955/180917759-6c197040-3e97-4003-b7e4-198798e398e6.png)

The Complementary community told me, its an Oculus incompability/bug. Maybe its related to Rubidium (or Forge?) - don't know how to isolate the Issue further. 

Without the Complementary Reimagined shader (but Rubidium + Oculus loaded) everything is fine.

### Minecraft Version

1.16.5

### Iris Version

oculus-1.2.5a.jar

### Sodium Version

rubidium-1.16.5-0.2.8.jar

### Operating System

WIndows 10

### What is your GPU?

RTX 2080

### Java Version

Java 8?

**Comment by SkullDiamond** [comment]
I have the same issue but whit mobs and chest 
![2022-07-26_17 37 55](https://user-images.githubusercontent.com/79324102/181101782-72ec5c0f-4f47-4407-ac29-440f47962aee.png)

**Comment by Cellorator** [comment]
I'm having the same issue with Rubidium and Oculus on 1.16.5.

**Comment by Sundwalltanner** [comment]
> I'm having the same issue with Rubidium and Oculus on 1.16.5.

Same

**Comment by Mathead253** [comment]
> I'm having the same issue with Rubidium and Oculus on 1.16.5.

Same

**Comment by Cobyt3** [comment]
I am having this issue on the Player model itself on Oculus v1.4.5 for 1.16.5

**Comment by EvergreenMoth8** [comment]
for anyone having this issue try turning RP Support to basic

**Comment by MastervXV** [comment]
i have this same problem 
![2023-04-18_09 57 59](https://user-images.githubusercontent.com/131195061/232862173-703434f4-d020-4877-8709-b7967136489c.png)

**Comment by Asek3** [comment]
Fixed in 1.4.8
