### ISSUE TITLE
Rubidium + Oculus (AstraLex Shader) + Minecolonies colonists have weird graphical glitch.

### ISSUE THREAD

**Issue by Waterspark63** [Asek3/Oculus#142]
### What happened?

When I had switched over from using optifine, to Rubidium, & Oculus, I loaded into my world only to notice a weird yellow line in the world. I followed it to find the colonists from Minecolonies had a weird visual glitch over their heads. If you need anything more than what I've provided, please let me know! 

### Screenshots

Edit: Wrong screenshot, oops.
![2022-07-29_02 22 17-min](https://user-images.githubusercontent.com/23124229/181718543-89a8427a-cab4-4817-81a2-a4701edf94ee.png)

### Minecraft Version

1.18.2

### Iris Version

Oculus-mc1.18.2-1.2.5

### Sodium Version

Rubidium-0.5.3

### Operating System

Win 10

### What is your GPU?

Nvidea GeForce RTX 3070 TI

### Java Version

Using Curseforge, don't know which is exactly running, but java -version returns Java 18

### Additional context

Here's the latest.log
[latest.log](https://github.com/Asek3/Oculus/files/9218163/latest.log)

**Comment by Waterspark63** [comment]
I have realized this is a duplicate of #126 & #84, so I'm closing it, if I shouldn't do that then feel free to reopen it.

**Comment by Shadows-of-Fire** [comment]
Tracking via #84 (fix available, PR pending to minecolonies)
