### ISSUE TITLE
Just F*cking Crashes

### ISSUE THREAD

**Issue by Nabroc** [Asek3/Oculus#147]
### Minecraft Version

Minecraft 1.16.5

### Iris Version

Oculus

### Sodium Version

Rubidium

### Operating System

Windows 10

### What is your GPU?

RTX 3060

### Java Version

Java Version 8 Update 341

### Reproduction Steps

start game, crashes immidiatly

### Crash Report file and latest.log

```shell
"An unexpected error has occurred and the game has crashed. We're sorry for the inconvenience. This crash may be caused by an invalid Java Runtime Configuration. Check any custom configuration settings."
Exit Code: 1
```

### Additional context

No Context. Just crashes upon loading

**Comment by NarwhalAndMe** [comment]
This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.

**Comment by Adam-cyb** [comment]
> This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.

Okay and which version of Java does not crash the game with these mods?

**Comment by NarwhalAndMe** [comment]
> > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> 
> Okay and which version of Java does not crash the game with these mods?

It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍

**Comment by Adam-cyb** [comment]
> > > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> > 
> > 
> > Okay and which version of Java does not crash the game with these mods?
> 
> It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍

I see, but which version would be needed for Minecraft 1.19.1?

**Comment by NarwhalAndMe** [comment]
> > > > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> > > 
> > > 
> > > Okay and which version of Java does not crash the game with these mods?
> > 
> > 
> > It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍
> 
> I see, but which version would be needed for Minecraft 1.19.1?

java 17..?

**Comment by Adam-cyb** [comment]
> > > > > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> > > > 
> > > > 
> > > > Okay and which version of Java does not crash the game with these mods?
> > > 
> > > 
> > > It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍
> > 
> > 
> > I see, but which version would be needed for Minecraft 1.19.1?
> 
> java 17..?

Isn't it supposed to tell me there's a Java update? I'm slightly confused.

**Comment by NarwhalAndMe** [comment]
> > > > > > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> > > > > 
> > > > > 
> > > > > Okay and which version of Java does not crash the game with these mods?
> > > > 
> > > > 
> > > > It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍
> > > 
> > > 
> > > I see, but which version would be needed for Minecraft 1.19.1?
> > 
> > 
> > java 17..?
> 
> Isn't it supposed to tell me there's a Java update? I'm slightly confused.

no, because its minecraft and it doesnt. it does tell you the issue in the crash log though.
just download the version of java you need, but it required more steps if you are using multimc or poly mc

**Comment by Adam-cyb** [comment]
> > > > > > > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> > > > > > 
> > > > > > 
> > > > > > Okay and which version of Java does not crash the game with these mods?
> > > > > 
> > > > > 
> > > > > It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍
> > > > 
> > > > 
> > > > I see, but which version would be needed for Minecraft 1.19.1?
> > > 
> > > 
> > > java 17..?
> > 
> > 
> > Isn't it supposed to tell me there's a Java update? I'm slightly confused.
> 
> no, because its minecraft and it doesnt. it does tell you the issue in the crash log though. just download the version of java you need, but it required more steps if you are using multimc or poly mc

It tells you the issue in the crash log? Where exactly, if I may ask?

**Comment by NarwhalAndMe** [comment]
> > > > > > > > This is not a Rubidium and Oculus problem, it's your java version, make sure to have the correct one installed.
> > > > > > > 
> > > > > > > 
> > > > > > > Okay and which version of Java does not crash the game with these mods?
> > > > > > 
> > > > > > 
> > > > > > It wouldn't run without the mod, too, it's not just a rubidium and oculus problem, like i said. it should work with java 8 since its 1.16 👍
> > > > > 
> > > > > 
> > > > > I see, but which version would be needed for Minecraft 1.19.1?
> > > > 
> > > > 
> > > > java 17..?
> > > 
> > > 
> > > Isn't it supposed to tell me there's a Java update? I'm slightly confused.
> > 
> > 
> > no, because its minecraft and it doesnt. it does tell you the issue in the crash log though. just download the version of java you need, but it required more steps if you are using multimc or poly mc
> 
> It tells you the issue in the crash log? Where exactly, if I may ask?

the bottom.

**Comment by Asek3** [comment]
Try to reinstall forge or download older java8 versions. Can't be related to us
