### ISSUE TITLE
[1.18.2]Unexpected error-NullPointerException

### ISSUE THREAD

**Issue by OcrSu** [Asek3/Oculus#154]
### Minecraft Version

1.18.2

### Iris Version

oculus-1.2.5a

### Sodium Version

rubidium-0.5.3a

### Operating System

Win10

### What is your GPU?

GT1030 DDR5

### Java Version

Java17

### Reproduction Steps

I'm playing on my vanilla server. When I get to a particular location, I don't know what's special about it.
Game crashes instantly
[crash-2022-08-14_08.18.04-client.txt](https://github.com/Asek3/Oculus/files/9332456/crash-2022-08-14_08.18.04-client.txt)

**Comment by Asek3** [comment]
Fixed in next version
