### ISSUE TITLE
Not a proper fork of Iris

### ISSUE THREAD

**Issue by coderbot16** [Asek3/Oculus#16]
You seem to have taken the Iris source code and recommitted it under a completely new git history, instead of just cloning the existing Iris source code and making your modifications on top of it as your own commits. Aside from screwing up the code attribution, this makes it painful to merge upstream changes or see exactly what has been changed in this fork.

You should make a proper fork of Iris, that includes full git history and thus proper attribution. That will ultimately make it easier for you to maintain the fork if you can minimize unnecessary restructurings and changes.

By creating a "hard fork", you've made it very difficult to share changes back and forth, and the specific method of recommitting changes as well as not providing a README or any of the sort doesn't make it at all clear who actually wrote a given line of the code in this repository.

**Comment by Asek3** [comment]
Soo, I think that's resolved
