### ISSUE TITLE
1.19.2 Crash oculus 1.2.5a

### ISSUE THREAD

**Issue by Edel-Lilies** [Asek3/Oculus#164]
### Minecraft Version

1.19.2

### Iris Version

1.2.5a

### Sodium Version

0.6.1

### Operating System

win11

### What is your GPU?

GTX1070ti

### Java Version

17

### Reproduction Steps

[crash-2022-08-22_22.03.35-client.txt](https://github.com/Asek3/Oculus/files/9394574/crash-2022-08-22_22.03.35-client.txt)
[crash-2022-08-22_22.05.58-client.txt](https://github.com/Asek3/Oculus/files/9394576/crash-2022-08-22_22.05.58-client.txt)

**Comment by CDAGaming** [comment]
[latest.log](https://github.com/Asek3/Oculus/files/9428926/latest.log)
Same issue :(

**Comment by CDAGaming** [comment]
Related: https://github.com/bonsaistudi0s/Creeper-Overhaul/issues/41

**Comment by CDAGaming** [comment]
Resolved as per https://github.com/bonsaistudi0s/Creeper-Overhaul/pull/44
