### ISSUE TITLE
Player/entity models render with red tint.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Oculus#17]
Player/entity models render with red tint.

Oculus version: 1.16.5-1.2.2
![2022-04-05_12 36 05](https://user-images.githubusercontent.com/47157784/161835534-725da443-182e-46ce-852a-fc048710f518.png)
.

**Comment by IMS212** [comment]
Do you have Physics Mod? If so, this will be fixed soon.

**Comment by Romoslayer** [comment]
This is only with oculus and rubidium installed.

**Comment by Asek3** [comment]
Update Oculus
