### ISSUE TITLE
Incorrect rendering of loot beams.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Oculus#18]
Incorrectly renders loot beams from the mod Loot Beams.

With Oculus:
![2022-04-05_14 51 09](https://user-images.githubusercontent.com/47157784/161855872-19054bce-6e85-48f3-b092-2787ef956bc0.png)

Without Oculus: 
![image](https://user-images.githubusercontent.com/47157784/161855970-c64e7880-77c8-4e2f-a94e-90854f114569.png)

Oculus version: 1.16.5-1.2.2

**Comment by Asek3** [comment]
Correctly works on latest versions
