### ISSUE TITLE
Entity Display Bug

### ISSUE THREAD

**Issue by SuperTiru** [Asek3/Oculus#191]
### What happened?

1. Display error of the enchanted equipment
2. Mob attack does not show red

### Screenshots

![1](https://user-images.githubusercontent.com/108540864/191966283-33105b5e-d56d-4e76-acd5-4ac9ba3dc14f.png)
![2](https://user-images.githubusercontent.com/108540864/191966286-e832ad27-f6db-4484-87fb-ff57ee89d729.png)
![3](https://user-images.githubusercontent.com/108540864/191966297-b5692a45-c1bb-4c06-b21e-255e89ca9654.png)
![4](https://user-images.githubusercontent.com/108540864/191966303-f16e6205-bfa0-4dea-b65f-bbaf22fd249a.png)

### Minecraft Version

Minecraft 1.16.5

### Iris Version

oculus-1.2.6.jar

### Sodium Version

 rubidium-0.2.10.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2070 Super

### Java Version

Java 8

### Additional context

[latest.log](https://github.com/Asek3/Oculus/files/9633813/latest.log)

**Comment by Asek3** [comment]
Fixed in 1.4.8
