### ISSUE TITLE
Over glow on Enteties

### ISSUE THREAD

**Issue by Seleneus98** [Asek3/Oculus#192]
### What happened?

After one minute or two in game enteties gain glow, when on fire is very noticeable.
First image is just when I load a world, second one after a couple minutes. 
It happens with rubidium + oculus, rubidium + magnesium extras + oculus, and rubidium + magnesium tools + dynamicLightsReForged + oculus.
Happens with all shaderpacks I've tested, most noticeable with Complementary Shaders v4. Does not happen with optifine.

### Screenshots

![1](https://user-images.githubusercontent.com/114293008/192097717-c98aefa7-8871-4d65-bf7e-6f6e292762e1.png)
![2](https://user-images.githubusercontent.com/114293008/192097722-3ce79cf6-5bf5-46e8-86a9-9334e2c55828.png)

### Minecraft Version

1.16.5

### Iris Version

oculus-1.2.6

### Sodium Version

rubidium-0.2.10

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3080 12 GB

### Java Version

Java 1.8.0_341

### Additional context

Thank you for your work. Your pice of software is amazing for the forge community.

**Comment by Asek3** [comment]
Fixed in 1.4.8
