### ISSUE TITLE
Oculus shaders breaks Neat health bars & player model transparency. 

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Oculus#195]
### What happened?

Oculus shaders breaks Neat mob health bars and stops them from rendering on top of mobs and makes the player model a bit transparent also renders mobs a little brighter white color and makes loot beams less transparent.

### Relevant log output

```shell
https://drive.google.com/file/d/1p4k6fReRqHw-neSf-A1DJV1U1t8DnDww/view?usp=sharing
```

### Minecraft Version

1.16.5

### Iris Version

1.16.5-1.2.6

### Sodium Version

1.16.5-0.2.10

### Operating System

win 10

### What is your GPU?

Nvidia Geforce RTX 3070ti

### Java Version

Java 8

**Comment by Asek3** [comment]
Fixed in 1.4.8
