### ISSUE TITLE
leather_chestplate missing texures

### ISSUE THREAD

**Issue by jihn47** [Asek3/Oculus#20]
![2022-02-21_20 45 08](https://user-images.githubusercontent.com/96333828/154949775-b29959bc-00c0-448c-98be-a8242538dce6.png)
![2022-02-21_20 45 18](https://user-images.githubusercontent.com/96333828/154949784-3b35104d-4654-46bf-b23c-8a81d99f6cac.png)

![2022-02-21_20 46 22](https://user-images.githubusercontent.com/96333828/154950002-0bb9f0c3-b792-48b6-886b-f7de5bf2e404.png)

**Comment by jihn47** [comment]
dont know if its rubidium's issue but i guess its oculus' bug?

**Comment by Grimmspecter** [comment]
having this issue to
