### ISSUE TITLE
Oculus crashes the game upon joining a world (StoneBlock 3)

### ISSUE THREAD

**Issue by ghost** [Asek3/Oculus#206]
### Minecraft Version

1.18.2

### Iris Version

Oculus 1.2.5a

### Sodium Version

Rubidium 0.5.4

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 2080 Super

### Java Version

Java 17

### Reproduction Steps

1. Add Rubidium and Oculus to StoneBlock 3
2. Create/join a world

### Additional context

[crash-2022-11-02_12.11.00-client.txt](https://github.com/Asek3/Oculus/files/9919778/crash-2022-11-02_12.11.00-client.txt)

**Comment by Glitched-Fox-Studios** [comment]
Getting same exact error and crash.

EDIT: Can confirm, Stoneblock 3 mod pack works just fine if you remove Oculus.

**Comment by ProjectGSX** [comment]
Im also running into this with SB3 and Oculus.

**Comment by Acidia5** [comment]
The crash is due to a conflict between Oculus and the Literal Sky Block mod as mentioned in issue #205 
You can fix the crash by just uninstalling the Literal Sky Block mod.

**Comment by Glitched-Fox-Studios** [comment]
Said mod is part of the modpack. Removing it would mess up the modpack. I do not find this to be an acceptable solution.

**Comment by ghost** [comment]
> The crash is due to a conflict between Oculus and the Literal Sky Block mod as mentioned in issue #205 You can fix the crash by just uninstalling the Literal Sky Block mod.

I guess I can close this issue then

**Comment by UrBoiTom** [comment]
> I guess I can close this issue then
No, it's not fixed, since Literal Skyblock is an essential part of the modpack and cannot be removed

**Comment by ghost** [comment]
> > I guess I can close this issue then
> > No, it's not fixed, since Literal Skyblock is an essential part of the modpack and cannot be removed

It's an incompatibility with Literal Sky Block, (which has been reported in #205 ), not SB3 as a whole. I don't see why this issue should be open when the other one is.

**Comment by SheroxGG** [comment]
Devepolers of both mods already know about this error, they are working on it. It has nothing to do with StoneBlock 3.

Literal Sky Block Report: https://github.com/nanite/Literal-Sky-Block/issues/3
Oculus Report: https://github.com/Asek3/Oculus/issues/205

@Radplay You can close it now.
Leaving this 2 Post so everyone can follow the problem on both side of the crash.
