### ISSUE TITLE
[1.16.5] Does not load half of shaders

### ISSUE THREAD

**Issue by viminio** [Asek3/Oculus#214]
### What happened?

1. Download Forge 1.16.5 - 36.2.39
2. Download Oculus 1.16.5 - 1.2.6
3. Try using shaders [Triliton's Shaders, Seus Renewed, AirLoocke Lite/Standard/High/Beta](![Download](https://github.com/CraftGXNetwork/UltraPack/tree/UltraPack/shaderpacks))
4. Read the millions of lines of error

### Screenshots

![2022-11-08_23 37 12](https://user-images.githubusercontent.com/62722905/200715403-6a00bdce-8a23-48e4-a50b-8a8e35832e04.png)

### Relevant log output

```shell
Latest.log - https://mclo.gs/Jw1E2jR
```

### Minecraft Version

Forge 1.16.5 - 36.2.39

### Iris Version

Oculus 1.16.5 - 1.2.6

### Sodium Version

Rubidium 1.16.5 - 0.2.10

### Operating System

Windows 10

### What is your GPU?

AMD Vega 8

### Java Version

Java 8 Update 321

### Additional context

In previous versions, shaders were rendered normally
I tried to make it as detailed as possible, sorry for any missing information.

**Comment by Asek3** [comment]
1.4 supports much more shaders but itself now
