### ISSUE TITLE
Crash on startup "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

### ISSUE THREAD

**Issue by AlcyonNorthstar** [Asek3/Oculus#22]
I'm using the [Medieval Minecraft [FORGE] 1.18.1 v6 modpack](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new).  I have added the latest (as of 2/21/2022 10 AM CST) five Mystical Agriculture mods to the modpack, and all works well.

I was going to next try Optifine, but the modpack says to remove [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) before doing so, which I did not want to do.  I was excited to see Rubidium's recommendation to use Oculus instead, which I am now attempting to try.

The game will not initialize with [Oculus mc1.18-1.2.1](https://www.curseforge.com/minecraft/mc-mods/oculus/files/3654792).  I am attaching my crash log for your reference.  I hope it helps with your continued development efforts.  

I'm glad to see more Optifine competition!

[crash-2022-02-21_12.39.30-client.txt](https://github.com/Asek3/Oculus/files/8111564/crash-2022-02-21_12.39.30-client.txt)

**Comment by Asek3** [comment]
Update Rubidium to 0.5.0
