### ISSUE TITLE
Oculus 1.4.3 version light shaders is not displayed

### ISSUE THREAD

**Issue by TH911** [Asek3/Oculus#225]
### What happened?

Shaders that can be loaded normally in version 1.2.6, but when I upgrade to version 1.4.3, all lights and shadows become invisible, although I only add rubidium and Oculus.

### Minecraft Version

1.16.5

### Oculus Version

Oculus-mc1.16.5-1.4.3

### Rubidium Version

0.2.10

### Operating System

windows11

### What is your GPU?

Intel®Iris(R)Xe Graphics

### Java Version

java8

**Comment by Lolothepro** [comment]
Give screenshots and log file.
