### ISSUE TITLE
[1.18.2]Crash when launching the game Incompatible with tombstone mod (mixin crash)

### ISSUE THREAD

**Issue by OcrSu** [Asek3/Oculus#229]
### Minecraft Version

1.18.2

### Oculus Version

oculus-1.4.3

### Sodium Version

rubidium-0.5.4

### Operating System

Win10

### What is your GPU?

XFX 5600xt

### Java Version

Java17

### Reproduction Steps

1.launch the game
2. Game Crashes
[crash-2022-11-25_08.28.52-client.txt](https://github.com/Asek3/Oculus/files/10087778/crash-2022-11-25_08.28.52-client.txt)
[crash-2022-11-25_08.32.06-client.txt](https://github.com/Asek3/Oculus/files/10087779/crash-2022-11-25_08.32.06-client.txt)

**Comment by Kasualix** [comment]
for mixin conflict, you'd better upload your latest.log instead of crash report

**Comment by OcrSu** [comment]
> 对于混合冲突，您最好上传最新的.log而不是崩溃报告
[2022-11-25-4.log](https://github.com/Asek3/Oculus/files/10089712/2022-11-25-4.log)
[2022-11-25-3.log](https://github.com/Asek3/Oculus/files/10089713/2022-11-25-3.log)

谢谢你的建议，thanks

**Comment by Kasualix** [comment]
是国人我就用中文了（

> Mixin apply failed irisflw.mixins.iris.json:MixinNewWorldRenderingPipeline -> net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching createShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/pipeline/newshader/FogMode;Z)Lnet/minecraft/client/renderer/ShaderInstance; in net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline for irisflw.mixins.iris.json:MixinNewWorldRenderingPipeline->@Invoker[METHOD_PROXY]::callCreateShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/pipeline/newshader/FogMode;Z)Lnet/minecraft/client/renderer/ShaderInstance; [INJECT Applicator Phase -> irisflw.mixins.iris.json:MixinNewWorldRenderingPipeline -> Apply Accessors ->  -> Locate -> irisflw.mixins.iris.json:MixinNewWorldRenderingPipeline->@Invoker[METHOD_PROXY]::callCreateShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/pipeline/newshader/FogMode;Z)Lnet/minecraft/client/renderer/ShaderInstance;]

看上去是 https://www.mcmod.cn/class/7283.html  的锅，删掉试试？

**Comment by Kasualix** [comment]
游戏一开就崩的 mixin 崩溃其实挺好解决的。不要看崩溃报告，看日志里崩溃报告上的 Mixin apply failed，除了代码文件路径之外的英文翻译一下看个大概，然后挑几个扎眼的 ModID 出来就知道问题出在哪个家伙上了。

**Comment by OcrSu** [comment]
我删除过了，还是会崩溃。这个模组pcl2提示有问题来着，但是删除后还是会崩溃。所以我上传了两个crash文件

> 游戏一开就崩的 mixin 崩溃其实挺好解决的。不要看崩溃报告，看日志里崩溃报告上的 Mixin apply failed，除了代码文件路径之外的英文翻译一下看个大概，然后挑几个扎眼的 ModID 出来就知道问题出在哪个家伙上了。

**Comment by OcrSu** [comment]
> > 
> 
> 我删除过了，还是会崩溃。这个模组pcl2提示有问题来着，但是删除后还是会崩溃。所以我上传了两个crash文件

再删除oculus模组后就正常了

**Comment by Kasualix** [comment]
这儿是3号的，上面的irisflw是4号的
tombstone跟Oculus的兼容寄了
> Mixin apply failed tombstone.mixins.json:NewShaderTestsMixin -> net.coderbot.iris.pipeline.newshader.NewShaderTests: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on tombstone.mixins.json:NewShaderTestsMixin->@Inject::methodMakeShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/shaderpack/loading/ProgramId;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/pipeline/newshader/ShaderAttributeInputs;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Ljava/util/function/Supplier;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZZZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> tombstone.mixins.json:NewShaderTestsMixin -> Apply Injections ->  -> Inject -> tombstone.mixins.json:NewShaderTestsMixin->@Inject::methodMakeShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]

**Comment by OcrSu** [comment]
> 这儿是3号的，上面的irisflw是4号的 tombstone跟Oculus的兼容寄了
> 
> > Mixin apply failed tombstone.mixins.json:NewShaderTestsMixin -> net.coderbot.iris.pipeline.newshader.NewShaderTests: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on tombstone.mixins.json:NewShaderTestsMixin->@Inject::methodMakeShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/shaderpack/loading/ProgramId;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/pipeline/newshader/ShaderAttributeInputs;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Ljava/util/function/Supplier;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZZZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> tombstone.mixins.json:NewShaderTestsMixin -> Apply Injections ->  -> Inject -> tombstone.mixins.json:NewShaderTestsMixin->@Inject::methodMakeShader(Ljava/lang/String;Lnet/coderbot/iris/shaderpack/ProgramSource;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/framebuffer/GlFramebuffer;Lnet/coderbot/iris/gl/blending/AlphaTest;Lcom/mojang/blaze3d/vertex/VertexFormat;Lnet/coderbot/iris/uniforms/FrameUpdateNotifier;Lnet/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline;Lnet/coderbot/iris/pipeline/newshader/FogMode;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]

对，感谢提醒，我想起pcl2在删除第一个模组后提示tombtone，我没在意:(  因为那个是我整合包中的一个必要元素。所以我习惯性忽视了这个问题。

**Comment by Kasualix** [comment]
还是先别更新Oculus版本了，这么大一个包，这么多模组难保不大寄特寄，等过段时间Oculus新版本稳定了再更不迟（

**Comment by OcrSu** [comment]
我咕咕咕了好久了，在等兰金计划更新，期间多试试其他新模组

**Comment by Kasualix** [comment]
不如试试[母爱](https://www.mcmod.cn/class/8019.html)然后把tombstone扬了？（雾

**Comment by OcrSu** [comment]
> 不如试试[母爱](https://www.mcmod.cn/class/8019.html)然后把tombstone扬了？（雾

有意思，有墓碑类功能，而且性能表现更高，我回去试试~v~

**Comment by CopperGiraffe** [comment]
Hi there, is there any update about this issue?

**Comment by Ghostcody** [comment]
I am also experiencing this issue, It works fine on oculus-mc1.18.2-1.2.5a though that does forgo a lot of the work and updates for oculus as of late.
