### ISSUE TITLE
Waving objects not working

### ISSUE THREAD

**Issue by Matthysse** [Asek3/Oculus#23]
Hello!
Here's a simple problem, visible on all shaders (tested with Complentary and Seus Renewed): grass, leaves etc. don't wave.
Everything else seem to work perfectly, thanks for this amazing port!

I have a nvidia GTX card if this can help.

**Comment by Asek3** [comment]
Resolved in [e1c8dea83a4b7876ddc92dfb52c97ddf79022544](https://github.com/Asek3/Rubidium/commit/e1c8dea83a4b7876ddc92dfb52c97ddf79022544)
Plz, update Rubidium
