### ISSUE TITLE
Flywheel/Create Incompatibility.

### ISSUE THREAD

**Issue by ShibeTemple** [Asek3/Oculus#24]
When placing a Create wheel down, the game crashes.

https://gist.github.com/ShibeTemple/66e7192b4cbd86e950db490ecbaa4128

**Comment by kaleinthepot** [comment]
yeah, having the same issue. game crashes whenever i place a create gear or grindwheel

**Comment by Asek3** [comment]
Try to disable Flywheel's backend

**Comment by kaleinthepot** [comment]
> Try to disable Flywheel's backend

how? configs?

**Comment by Asek3** [comment]
> > Try to disable Flywheel's backend
> 
> how? configs?

/flywheel backend off

**Comment by kaleinthepot** [comment]
> Try to disable Flywheel's backend

still crashes the game

**Comment by ShibeTemple** [comment]
Additionally, the world where the create block is placed is unjoinable with the mod.

**Comment by Asek3** [comment]
Flywheel on Forge has compatibility only with Optifine Shaders, plz report to their devs.

**Comment by ShibeTemple** [comment]
Are there any specific details I can provide, i.e. pipeline changes, to direct them?
