### ISSUE TITLE
Looping when entering a map!

### ISSUE THREAD

**Issue by seriousfreezing** [Asek3/Oculus#244]
### What happened?

I have updated my modpack that I made, so I can't log into my map anymore, as it keeps looping "Saving the map" as if I was already leaving the map!

### Screenshots

![image](https://user-images.githubusercontent.com/66693072/205391416-ff6453b1-cf2f-47fa-8ff1-6b2abb450445.png)

### Minecraft Version

Minecraft 1.19.2

### Oculus Version

oculus-mc1.19.2-1.2.8

### Rubidium Version

rubidium-0.6.2.jar

### Operating System

Windows 11 (22H2)

### What is your GPU?

RTX 3050 (Laptop)

### Java Version

Java 8 Update 341

**Comment by seriousfreezing** [comment]
Java SE 19, sorry!

**Comment by supershorty1** [comment]
seems a| incompatible issue with Oculus flywheel compat

**Comment by seriousfreezing** [comment]
Hmm, I get it but I don't have flywheel compat in my modpack and neither does mod create!

**Comment by seriousfreezing** [comment]
Is there a list of mods that are incompatible with Oculus?

**Comment by ArthixFR** [comment]
What's your Forge version ?

**Comment by seriousfreezing** [comment]
Forge 43.1.65

**Comment by ArthixFR** [comment]
You probably have the same problem as #243. Try to downgrade the forge version to 43.1.57

**Comment by seriousfreezing** [comment]
Hmm, I will try to downgrade the forge version, but in my case it doesn't crash or anything like that. It just keeps looping around saving the world anyway, but thanks for the tip!

**Comment by seriousfreezing** [comment]
I LOVE YOU MAN! I WAS ALMOST SCREWED SINCE I NEEDED TO MAKE THUMBNAILS AND YOU SAVED ME!

**Comment by seriousfreezing** [comment]
Okay, that version saved me during that time. However, the mods keep asking me to stay on the latest version of forge and that makes me very frustrated with Oculus, since Oculus does not do well at all with the current version of Forge!
