### ISSUE TITLE
Crash when I try to turn on minecraft

### ISSUE THREAD

**Issue by DrSigma4164** [Asek3/Oculus#250]
### Minecraft Version

1.19.2

### Oculus Version

1.2.8

### Sodium Version

0.6.2

### Operating System

Windows 10

### What is your GPU?

GTX 1660

### Java Version

Java 17 apparently

### Reproduction Steps

1) Click on the launch button in the launcher
2) Some time passes
3) An error pops up, I can't even see the minecraft loading screen

### Crash Report file and latest.log

```shell
https://pastebin.com/WWxHnUi7
```

**Comment by Looodon** [comment]
Downgrading forge to any version BEFORE 43.1.58 fixed it for me, hope it helps in the meantime

**Comment by Asek3** [comment]
Fixed in 1.2.8a
