### ISSUE TITLE
1.16.5 Pixelmon Incompatibility

### ISSUE THREAD

**Issue by ZayneBio** [Asek3/Oculus#252]
### What happened?

Models look polygonal when using shaders.

### Minecraft Version

1.16.5

### Oculus Version

oculus mc1.16.5-1.4.3

### Rubidium Version

rubidium mc1.16.5-0.2.10

### Operating System

Windows 11

### What is your GPU?

GTX 1650

### Java Version

Java 8

**Comment by Lolothepro** [comment]
Screenshot?

**Comment by ZayneBio** [comment]
> Screenshot?

https://media.discordapp.net/attachments/420682973319528448/1048043812129361940/image.png?width=1257&height=663 (sildurs)

https://media.discordapp.net/attachments/420682973319528448/1049837381437628506/2022-12-06_21.40.11.png?width=1257&height=663 (continuum)

also happens with chocapics, BSL, Complimentary, Seus. so basically all popular shaders
