### ISSUE TITLE
Weird Mixin Crash.

### ISSUE THREAD

**Issue by Xaligal** [Asek3/Oculus#253]
Crash log attached, crashes both with Complementary Reimagined shaders and without any shaders at all. Only other mods are Essential and William Wyther's Overhauled Overworld, both don't impact the crash. Tested with and without Rubidium's Addons. No clue what's causing it. 

[crash-2022-12-11_06.18.35-client.txt](https://github.com/Asek3/Oculus/files/10201523/crash-2022-12-11_06.18.35-client.txt)

**Comment by Willem07** [comment]
oculus does not work on forge version 43.2.0

**Comment by Asek3** [comment]
Fixed in 1.2.8a
