### ISSUE TITLE
[1.18.2]Initializing game When launch the game

### ISSUE THREAD

**Issue by OcrSu** [Asek3/Oculus#264]
### Minecraft Version

1.18.2

### Oculus Version

oculus-1.4.3

### Sodium Version

rubidium-0.5.4

### Operating System

Win10

### What is your GPU?

RX 6600 Gigabyte

### Java Version

Java17

### Reproduction Steps

1.launch the game
2. Game Crashes
[CrashReport-2022-12-26_12.43.12.zip](https://github.com/Asek3/Oculus/files/10301556/CrashReport-2022-12-26_12.43.12.zip)

**Comment by Proxwian** [comment]
How did you fixed it? Issue still exist on latest version

**Comment by OcrSu** [comment]
> oculus

remove oculus mod. This mod doesn't stop me from updating my modpack

**Comment by Proxwian** [comment]
Doesn't seems to be nice decision) And if problem still exist, don't close issue with mod

**Comment by OcrSu** [comment]
> Doesn't seems to be nice decision) And if problem still exist, don't close issue with mod

You are right. I thought this issue would be resolved in a few weeks. That doesn't seem to be the case now.
