### ISSUE TITLE
Crashing when trying to join moded server

### ISSUE THREAD

**Issue by TreeV2** [Asek3/Oculus#269]
### Minecraft Version

1.19.2

### Oculus Version

1.19.2-1.2.8

### Sodium Version

rubidium-0.6.2

### Operating System

Win 10

### What is your GPU?

Gtx 970

### Java Version

Java 17

### Reproduction Steps

1. Trying to join my friends server
2. Game Crashes

[latest.log](https://github.com/Asek3/Oculus/files/10333480/latest.log)
[crash-2023-01-02_22.01.24-client.txt](https://github.com/Asek3/Oculus/files/10333482/crash-2023-01-02_22.01.24-client.txt)

**Comment by lzyzl6** [comment]
you were using Forge 43.2.3,but the v1.2.8 Oculus will crash on Forge 43.1.58+
Update to the newest verison 1.2.8a will resolve the incompatibility between the Forge 43.1.58+ and Oculus.
Hoping for a positive change.(‾◡◝)

**Comment by Asek3** [comment]
Fixed in 1.2.8a
