### ISSUE TITLE
Oculus causing pack to crash

### ISSUE THREAD

**Issue by SmittyTheGod** [Asek3/Oculus#28]
When I try to launch Minecraft it crashes with this mod installed. It seems there could be a compatibility issue and wanted to see what could be causing it. I've provided my logs as well

[latest.log](https://github.com/Asek3/Oculus/files/8193531/latest.log)

**Comment by Asek3** [comment]
8375cb44a8ec6e1b3089f4a300b6b7ba53ec8393
