### ISSUE TITLE
Random lag when looking in specific direction

### ISSUE THREAD

**Issue by myron-obsolete-account** [Asek3/Oculus#287]
### What happened?

When I am looking at a specific direction spot in my world, my framerate drops from 60 to 30 FPS.
I am using Complementary shaders 4.6 and this issue does not occur without having shaders applied.

### Screenshots

Not a screenshot [but a video](https://www.youtube.com/watch?v=UMhP9xOl1Is)

### Minecraft Version

1.19.2

### Oculus Version

1.19.2 1.2.8a

### Rubidium Version

0.6.2

### Operating System

Windows 10 Home 64bit

### What is your GPU?

NVIDIA GeForce GTX 1660 SUPER

### Java Version

Java 18

### Additional context

Tested a different shaderpack, does not happen with other shaderpacks than Complementary. :(

**Comment by myron-obsolete-account** [comment]
*direction to look at to notice lag is between north and east and a bit downwards

**Comment by myron-obsolete-account** [comment]
allocated a little more RAM to minecraft, lag got reduced but is still kind of there, mostly when looking at sun- and moon along the horizon of the world

**Comment by Pokihead** [comment]
Do you have vsync activated?
If yes does it happen to if you deactivate vsync?
Is your GPU Load higher or lower if the fps drops?

**Comment by myron-obsolete-account** [comment]
> Do you have vsync activated? If yes does it happen to if you deactivate vsync? Is your GPU Load higher or lower if the fps drops?

I had my FPS capped to 60 my whole life, turning it to "infinity" (260 or so) reduces the lag by increasing the limit, so I think it's fine for now
