### ISSUE TITLE
1.16.5 Graphic Bug with Pixelmon Mod(9.1.2) when using shader.

### ISSUE THREAD

**Issue by LaShqipe** [Asek3/Oculus#306]
Graphic Bug when playing with PIxelmon Mod

There is a graphic bug when playing with Pixelmon Mod. The machines from the mod(healer,pc, etc...) start looking like shown in the video.
https://user-images.githubusercontent.com/125850720/220013972-117749f5-8d7c-4853-aa9c-1758b1432beb.mp4

### Minecraft Version

Minecraft 1.16.5

### Oculus Version

oculus 1.4.5

### Rubidium Version

rubidium 0.2.11

### Operating System

Windows 10

### What is your GPU?

Zotac Geforce RTX 3090

### Java Version

Java 8

**Comment by ZayneBio** [comment]
First, update to 9.1.3 Pixelmon and secondly it's a known bug where models of the smooth models go weird based on your shaders, however there's no current fix for the bug so just wait

**Comment by santiagortizgue** [comment]
Any update on this? 😄
