### ISSUE TITLE
[FORGE] NOT ENOUGH CRASHES WARNING ON STARTUP

### ISSUE THREAD

**Issue by Camawama** [Asek3/Oculus#313]
Either add a config option or get rid of the intrusive pop-up warning users about another mod. Besides, pretty sure they updated to support Mixins in version 4.2.0 so maybe your problem with the mod is fixed. 

P.S. MixinTrace and Crafty Crashes are both not available for 1.18.2 and that is the version I'm using while getting this error.

**Comment by Kasualix** [comment]
1.16.5 Forge Option: https://www.curseforge.com/minecraft/mc-mods/opotato

**Comment by Camawama** [comment]
I'm playing 1.18.2......

**Comment by Camawama** [comment]
ALRIGHT, you sending the link for 1.16.5 Forge Option didn't help at all and I am unable to find any solution to this problem. I can't even disable the pop-up using fancymenu because the pop-up is made on the same screen as the delete world confirmation screen. Anything I edit on it's screen will also edit on the delete world screen.

Please help me fix this.

**Comment by Asek3** [comment]
Fixed in Dev
