### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by myron-obsolete-account** [Asek3/Oculus#314]
**Is your feature request related to a problem? Please describe.**
Yes. I have one mod which got an update but it's on 1.19.3 so I basically got forced to move from 1.19.2 to 1.19.3, and the sad thing is that most mods I have aren't updated to 1.19.3 yet. However I wish to use shaders in 1.19.3 so yeah.

**Describe the solution you'd like**
An update for 1.19.3

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Composer-Hu** [comment]
I think you move from 1.19.2 to 1.19.3 is because of cracker's wither storm,or you have to use optifine instead of it,at least for now

**Comment by myron-obsolete-account** [comment]
> I think you move from 1.19.2 to 1.19.3 is because of cracker's wither storm,or you have to use optifine instead of it,at least for now

OptiFine creates rendering issues with CWSM that's why I am using Oculus

**Comment by myron-obsolete-account** [comment]
oh yeah nvm
