### ISSUE TITLE
Oculus incompatible with FlyWheel (i guess?)

### ISSUE THREAD

**Issue by Carrielzada** [Asek3/Oculus#32]
so here's the crashlog

important note: I already played that modded version with those mods installed, a few minutes ago I updated the mods, i don't remember if oculus or flywheel was included in that list, so anyway, try fix that pls :(

Minecraft 1.18.1
forge version 39.0.85
modpack: better minecraft plus 1.18.2 (v4 beta)
(but the minecraft still is in 1.18.1)

[crashlog-cut.txt](https://github.com/Asek3/Oculus/files/8337494/crashlog-cut.txt)

**Comment by Asek3** [comment]
Issue is resolved for 1.18.2, 1.18.1 wont be fixed
