### ISSUE TITLE
Mekasuit doesn't render with shaders

### ISSUE THREAD

**Issue by KostromDan** [Asek3/Oculus#338]
### What happened?

Mekanism users reguraly encounter this. Problem on your side.
https://github.com/mekanism/Mekanism/issues/7743
https://github.com/mekanism/Mekanism/issues/7729
https://github.com/mekanism/Mekanism/issues/7771

### Minecraft Version

1.19.2

### Oculus Version

oculus-mc1.19.2-1.2.8a.jar

### Rubidium Version

 rubidium-0.6.2a.jar

### Operating System

win 11

### What is your GPU?

3070ti

### Java Version

17

**Comment by bcrotty** [comment]
Not sure if this needs another bug, but Botania has several things that don't render at all as well:

- Mana in Mana Pools
- Sparks
- Gaia Guardian
- Middle crystal in pylons (Mana, Natura, Gaia)

**Comment by DancingSnow0517** [comment]
I have same issue with this

**Comment by Edel-Lilies** [comment]
long time issue from one year ago

**Comment by RyanHakurei** [comment]
Can confirm. Kinda sucks as this mod beats the hell out of Optifine in terms of performance.

![Screenshot - 2023-07-15 03-15](https://github.com/Asek3/Oculus/assets/5086636/075d817c-dd2e-4707-92fe-d1cf69b0cbda)
![Screenshot - 2023-07-15 03-15_2](https://github.com/Asek3/Oculus/assets/5086636/0dabcb36-16c4-4963-be51-d08c972a8ff5)
![Screenshot - 2023-07-15 03-15_3](https://github.com/Asek3/Oculus/assets/5086636/3adc3a62-45bf-46eb-9a11-3999ee96ce73)

**Comment by CSdiscoveries** [comment]
Can confirm, the issue happens with me as well. I would greatly appreciate a fix, as would many other people it seems.

**Comment by cryptofyre** [comment]
Bumping this, happening on 1.20.1 with Oculus.

**Comment by TypicalNeko** [comment]
I'ma bump as well as I really wanna use meka armor but I can't stand not being able to not see my hand. 1.18.2

**Comment by Landor151** [comment]
bumping too

**Comment by KostromDan** [comment]
This bug is duplicate of:
https://github.com/Asek3/Oculus/issues/170#issuecomment-2389938391

This msg has more info about what is going on with this bug.
