### ISSUE TITLE
{1.16.5} Minecraft is stuck on joining world screen for a really long time and then crashes

### ISSUE THREAD

**Issue by usernamewasalreadytakenlol** [Asek3/Oculus#36]
When i try to join a world minecraft gets stuck on the joining world screen for a really long time and then crashes.

The crash log
[crash-2022-04-01_19.57.10-client.txt](https://github.com/Asek3/Oculus/files/8400035/crash-2022-04-01_19.57.10-client.txt)

**Comment by Asek3** [comment]
Update Rubidium https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3728368
