### ISSUE TITLE
[1.16.5] Crash when attempting to save settings after selecting/deselecting a shaderpack, or disabling/enabling shaders

### ISSUE THREAD

**Issue by genderneutralnoun** [Asek3/Oculus#37]
What it says on the tin. I should also point out that there's no way to change a shaderpack's settings that I can find - the option is just greyed out. Crash log here. 
[crash-2022-04-01_15.17.26-client.txt](https://github.com/Asek3/Oculus/files/8400707/crash-2022-04-01_15.17.26-client.txt)

**Comment by Quickburst** [comment]
I get the same issue.

**Comment by Asek3** [comment]
Update Rubidium https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3728368
