### ISSUE TITLE
FPS drop between versions. (1.16.5)

### ISSUE THREAD

**Issue by Aarods** [Asek3/Oculus#370]
### What happened?

After switching versions between "Oculus mc1.16.5-1.4.5" and "Oculus mc1.16.5-1.2.6" with the same conditions, I noticed a drop in FPS between versions. I made a comparison between versions in the same world, same configuration and same position to see the result:

Oculus mc1.16.5-1.2.6:
![2023-05-24_12 20 44](https://github.com/Asek3/Oculus/assets/110215990/653e6ecb-8dc8-4913-8455-dbf8771d1955)
![2023-05-24_12 20 45](https://github.com/Asek3/Oculus/assets/110215990/6d6f94c6-3c95-4aa8-a57e-1987986e71fa)

Oculus mc1.16.5-1.4.5:
![2023-05-24_12 26 45](https://github.com/Asek3/Oculus/assets/110215990/b6566b0c-2d48-471f-aa42-750e976a7819)
![2023-05-24_12 23 57](https://github.com/Asek3/Oculus/assets/110215990/518df46a-085f-4127-9333-6e9bf994d385)

The result shows a change between 10 and 15 fps between versions. I didn't change any mod or anything else than Oculus.

### Minecraft Version

Minecraft 1.16.5

### Oculus Version

Oculus 1.16.5-1.4.5

### Rubidium Version

rubidium-0.2.11.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3060

### Java Version

Java 8

**Comment by Asek3** [comment]
This may be due to a variety of factors, including support for more shader features. Also updating Rubidium should increase performance
