### ISSUE TITLE
[1.16.5] Unable to join server with Oculus enabled

### ISSUE THREAD

**Issue by illogicaliam** [Asek3/Oculus#379]
### What happened?

When loading Minecraft 1.16.5 with Oculus installed, I am unable to join my modded server as it is deemed incompatible. Disabling Oculus lets me join. Since this mod is client side, I am confused as to why this happens in the first place. I have added my mod list below, in case there's an issue with other mods. 

### Screenshots

![modlist](https://github.com/Asek3/Oculus/assets/136255710/3ebb4602-3a02-4fdb-a778-484bbfc03108)

(Even though OptiFine is listed in the mods, it is disabled. Removing it or not doesn't resolve the issue.)

![incompatible](https://github.com/Asek3/Oculus/assets/136255710/a131b5c3-8926-4273-841f-11d0d58222ac)

### Minecraft Version

Minecraft 1.16.5

### Oculus Version

oculus-1.4.5.jar

### Rubidium Version

rubidium-0.2.12.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060 SUPER

### Java Version

Java 8

### Additional context

[2023-06-11-1.log](https://github.com/Asek3/Oculus/files/11715457/2023-06-11-1.log)

**Comment by SiverDX** [comment]
Why is Optifine (a client mod) installed on the server

And why do you have Optifine in your modlist, it's not compatible with Oculus

**Comment by illogicaliam** [comment]
> Why is Optifine (a client mod) installed on the server
> 
> And why do you have Optifine in your modlist, it's not compatible with Oculus

OptiFine has been removed from the server.

It's disabled in my mod list. Even straight up removing OptiFine from the mods doesn't change anything.

**Comment by PerilousBooklet** [comment]
Hi, I'm having the same problem and still haven't found a solution.
Since you (@illogicaliam) closed this issue, I assume you found the solution.
Could you please tell me how you solved this issue?
