### ISSUE TITLE
[1.16.5] Crash when joining world in a Modpack (ATM6)

### ISSUE THREAD

**Issue by Quickburst** [Asek3/Oculus#38]
When joining a world with Oculus installed, a crash occurs which is detailed in this report. Note that Rubidium works fine in the pack (ATM6) without it (Although it does have rendering issues with Immersive Engineering)
[crash-2022-04-02_14.19.07-client.txt](https://github.com/Asek3/Oculus/files/8401711/crash-2022-04-02_14.19.07-client.txt)
.

**Comment by SHXRKIEgg** [comment]
Same error here trying to add to Better Minecraft

**Comment by usernamewasalreadytakenlol** [comment]
I also have the same issue

**Comment by usernamewasalreadytakenlol** [comment]
I also get this issue without any other mods

**Comment by Asek3** [comment]
Update Rubidium https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3728368
