### ISSUE TITLE
Game crashes when loading world

### ISSUE THREAD

**Issue by Chickn-man** [Asek3/Oculus#382]
### Minecraft Version

Minecraft 1.20

### Oculus Version

oculus-mc1.20-1.6.4.jar

### Sodium Version

rubidium-0.6.5.jar

### Operating System

Linux 6.3.4-arch1-1 (Arch Linux)

### What is your GPU?

Nvidia GeForce RTX 3060

### Java Version

Java 17

### Reproduction Steps

1. Install a bunch of mods including Oculus
2. Launch Minecraft
3. Open "The New World"
4. Game Crashes
[crash-2023-06-13_14.15.14-client.txt](https://github.com/Asek3/Oculus/files/11737904/crash-2023-06-13_14.15.14-client.txt)
[latest.log](https://github.com/Asek3/Oculus/files/11737907/latest.log)
Mods List:
![Screenshot_20230613_141635](https://github.com/Asek3/Oculus/assets/85531727/6d7c36eb-1784-45f7-87d5-b9ce4f20c8cd)
[minecraft folder](https://www.mediafire.com/file/qw9mjpo38odfb5q/instance.zip/file)

### Crash Report file and latest.log

```shell
Check Reproduction Steps
```

### Additional context

It only crashes with Oculus installed.

**Comment by mysticdrew** [comment]
This is an issue with JourneyMap, it is fixed in `JourneyMap-1.20.1-5.9.10-forge` should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)
