### ISSUE TITLE
Incompatibility with Eating Animation

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Asek3/Oculus#386]
### Minecraft Version

Minecraft 1.20

### Oculus Version

oculus-mc1.20-1.6.4

### Sodium Version

rubidium-0.6.5

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 2070 Super

### Java Version

Java 16

### Reproduction Steps

1. Install Eating Animation version 5.0.0 along with Rubidium 0.6.5 and Oculus 1.6.4.
2. Start Minecraft,
3. Crash on startup.

### Crash Report file and latest.log

```shell
[crash-2023-06-18_13.32.55-client.txt](https://github.com/Asek3/Oculus/files/11781340/crash-2023-06-18_13.32.55-client.txt)
[latest.log](https://github.com/Asek3/Oculus/files/11781341/latest.log)

```

### Additional context

Running Forge 46.0.14.

**Comment by dima-dencep** [comment]
Missing language gml version [1,) wanted by eatinganimation-1.20-5.0.0.jar
