### ISSUE TITLE
Minecraft crashes with java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance

### ISSUE THREAD

**Issue by NeverFenrir** [Asek3/Oculus#419]
### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20-1.6.4.jar

### Sodium Version

rubidium-0.6.5.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce GTX 1650

### Java Version

Java 8

### Reproduction Steps

REQUIREMENTS: Have this mods installed, I suppose:
- Armourer’s workshop 2.0.2
- Auto third person 2.0.4
- Better combat 1.7.2
- CreativeCORE 2.10.29
- Farmer’s Delight 1.2.2a
- LittleTiles 1.6.0-pre053
- oculus 1.6.4
- polymorph 0.49.0
- rubidium 0.6.5

2. Initialize the game from the launcher.
3. The game will start loading but seems to crash when "loading bootstrap resources"

[latest.log](https://github.com/Asek3/Oculus/files/12143104/latest.log)
[crash-2023-07-24_09.28.20-client.txt](https://github.com/Asek3/Oculus/files/12143107/crash-2023-07-24_09.28.20-client.txt)

### Additional context

I think it might have to do with Oculus because it menstion Iris on the crash report. I'm not really sure though.

**Comment by NeverFenrir** [comment]
Sorry, I uploaded the crash report and log files where they don't belong. I didn't look at that part.

**Comment by SiverDX** [comment]
could you at least take a single second to open your own log files? it literally tells you whats wrong

**Comment by NeverFenrir** [comment]
@SiverDX 

Really sorry. When I opened the log I felt intimidated and thought I wouldn't be able to read it. My bad. It's the bettercombat mod requesting some mod called "playeranimator" and "clothconfig" right? I'll make sure to look at this files more often... Thank you for making me see it.
