### ISSUE TITLE
Crash on entering Nether

### ISSUE THREAD

**Issue by ChromaPIE** [Asek3/Oculus#42]
### Minecraft Version

1.16.5

### Iris Version

oculus-1.16.5-1.2.2

### Sodium Version

rubidium-0.2.5

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1650

### Java Version

Java 11

### Reproduction Steps

1. Try entering Nether
2. Ka-boom

Crash report: [crash-2022-04-10_10.56.33-client.txt](https://github.com/Asek3/Oculus/files/8458150/crash-2022-04-10_10.56.33-client.txt)

latest.log: [latest.log](https://github.com/Asek3/Oculus/files/8458154/latest.log)
 

### Additional context

Issue happened with Sildur's+Enhanced+Default+v1.131+Fancy activated. Did a few more tests and it turns out to be seemingly caused by the shaderpack. Complementary worked just fine, and the issue won't happen with shaders turned off. Just to make sure that the issue should purely be on the shaderpacks' end.

**Comment by Asek3** [comment]
Update Oculus and reopen issue if it still happens.
