### ISSUE TITLE
Keep on Crashing no matter what version

### ISSUE THREAD

**Issue by ZealousVult2283** [Asek3/Oculus#424]
### Minecraft Version

Minecraft 1.19.2, 1.20.1, and 1.18.2

### Oculus Version

Oculus 1.6.4 for the same versions as put above

### Sodium Version

rubidium 0.6.5 1.20

### Operating System

Windows 11 Pro

### What is your GPU?

AMD Radeon RX 6700 XT

### Java Version

Java 17

### Reproduction Steps

1. I play Minecraft with Oculus and Some other Great mods, (create, farmers delight, all mods made by Fuzs, the "Let's do" mods, and some other biome and decoration mods alongside those with their addons.
2. I launch the game and I see "MOD LOADING ERROR" and a few seconds afterwards, the middle part of the loading screen is black, and afterwars...
3. Game Crashes
[crash-2023-07-31_22.58.52-client2.txt](https://github.com/Asek3/Oculus/files/12228401/crash-2023-07-31_22.58.52-client2.txt)

### Additional context

I tried this with optifine and I fixed it but now I get the same issue

and here is another crash log by oculus, I would like it if someone could help me find the cause of both of thest.

[crash-2023-07-31_22.58.52-client.txt](https://github.com/Asek3/Oculus/files/12228412/crash-2023-07-31_22.58.52-client.txt)

**Comment by dima-dencep** [comment]
It's a create bug
And you also have optifine installed)
