### ISSUE TITLE
particles are visible through walls for a short time when picking up items or experience orbs

### ISSUE THREAD

**Issue by myron-obsolete-account** [Asek3/Oculus#438]
### What happened?

When mining blocks or killing monsters and collecting the items and/or experience orbs, (best noticable when underground) the particles that are around you, but behind block, get visible for like one or two ticks. This does not happen without Oculus.

### Screenshots

N/A

### Relevant log output

```shell
N/A
```

### Minecraft Version

1.20.1

### Oculus Version

1.20-1.6.4

### Rubidium Version

0.6.5

### Operating System

Windows 10 Home

### What is your GPU?

Nvidia GeForce GTX 1660 SUPER

### Java Version

probably Java 17, idk which one it is for 1.20.1

**Comment by OparsaO** [comment]
I have the same issue its super annoying

**Comment by Overtekk** [comment]
same one here but not always (on multiplayer when a friend pick item it do that)

**Comment by EmeraldLegate** [comment]
it is apparently caused by the pickup animation for items/xp
https://github.com/Asek3/Oculus/files/10095298/item-pickup-particle-disable-1.0.0.jar.zip
this fixes it by disabling said animations, this one works on 1.19.2 and 1.20.1

**Comment by myron-obsolete-account** [comment]
> it is apparently caused by the pickup animation for items/xp https://github.com/Asek3/Oculus/files/10095298/item-pickup-particle-disable-1.0.0.jar.zip this fixes it by disabling said animations, this one works on 1.19.2 and 1.20.1

thank you I was looking for this file someone else said a mod would disable it but didnt provide a link so I opened a new issue in hope someone would send it

**Comment by LaidBackSloth** [comment]
#149

**Comment by myron-obsolete-account** [comment]
> #149

idc this is already closed
