### ISSUE TITLE
Everything Appears Red when Using Oculus

### ISSUE THREAD

**Issue by PhweeDev** [Asek3/Oculus#45]
### What happened?

When joining a world and server with these mods (And Oculus by itself!) All of my game, including myself and my inventory render as a red tint.

![image](https://user-images.githubusercontent.com/44146422/162803111-0928be4b-3c3d-4256-9886-419ee3741625.png)
![image](https://user-images.githubusercontent.com/44146422/162803101-52c8e25a-b46c-4781-ab59-6e9051144151.png)

### Minecraft Version

1.16.5

### Iris Version

Oculus mc1.16.5-1.2.2

### Sodium Version

Rubidium mc1.16.5-0.2.5

### Operating System

WIndows 10

### What is your GPU?

AMD Ryzen 3 3250U

### Java Version

Java 8

**Comment by tangzixiang-hash** [comment]
iIt is suspected to be a problem with intel's built-in nuclear display. Mine is mx150, and it cannot be used. All items are lost in green.

**Comment by linux-leo** [comment]
im using a 5700g and have the same issue

**Comment by SunnyMenkov** [comment]
same

**Comment by Asek3** [comment]
Fixed, plz update Oculus
