### ISSUE TITLE
1.16.5 Shaders prevent "Chunk Fade" feature in Rubidium Extras from working

### ISSUE THREAD

**Issue by calreveraster** [Asek3/Oculus#450]
### What happened?

In 1.16.5 with Rubidium, Rubidium Extras and Oculus, when shaders are enabled the "chunk fade in" feature of Rubidium Extras ceases to function regardless of any other options selected. 

### Minecraft Version

1.16.5

### Oculus Version

1.4.5

### Rubidium Version

0.2.12

### Operating System

Windows 11

### What is your GPU?

GeForce RTX 3060

### Java Version

Java 8

### Additional context

I have also opened up a report on this in Rubidium Extras, but as I can't tell which "side of the fence" would need to perform a fix for this, I figured I'd open up an issue in both mods.

**Comment by Asek3** [comment]
Should be fixed on their end

**Comment by calreveraster** [comment]
> Should be fixed on their end

That was what felt sensible to me and is why I opened up over with them first, but I haven't taken enough of a look at the code of either mod to know, so I took the "err on the side of caution" route and opened up in both places. Hopefully it gets fixed!
