### ISSUE TITLE
Support for a dimension.properties file to allow for the addition of modded dimensions 

### ISSUE THREAD

**Issue by calreveraster** [Asek3/Oculus#451]
**Is your feature request related to a problem? Please describe.**

From 1.16 on, dimensions are called by their name (ie modName:dimensionName) instead of a numerical ID. This has made it impossible for shaders to detect modded dimensions. Consequently, Optifine, Iris and Oculus have all limited themselves to working with vanilla dimensions only, and applies the overworld effects to any modded dimensions as a result.

This becomes an issue in mods like Beyond Earth (which adds other planets that have no atmosphere, where things like clouds don't make sense) and Twilight Forest, which has no day/night cycle. 

**Describe the solution you'd like**
Optifine (and then eventually Iris) created a way to address the need to include modded blocks into shaders when this happened to block IDs by creating a block.properties file which could map block names to shader IDs. The same could (and should) be done for dimensions. 

So the recommended approach would be to create a dimension.properties file where dimension names could be manually mapped to  numerical dimension IDs and then parsed. 

**Describe alternatives you've considered**
There are none. The only alternative is to have modded dimensions permanently have overworld effects, disable desirable shader effects for the overworld, or eliminate all modded dimensions entirely from your pack.

**Additional context**
If Oculus added this, they'd be beating both optifine and iris to the punch. Just throwing that out there. :)

**Comment by calreveraster** [comment]
(as an aside I'd *really* like to see this on 1.16 specifically. Just throwing that out there)

**Comment by calreveraster** [comment]
small update on this, it looks like newer versions of iris now have said dimension.properties file, so I'm hoping to see it come to oculus soon.

**Comment by embeddedt** [comment]
This was added to 1.16 in https://github.com/Asek3/Oculus/commit/799f19bbaf542ff414c84a59517874ac3d992378
