### ISSUE TITLE
Crash on world load/creation

### ISSUE THREAD

**Issue by PenumbraStar** [Asek3/Oculus#46]
### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.2a

### Sodium Version

rubidium-0.5.2

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 3070 Ti

### Java Version

AdoptOpenJDK 17.0.2.8-Hotspot

### Reproduction Steps

1. Load Minecraft with Rubidium and Oculus
2. Attempt to create or load a world
3. Spawn Generates
4. Game Crashes

### Additional context

[crash-2022-04-12_08.13.27-client.txt](https://github.com/Asek3/Oculus/files/8472800/crash-2022-04-12_08.13.27-client.txt)
[latest.log](https://github.com/Asek3/Oculus/files/8472803/latest.log)

**Comment by Asek3** [comment]
Update Oculus and Rubidium
