### ISSUE TITLE
Please help me! I have crush

### ISSUE THREAD

**Issue by shlee7878** [Asek3/Oculus#461]
### Minecraft Version

1.19.2

### Oculus Version

 oculus-mc1.19.2-1.6.4.jar

### Sodium Version

Rubidium

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2060

### Java Version

java version 8

### Reproduction Steps

When I click play button and while processing that starting minecraft
[crash-2023-09-22_00.43.18-client.txt](https://github.com/Asek3/Oculus/files/12686749/crash-2023-09-22_00.43.18-client.txt)

**Comment by dima-dencep** [comment]
check dependencies
