### ISSUE TITLE
Crashes with Rubidium extra

### ISSUE THREAD

**Issue by ghost** [Asek3/Oculus#464]
### Minecraft Version

1.19.2

### Oculus Version

1.6.9

### Sodium Version

0.6.2c

### Operating System

windows 10

### What is your GPU?

RTX3070TI

### Java Version

JAVA17

### Reproduction Steps

1.install rubidium-extra-0.4.17+mc1.19.2-build.71. and oculus 1.6.9
2.game crashes
[latest.log](https://github.com/Asek3/Oculus/files/12702707/latest.log)
[crash-2023-09-22_23.23.27-client.txt](https://github.com/Asek3/Oculus/files/12702711/crash-2023-09-22_23.23.27-client.txt)

**Comment by Nycto97** [comment]
Can confirm. Running 300+ mods, tried to upgrade Oculus -> game crashes on start-up.
Removing Rubidium Extra 0.4.17 -> game launches fine.

**Comment by kawaiicakes** [comment]
+1. I have an identical stacktrace.

**Comment by ghost** [comment]
Fixed in the latest version of rubidium extra
