### ISSUE TITLE
Oculus + Rubidium -> crash exit code 1

### ISSUE THREAD

**Issue by yo-spooky** [Asek3/Oculus#466]
### Minecraft Version

Minecraft Forge 1.20.1

### Oculus Version

 oculus-mc1.20-1.6.4.jar

### Sodium Version

rubidium-mc1.20.1-0.7.0a.jar

### Operating System

Windows 10

### What is your GPU?

radeon rx 580

### Java Version

Java 8

### Reproduction Steps

Open Curseforge Launcher, create profile (forge - 47.2.0), install oculus-mc1.20-1.6.4.jar and rubidium-mc1.20.1-0.7.0a.jar, start the game -> you will get exit code 1

### Crash Report file and latest.log

```shell
don't have any crash reports cause the game crashes while starting (exit code 1)...
```

### Additional context

I tried to fix it with changing the mod versions, Rubidium mc1.20-0.6.5 for example but it didn't change anything...

**Comment by TheLolkPlays** [comment]
+1 Same here

Disabled all other mods, I got version oculus-mc1.20.1-1.6.15.jar

Exit code 1

NB; disabled Oculus was still crashing, seems to be Embeddium, tried different version, not working
