### ISSUE TITLE
Nostalgic Tweaks causing crash [1.20.1]

### ISSUE THREAD

**Issue by Its-Just-Luci** [Asek3/Oculus#467]
### Minecraft Version

1.20.1

### Oculus Version

1.20.1-1.6.4

### Sodium Version

rubidium-mc1.20.1-0.7.0a(1)

### Operating System

Windows 10

### What is your GPU?

RTX-2070

### Java Version

Java 16

### Reproduction Steps

1. Boot the game
2. Suffer

**Comment by Its-Just-Luci** [comment]
[debug.log](https://github.com/Asek3/Oculus/files/12707356/debug.log)
[latest.log](https://github.com/Asek3/Oculus/files/12707357/latest.log)

**Comment by TylerSky** [comment]
Did you find a fix?

**Comment by dima-dencep** [comment]
update oculus
