### ISSUE TITLE
crushed world rubidium with oculus [1.20.1]

### ISSUE THREAD

**Issue by idkwhoisit** [Asek3/Oculus#474]
### Minecraft Version

1.20.1

### Oculus Version

1.20.1

### Sodium Version

1.20.1-0.7.1

### Operating System

windows 11

### What is your GPU?

Nvidia geforce 1050 ti

### Java Version

java 8

### Reproduction Steps

1. Ran around the world
2. idk, probably new chanks were loading 
3. Game Crashes

 
4. when you enter the world again, it crashes after a couple of seconds

CRUSH REPORT HERE
[crash-2023-10-08_21.11.32-client.txt](https://github.com/Asek3/Oculus/files/12841422/crash-2023-10-08_21.11.32-client.txt)

**Comment by VanilaBOI** [comment]
I had the same thing happen too.
[crash-2023-10-17_19.05.37-client.txt](https://github.com/Asek3/Oculus/files/12937241/crash-2023-10-17_19.05.37-client.txt)

**Comment by jotadetc** [comment]
It crashes when lava comes into contact with tree leaves.

**Comment by nichharr** [comment]
Same thing is happening to me.

**Comment by Robonics** [comment]
[crash-2023-11-27_19.01.08-client.txt](https://github.com/Asek3/Oculus/files/13481889/crash-2023-11-27_19.01.08-client.txt)

Same issue, here is a full modlist:
<details>
<summary><h3>Modlist</h3></summary>
<ul>
<li>curios-forge-5.4.2+1.20.1.jar</li>
<li>irons_spellbooks-1.20.1-2.0.3.jar</li>
<li>resourcefullib-forge-1.20.1-2.1.16.jar</li>
<li>moonlight-1.20-2.8.65-forge.jar</li>
<li>aeroblender-1.20.1-1.0.1-neoforge.jar</li>
<li>alexsmobs-1.22.6.jar</li>
<li>Apotheosis-1.20.1-7.1.0.jar</li>
<li>apotheotic_additions1.2.jar</li>
<li>ApothicAttributes-1.20.1-1.2.0.jar</li>
<li>appleskin-forge-mc1.20.1-2.5.1.j</li>
<li>ararchitectury-9.1.12-forge.jar</li>
<li>AttributeFix-Forge-1.20.1-21.0.3.jar</li>
<li>AutoLeveling-1.20-1.19b.jar</li>
<li>balm-forge-1.20.1-7.1.4.jar</li>
<li>bettercombat-forge-1.8.1+1.20.1.jar</li>
<li>Bookshelf-Forge-1.20.1-20.1.6.jar</li>
<li>brutalbosses-1.20.1-6.6.jar</li>
<li>bygonenether-1.3.2-1.20.x.jar</li>
<li>caelus-forge-3.1.0+1.20.jar</li>
<li>cagedmobs-1.20.1-2.0.3.jar</li>
<li>catacalysm delight 1.20.1 - 0.1.1.jar</li>
<li>CataclysmWeaponery1.0.3-1.20.1.jar</li>
<li>ctov-3.3.6.jar</li>
<li>citadel-2.4.9-1.20.1.jar</li>
<li>cloth-config-11.1.106-forge.jar</li>
<li>combatroll-forge-1.3.0+1.20.1.jar</li>
<li>comforts-forge-6.3.4+1.20.1.jar</li>
<li>Controlling-forge-1.20.1-12.0.2.jar</li>
<li>tombstone-8.5.5-1.20.1.jar</li>
<li>corn_delight-1.0.3-1.20.1.jar</li>
<li>CrabbersDelight-1.20.1-1.1.3a.jar</li>
<li>create-1.20.1-0.5.1.f.jar</li>
<li>cupboard-1.20.1-2.1.jar</li>
<li>deep_aether-1.20.1-1.0.12.jar</li>
<li>deeperdarker-forge-1.20.1-1.2.1.jar</li>
<li>Delightful-1.20.1-3.4.2.jar</li>
<li>eastwardjourneys-1.20.1-1.0.4.jar</li>
<li>EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar</li>
<li>epicsamurai-0.0.29-1.20.1-forge.jar</li>
<li>ExplorersCompass-1.20.1-1.3.3-forge.jar</li>
<li>explorify-v1.3.0-mc1.20.jar</li>
<li>FarmersDelight-1.20.1-1.2.3.jar</li>
<li>FastLeafDecay-31.jar</li>
<li>Festive_Delight_1.1_1.20.1.jar</li>
<li>flib-1.20.1-0.0.11.jar</li>
<li>geckolib-forge-1.20.1-4.2.4.jar</li>
<li>guardvillagers-1.20.1-1.6.3.jar</li>
<li>handcrafted-forge-1.20.1-3.0.5.jar</li>
<li>TreeChop-1.20.1-forge-0.18.3.jar</li>
<li>Iceberg-1.20.1-forge-1.1.16.jar</li>
<li>IllagerInvasion-v8.0.3-1.20.1-Forge.jar</li>
<li>InsaneLib-1.12.1-mc1.20.1.jar</li>
<li>ironchest-1.20.1-14.4.4.jar</li>
<li>Jade-1.20.1-forge-11.6.3.jar</li>
<li>journeymap-1.20.1-5.9.18-forge.jar</li>
<li>jei-1.20.1-forge-15.2.0.27.jar</li>
<li>JustEnoughResources-1.20.1-1.4.0.238.jar</li>
<li>L_Enders_Cataclysm-1.39 -1.20.1.jar</li>
<li>LegendaryTooltips-1.20.1-forge-1.4.5.jar</li>
<li>mcw-bridges-2.1.1-mc1.20.1forge.jar</li>
<li>maturidelight-1.20.1-2.1.0.jar</li>
<li>dummmmmmy-1.20-1.8.10.jar</li>
<li>MouseTweaks-forge-mc1.20-2.25.jar</li>
<li>mysterious_mountain_lib-1.2.7-1.20.jar</li>
<li>NaturesCompass-1.20.1-1.11.2-forge.jar</li>
<li>nethersdelight-1.20.1-4.0.jar</li>
<li>netherportalfix-forge-1.20-13.0.0.jar</li>
<li>oceansdelight-1.0.2-1.20.jar</li>
<li>oculus-mc1.20.1-1.6.9.jar</li>
<li>Patchouli-1.20.1-83-FORGE.jar</li>
<li>PineappleDelight-Forge-1.0.7-Fix.jar</li>
<li>Placebo-1.20.1-8.5.8.jar</li>
<li>player-animation-lib-forge-1.0.2-rc1+1.20.jar</li>
<li>polymorph-forge-0.49.1+1.20.1.jar</li>
<li>Prism-1.20.1-forge-1.0.5.jar</li>
<li>ProgressiveBosses-3.9.5-mc1.20.1.jar</li>
<li>PuzzlesLib-v8.1.9-1.20.1-Forge.jar</li>
<li>rubidium-mc1.20.1-0.7.1.jar</li>
<li>Searchables-forge-1.20.1-1.0.2.jar</li>
<li>SereneSeasons-1.20.1-9.0.0.46.jar</li>
<li>sereneseasonfix-1.20.1-1.0.8.jar</li>
<li>serializationisbad-1.5.jar</li>
<li>SimpleStorageNetwork-1.20.1-1.10.0.jar</li>
<li>simplyswords-forge-1.51.5-1.20.1.jar</li>
<li>sophisticatedbackpacks-1.20.1-3.18.68.952.jar</li>
<li>sophisticatedcore-1.20.1-0.5.107.496.jar</li>
<li>supplementaries-1.20-2.6.31.jar</li>
<li>Swashbucklers 2.6.2 1.20.1.jar</li>
<li>TerraBlender-forge-1.20.1-3.0.0.169.jar</li>
<li>aether-1.20.1-1.0.0-beta.1.4-neoforge.jar</li>
<li>ToastControl-1.20.1-8.0.3.jar</li>
<li>TofuCraftReload-1.20.1-5.8.1.1.jar</li>
<li>torchmaster-20.1.5.jar</li>
<li>trade-cycling-forge-1.20.1-1.0.7.jar</li>
<li>Voidscape-1.20.1-1.5.310.jar</li>
<li>waystones-forge-1.20-14.0.2.jar</li>
<li>YungsApi-1.20-Forge-4.0.2.jar</li>
<li>YungsBetterDesertTemples-1.20-Forge-3.0.3.jar</li>
<li>YungsBetterDungeons-1.20-Forge-4.0.3.jar</li>
<li>YungsBetterEndIsland-1.20-Forge-2.0.4.jar</li>
<li>YungsBetterJungleTemples-1.20-Forge-2.0.4.jar</li>
<li>YungsBetterMineshafts-1.20-Forge-4.0.4.jar</li>
<li>YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar</li>
<li>YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar</li>
<li>YungsBetterStrongholds-1.20-Forge-4.0.3.jar</li>
<li>YungsBetterWitchHuts-1.20-Forge-3.0.3.jar</li>
</ul>
</details>

**Comment by dima-dencep** [comment]
It's a rubidium bug
