### ISSUE TITLE
Upgrading from Adoptium 17.0.1+12 to 17.0.8.1+1 makes Create Minecart Contraptions Invisible

### ISSUE THREAD

**Issue by ruifengx** [Asek3/Oculus#475]
### What happened?

I updated my JDK from Adoptium 17.0.1+12 to 17.0.8.1+1 (the current latest), and I noticed that assembled minecart contraptions become invisible. Their shadows are still rendered correctly, but the whole contraption is not rendered (the minecart is still visible). Disabling the shaders make the contraptions render again. Downgrading JDK fixes the problem.

So it seems there must be something changed in JDK and causes this misbehaviour. I do not have the time today, but maybe I can bisect to find the exact problematic version.

### Screenshots

| Adoptium 17.0.1+12<br>(Shader On) | Adoptium 17.0.8.1+1<br>(Shader On) | Adoptium 17.0.8.1+1<br>(Shader Off) |
|-|-|-|
| ![Correct](https://github.com/Asek3/Oculus/assets/77261059/b80c1be1-f24d-4cd5-8dee-a24a692475fe) | ![Incorrect](https://github.com/Asek3/Oculus/assets/77261059/8945649d-016c-4a35-a805-73c1d2a9f4f3) | ![WithoutShader](https://github.com/Asek3/Oculus/assets/77261059/f4fa9029-76d1-4a11-9cfa-f2fb80e0ff90) |

### Minecraft Version

Minecraft 1.18.2

### Oculus Version

oculus-mc1.18.2-1.6.4.jar

### Rubidium Version

rubidium-0.5.6.jar

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 2060 Max-Q

### Java Version

Java 17

**Comment by Naxdy** [comment]
Same problem.

**Comment by ruifengx** [comment]
May I know why this is closed? Is it a bug in JDK itself that has been fixed already? The screenshots I attached should confirm that this report was not made up.

**Comment by dima-dencep** [comment]
Use the version of java provided by the official launcher

**Comment by ruifengx** [comment]
Thanks. That's a bit unfortunate, but this issue might be fixed automatically after another JDK update, so probably not a big deal. Though I'd suggest that you document this requirement in your README and/or mod description page if you mean it seriously. Also, you may want to replace the "Java Version" field in the issue template with a similar warning.
