### ISSUE TITLE
ComputerCraft Monitor Rendering - Screen is Dark Without Shaders

### ISSUE THREAD

**Issue by cjsilman** [Asek3/Oculus#478]
### Issue

Without having shaders on, ComputerCraft monitors are dark, making it difficult to see text.

A s similar issue was fixed with Iris (see https://github.com/IrisShaders/Iris/issues/2053).

### Screenshots

![2023-10-14_17 22 55](https://github.com/Asek3/Oculus/assets/75451857/bafd95ec-43b8-497f-bccc-f87758cfcbaf)

![2023-10-14_17 25 11](https://github.com/Asek3/Oculus/assets/75451857/2d8a9a50-f861-4c35-a0e8-56df701d64cb)

### Relevant log output

NOne

### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.9

### Rubidium Version

embeddium-0.1.16+mc1.20.1

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3070ti

### Java Version

Java 17

**Comment by zenmetsu** [comment]
Replicated with Rubidium and Embeddium

**Comment by Argon42043** [comment]
I've got the same issue in the 1.19.2 version.
- Minecraft: 1.19.2
- Forge: 43.3.0
- Oculus: 1.6.9
- Rubidium: 0.6.2c
- CC: Tweaked: 1.101.3

- OS: Linux(Manjaro)
- GPU: Iris Xe Graphics (Intel Core i7-1165G7)
- Java: java-17-openjdk

When I have all mods of my mod list installed and not just these three, the text is not visible at all without shaders. But this might be a result of this issue or another one all together.
