### ISSUE TITLE
Oculus causing chunks not to load properly

### ISSUE THREAD

**Issue by MSFortuneBlack** [Asek3/Oculus#479]
### What happened?

When running Oculus, Chunks dont load correctly, with some chunks remaining unloaded when standing right on it, some chunks will also randomly unload.

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.9.jar

### Rubidium Version

Rubidium causes whole game to crash

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 3070

### Java Version

no clue

![2023-10-20_11 51 02](https://github.com/Asek3/Oculus/assets/37426127/96be1a16-cd58-4c19-8db0-6c3c68cb05b1)

**Comment by RegalRuffRaff** [comment]
Been having the same issue. I've been checking all my recent mods, but even removing Oculus causes the problem to persist with Embeddium. Now I'm not sure which is causing it, as an older version of Embeddium with 1.6.9 Oculus was running just fine.
