### ISSUE TITLE
Minecolonies Bug with Oculus

### ISSUE THREAD

**Issue by SHXRKIEgg** [Asek3/Oculus#5]
Check here for the Issue https://github.com/LunaPixelStudios/Medieval-Minecraft/issues/96#issuecomment-1062769844

Minecolonies Icons bugging out with Oculus

**Comment by LSuende** [comment]
Open your minecolonies mod as .zip，go in \assets\minecolonies\textures\icons\ , edit the image recruiticon.png transparent as sRGB mode or simply delete it. The problem would be superficially solved. (

**Comment by SHXRKIEgg** [comment]
I cant edit jars in the modpack so this isnt an option

**Comment by nickmuenster** [comment]
Hey i hope this is the right place to ask. I have the same issue. is there a way to fix that? or a workaround?
Maybe a way to disable the notification symbols all together? 

since oculus has the same issue after all

**Comment by tpl20000** [comment]
I've made some icons transparent which "solved" the problem.
https://mega.nz/file/KHJ2UQST#UQ3nOePvmJsYCx3QiXynezRVQx8P8J8MEaRtBMHaeKg
(Only three icons altered at \assets\minecolonies\textures\icons)

**Comment by Shadows-of-Fire** [comment]
Tracking via #84 (fix available, PR pending to minecolonies)

**Comment by Asek3** [comment]
Update mods, should be fixed now
