### ISSUE TITLE
Create Mod Transparency

### ISSUE THREAD

**Issue by SillySoon** [Asek3/Oculus#50]
### What happened?

If I use Oculus with the famous mod Create, 3D Items or else are Transparent.

### Screenshots

Expectations:
![grafik](https://user-images.githubusercontent.com/57587656/163689097-944380dc-2f21-4e2a-9acf-4620cc3ce1a8.png)

With Oculus:
![grafik](https://user-images.githubusercontent.com/57587656/163689063-20f90914-19b9-454e-930b-fecfe9d41900.png)

### Minecraft Version

Minecraft Forge 1.18.2 (40.0.52)

### Iris Version

Not in the Pack

### Sodium Version

Not in the Pack

### Operating System

Windows 10 Pro

### What is your GPU?

MSI RTX 3070 Supreme

### Java Version

Java 8 Update 321 (Build 1.8.0_321-b07)

### Additional context

Im using the Unofficial Sodium Fork **Rubidium** (rubidium-0.5.2a.jar) The bug doesn't happen with only Rubidium installed.

**To the Logs**
There is nothing special to see in the Logs, but here:
[latest.log](https://github.com/Asek3/Oculus/files/8500550/latest.log)

**Comment by literallypan** [comment]
I have this problem as well. It turns 3D models like the water wheel invisible.

**Comment by Asek3** [comment]
Resolved in 1.2.4
