### ISSUE TITLE
Horse Marking and Horse Armor rendering conflict

### ISSUE THREAD

**Issue by Uraneptus** [Asek3/Oculus#506]
### What happened?

It seems like the `HorseMarkingLayer` is rendered above the `HorseArmorLayer` for some reason. Happens with any armor (even modded ones).

### Screenshots

![2023-12-10_20 18 06](https://github.com/Asek3/Oculus/assets/50745606/254f62c6-d86c-4cf6-8f3c-041c2d9255de)

### Minecraft Version

1.20.1

### Oculus Version

1.20.1-1.6.9

### Rubidium Version

1.20.1-0.7.1

### Operating System

Windows 10

### What is your GPU?

Nivida Geforce RTX 2070 super

### Java Version

17

### Additional context

Forge version: 47.1.0

Debug log: [debug.log](https://github.com/Asek3/Oculus/files/13628955/debug.log)

No other mod is installed and I used the default graphic settings.!

**Comment by dima-dencep** [comment]
update oculus

**Comment by spacialflaw** [comment]
> update oculus

Encountering the same problem on 1.20.1-1.6.15a
