### ISSUE TITLE
crash with creat potato cannon and laendli transport weapons

### ISSUE THREAD

**Issue by Tsumiki129** [Asek3/Oculus#508]
### Minecraft Version

minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.9.jar

### Sodium Version

embeddium-0.2.12+mc1.20.1.jar

### Operating System

windows 10

### What is your GPU?

Nvidia geforce gtx 1660

### Java Version

java 17

### Reproduction Steps

1. kill any mob with potato cannon from create or guns from laendli transport weapons
2. Game Crashes

### Crash Report file and latest.log

```shell
https://mclo.gs/zDO2Jtx
```

**Comment by dima-dencep** [comment]
Update oculus
