### ISSUE TITLE
Tools disappear when using shaders

### ISSUE THREAD

**Issue by DankestO** [Asek3/Oculus#509]
### What happened?

In the new update 1.6.13, when I use shaders (in this case "Complementary Shaders - Reimagined"), for some reason the tools held in the hand disappear, this curiously did not happen in the previous update (1.6.9)
The pickaxe I use is from the Truly Modular mod.

### Screenshots

![Captura de pantalla 2023-12-12 232112](https://github.com/Asek3/Oculus/assets/126206944/ee1f923a-d02a-4edc-8910-51ca561e3f84)
![Captura de pantalla 2023-12-12 231616](https://github.com/Asek3/Oculus/assets/126206944/de5c7cc7-f774-4af6-aa66-a09411d19b25)

### Minecraft Version

1.20.1

### Oculus Version

1.6.13

### Rubidium Version

Embeddium 0.2.13

### Operating System

Win 11

### What is your GPU?

RX5700

### Java Version

Java included in the Microsoft launcher

**Comment by dima-dencep** [comment]
Try https://github.com/Asek3/Oculus/suites/19038686205/artifacts/1114168142

**Comment by Nycto97** [comment]
This also happens with the Fiery tools from The Twilight Forest. I play on 1.19.2 with Oculus 1.6.9.

**Comment by DankestO** [comment]
With the latest updates I no longer have this problem. thanks! 👍
