### ISSUE TITLE
1.16.5 Hotbar items turn screen white on disabling shaders.

### ISSUE THREAD

**Issue by SKPNeon** [Asek3/Oculus#51]
### What happened?

When Disabling Shaders, having items in my hotbar will cause the screen to turn a heavy tinted white. re-enabling shaders then removing the items before turning off again fixes the issue but this defentetly should not happen. 

### Screenshots

![e8cc02ae0b0fecc2a2f67770eca08262](https://user-images.githubusercontent.com/36781416/163689734-8135cd51-7bbb-400b-bdbb-081b4584545a.png)

### Minecraft Version

Minecraft 1.16.5

### Iris Version

Oculus 1.2.2

### Sodium Version

Rubidium 0.2.5

### Operating System

Windows 10

### What is your GPU?

GTX 1070

### Java Version

Java 1.8.0_51 64Bit

### Additional context

Tested on Forge 36.2.26 with only Rubidium and oculus Installed. Used Complimentary Shaders and Prismarine Shaders, Both had same issue.

**Comment by KarinMiku** [comment]
i can confirm this bug, it isnt really a game-breaking problem since i just stay playing with shaders but i wont deny that is a bit annoying

**Comment by Asek3** [comment]
Fixed, plz update Oculus
