### ISSUE TITLE
1.20.1 - Unknown in-game crash with rubidium

### ISSUE THREAD

**Issue by abrossimow** [Asek3/Oculus#512]
### Minecraft Version

1.20.1

### Oculus Version

oculus_-mc1.20.1-1.6.13

### Sodium Version

rubidium-mc1.20.1-0.7.1a

### Operating System

Windows 11

### What is your GPU?

RTX3090

### Java Version

Java 17

### Reproduction Steps

1. Load World
2. Crash.
[crash-2023-12-16_10.52.51-client.txt](https://github.com/Asek3/Oculus/files/13692189/crash-2023-12-16_10.52.51-client.txt)
[2023-12-16-7.log](https://github.com/Asek3/Oculus/files/13692190/2023-12-16-7.log)

**Comment by embeddedt** [comment]
Use Embeddium instead of Rubidium.
