### ISSUE TITLE
Create Mod's Machines Invisible

### ISSUE THREAD

**Issue by literallypan** [Asek3/Oculus#52]
### What happened?

Animated machines in the Create mod such as water wheels are invisible when Oculus is active. I removed the mod and it fixed the invisible glitch.

### Minecraft Version

Minecraft 1.18.2

### Iris Version

oculus-mc1.18.2-1.2.2b

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 11

### What is your GPU?

MSI Geforce RTX 3070

### Java Version

Java 16

**Comment by dystopiawrlnd** [comment]
same problem here

**Comment by Asek3** [comment]
Resolved in 1.2.4
