### ISSUE TITLE
java.lang.IllegalStateException: Already in a group

### ISSUE THREAD

**Issue by MikeyPantsOn** [Asek3/Oculus#523]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.13.jar

### Sodium Version

embeddium-0.2.16+mc1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 3060

### Java Version

Java 17.0.7 2023-04-18 LTS

### Reproduction Steps

1. Launch minecraft with all other mods in the modlist which is in the latest log and the crash report.
2. Join a server.
3. After 10 minutes it elapse, the game crashes.

### Additional context

latest.log and crash report too long for body, 
latest.log pastebin: [https://pastebin.com/tUQc6EMz](https://pastebin.com/tUQc6EMz)
crash report pastebin: [https://pastebin.com/yMHPaVSp](https://pastebin.com/yMHPaVSp)

**Comment by nasapierce** [comment]
### Minecraft Version
1.20.1

### Oculus Version
oculus-mc1.20.1-1.6.13.jar

### Sodium Version
embeddium-0.2.16+mc1.20.1.jar

### Operating System
Windows 10

### What is your GPU?
Nvidia Geforce RTX 2070 Super

### Java Version
Java 17.0.8

### Reproduction Steps
    Launch minecraft with all other mods in the modlist which is in the latest log and the crash report.
    Load Single Player World.
    After a few seconds screen turns white and crashes.

### Crash Report file and latest.log
latest.log pastebin: https://pastebin.com/U7UePi3U
crash report pastebin: https://pastebin.com/tyf9Grh7

### Additional Context
Disabling Shader in-game stops the crash. Shader is Complementary Reimagined - 5.1.1

**Comment by lanwoodall423** [comment]
[crash-2024-01-09_18.54.28-client.txt](https://github.com/Asek3/Oculus/files/13881345/crash-2024-01-09_18.54.28-client.txt)
same issue. Crashes even with shaders disabled for me.

**Comment by lanwoodall423** [comment]
I upgraded Oculus to the latest oculus-mc1.20.1-1.6.13a.jar using the fix provided in another issue and still get this same crash on world load.

**Comment by lanwoodall423** [comment]
Still getting this

**Comment by lanwoodall423** [comment]
I think this issue is resolved by removing the entity culling mod. Something else associated with embeddium is adding entity culling features as I still see them in the menus after it's disabled but I'm no longer getting the crash.
