### ISSUE TITLE
oculus is not a valid jar file 1.20.1 forge 47.2.0

### ISSUE THREAD

**Issue by Thunderrock424242** [Asek3/Oculus#525]
### What happened?

A bug happened! loading errors 

### Screenshots

[latest.log](https://github.com/Asek3/Oculus/files/13801910/latest.log)

### Minecraft Version

1.20.1

### Oculus Version

1.16.13a

### Rubidium Version

n/a using embedium latest

### Operating System

windows 11

### What is your GPU?

nivida geforce rtx 4060 laptop

### Java Version

java 17 i think 

### Additional context

![Screenshot 2023-12-31 130745](https://github.com/Asek3/Oculus/assets/119463825/d1802f14-f1fd-4de7-acc8-d12a8efa1bd3)

**Comment by Thunderrock424242** [comment]
nvm its not still playable only 2 mods our of 430 loaded

**Comment by VOLKOUL** [comment]
Same thing here. I am using NeoForge 1.20.1 however. After updating Oculus along with Embeddium I get an error screen on startup with a list of all the fabric mods running on Connector and the "Oculus is not a valid jar file" message.

**Comment by rudugampola** [comment]
I got the same error, I have 387 mods but only 2 got loaded. Ended up downgrading just for now

**Comment by ModernGamingWorld** [comment]
Same Just got this error and I have like 400 mods

**Comment by ModernGamingWorld** [comment]
found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@127705e4
net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing required field mandatory in dependency (oculus-mc1.20.1-1.6.13a.jar)
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.lambda$new$1(ModInfo.java:216) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.<init>(ModInfo.java:216) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$7(ModInfo.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.<init>(ModInfo.java:100) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:85) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:86) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:47) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:52) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164) ~[fmlloader-1.20.1-47.2.19.jar:1.0]
	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.20.1-47.2.19.jar:1.0]
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.9.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by BrandonPotter0** [comment]
I can confirm I have this issue as well. Wont load for me at all.

**Comment by glea94** [comment]
I don't want to report a bug because i don't see any work done ont the oculus code page like showing something done few hours ago or 1 days ago.
I compare it to embendium where you can follow the time
Add a system property to allow disabling the render layer cache | 3 hours ago
There is nothing about oculus-mc1.20.1-1.6.13a version.. The last work has been done the last week for the version 13. So becarefull about this update.

**Comment by glea94** [comment]
> I don't want to report a bug because i don't see any work done ont the oculus code page like showing something done few hours ago or 1 days ago. I compare it to embendium where you can follow the time Add a system property to allow disabling the render layer cache | 3 hours ago There is nothing about oculus-mc1.20.1-1.6.13a version.. The last work has been done the last week for the version 13. So becarefull about this update.

So i wanted to check inside and see that mod.toml was different, i deleted the last part of it, 7z asked me if i want to record the changes, i click yes and this windows happened
![image](https://github.com/Asek3/Oculus/assets/89050166/d0bfdce2-ff3b-4176-85ea-26679ced347c)
It says it get a virus, windows defender open also a pop up to tell me the same.
So beware this "update", maybe the modrinth and curseforge are hacked but not the github : there is no info on last works at all on oculus.
![image](https://github.com/Asek3/Oculus/assets/89050166/7d746a74-fae8-4f49-a67b-683d8abf76d6)
Another windows if i want to delete the file : i can't
![image](https://github.com/Asek3/Oculus/assets/89050166/64b0d3dc-31df-4d58-af63-6babeb0113ba)

**Comment by glea94** [comment]
Update about the file i can't delete.
I went into windows defender protection settings and saw in authorized program that i have a keygen with low restriction
so i deleted it and now i can delete this "oculus update" to the trash.

**Comment by rudugampola** [comment]
Wow this took a turn for the worse. It's possible it wasn't pushed to github? Can someone confirm what @glea94  mentioned

**Comment by glea94** [comment]
> Wow this took a turn for the worse. It's possible it wasn't pushed to github? Can someone confirm what @glea94 mentioned

I actually doing a scan... got 1 object detected
![image](https://github.com/Asek3/Oculus/assets/89050166/29802a7d-1b02-47ae-9932-65c5953b15a1)
Wait until the scan is done I got nothing before, my scann run every 2 days automatically..

**Comment by rudugampola** [comment]
I would checkout Discord inspector gadget

**Comment by LordM4x** [comment]
I have the exact same issue, except when I downgrade oculus it also just won't work.

**Comment by VOLKOUL** [comment]
Downgrade to Embeddium 13 also.

**Comment by LordM4x** [comment]
that did not change anything it still does not work

**Comment by VOLKOUL** [comment]
¯\_(ツ)_/¯

**Comment by Hir0shiyt** [comment]
Same issue here, it lets me open the jar file and it says "This file is the Forge version of Oculus, meant to be installed as a mod. Would you like to get the Forge Installer instead? [Yes]   [No]"

**Comment by kittykiller** [comment]
I seem to have found a fix.
1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
2. open the "META-INF" folder
3. drag the file "mods.toml" to desktop
4. open "mods.toml" from the desktop with notepad
5. delete 
[[dependencies.oculus]]
modId = "embeddium"
versionRange = "[0.2.14,)"
ordering = "NONE"
side = "CLIENT"
6. Save "mods.toml"
7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF\" in 7-zip
8. say yes when it asks to copy files to archive

**Comment by LordM4x** [comment]
> I seem to have found a fix.
> 
> 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> 2. open the "META-INF" folder
> 3. drag the file "mods.toml" to desktop
> 4. open "mods.toml" from the desktop with notepad
> 5. delete
>    [[dependencies.oculus]]
>    modId = "embeddium"
>    versionRange = "[0.2.14,)"
>    ordering = "NONE"
>    side = "CLIENT"
> 6. Save "mods.toml"
> 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> 8. say yes when it asks to copy files to archive

I dont have that dependency in my mods.toml, odd...

**Comment by DaemonUmbra** [comment]
> found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@127705e4 net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing required field mandatory in dependency (oculus-mc1.20.1-1.6.13a.jar) at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.lambda$new$1(ModInfo.java:216) ~[fmlloader-1.20.1-47.2.19.jar:?] at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.(ModInfo.java:216) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$7(ModInfo.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] at net.minecraftforge.fml.loading.moddiscovery.ModInfo.(ModInfo.java:100) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:85) ~[fmlloader-1.20.1-47.2.19.jar:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.(ModFileInfo.java:86) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:47) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModFile.(ModFile.java:79) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModFile.(ModFile.java:68) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:52) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19) ~[fmlloader-1.20.1-47.2.19.jar:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?] at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75) ~[fmlloader-1.20.1-47.2.19.jar:?] at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164) ~[fmlloader-1.20.1-47.2.19.jar:1.0] at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.20.1-47.2.19.jar:1.0] at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.9.jar:?] at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.9.jar:?] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) ~[modlauncher-10.0.9.jar:?] at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) ~[modlauncher-10.0.9.jar:?] at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar:?] at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

If this log is accurate the issue has been addressed by c730f72740dfbe1728e2b51fe1b6f96bd566e591 and just hasn't been included in a release build yet

**Comment by glea94** [comment]
> I seem to have found a fix.
> 
> 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> 2. open the "META-INF" folder
> 3. drag the file "mods.toml" to desktop
> 4. open "mods.toml" from the desktop with notepad
> 5. delete
>    [[dependencies.oculus]]
>    modId = "embeddium"
>    versionRange = "[0.2.14,)"
>    ordering = "NONE"
>    side = "CLIENT"
> 6. Save "mods.toml"
> 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> 8. say yes when it asks to copy files to archive

I've done this is when i wanted to record and change that i got the virus popup about it.

**Comment by AsheX1** [comment]
> > I seem to have found a fix.
> > 
> > 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> > 2. open the "META-INF" folder
> > 3. drag the file "mods.toml" to desktop
> > 4. open "mods.toml" from the desktop with notepad
> > 5. delete
> >    [[dependencies.oculus]]
> >    modId = "embeddium"
> >    versionRange = "[0.2.14,)"
> >    ordering = "NONE"
> >    side = "CLIENT"
> > 6. Save "mods.toml"
> > 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> > 8. say yes when it asks to copy files to archive
> 
> I've done this is when i wanted to record and change that i got the virus popup about it.

what are you even doing i have done this now on 4 diffrent PC's and never got windows defender to pop up maybe you have a virus some where els on your PC 

2 pc are windows 10 the other 2 PC are windows 11

and yes deleting those lines fixes the problem of invalid mod jar something something

**Comment by AsheX1** [comment]
also clicking the oculus jar creates a pop up to asking/saying

This File is the Forge version of Oculus, meant to be installed as a mod. Would you like to get the Forge installer instead?

[ YES ]    [ NO ]

maybe a good idea to also update java

you can get for what ever OS you are using here https://adoptium.net/temurin/releases/?variant=openjdk8&jvmVariant=hotspot&os=any&arch=x64&package=jdk&version=17

or you google java SE and get java from oracle website https://www.oracle.com/java/technologies/downloads/#jdk17-windows

pretty sure there is also a version from amazon for java called krokete something something ( i do not recommend that as it seems to change stuff in the code and alot of minecraft mods dont work with it ) stick with adoptium temurin java or oracle java

if you are using the curseforge launcher (not my problem the launcher is shit)
if you are using the default minecraft launcher (same as above hate it)

recommend multiMC
or Prism Launcher (is a fork of multiMC with alot more functions)

**Comment by AsheX1** [comment]
also anyone els wanne test this just dubbel click the oculus-mc1.20.1-1.6.13a.jar
to see if you get a popup from windows defender

i can also just spin up all my vm's to test every windows 10 build and windows 11 build but i feel like its gone be pointless

**Comment by bobabiba** [comment]
> I seem to have found a fix.
> 
> 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> 2. open the "META-INF" folder
> 3. drag the file "mods.toml" to desktop
> 4. open "mods.toml" from the desktop with notepad
> 5. delete
>    [[dependencies.oculus]]
>    modId = "embeddium"
>    versionRange = "[0.2.14,)"
>    ordering = "NONE"
>    side = "CLIENT"
> 6. Save "mods.toml"
> 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> 8. say yes when it asks to copy files to archive

when I did this my game just crashed and reported an error and popped up the logs.

**Comment by AsheX1** [comment]
> > I seem to have found a fix.
> > 
> > 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> > 2. open the "META-INF" folder
> > 3. drag the file "mods.toml" to desktop
> > 4. open "mods.toml" from the desktop with notepad
> > 5. delete
> >    [[dependencies.oculus]]
> >    modId = "embeddium"
> >    versionRange = "[0.2.14,)"
> >    ordering = "NONE"
> >    side = "CLIENT"
> > 6. Save "mods.toml"
> > 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> > 8. say yes when it asks to copy files to archive
> 
> when I did this my game just crashed and reported an error and popped up the logs.

then you must be doing it wrong as it does work

here is pic of how the file needs to look 
![image](https://github.com/Asek3/Oculus/assets/6249407/ab375841-d731-4e23-8109-4388cbb0da03)

**Comment by AsheX1** [comment]
and i don't know in what program you are editing the file but if its on and old notepad version of windows then there is good chance that is gone fuck up the file order
i recommend just using notepad++ for editing any config/txt file

https://notepad-plus-plus.org/

**Comment by AsheX1** [comment]
> > I seem to have found a fix.
> > 
> > 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> > 2. open the "META-INF" folder
> > 3. drag the file "mods.toml" to desktop
> > 4. open "mods.toml" from the desktop with notepad
> > 5. delete
> >    [[dependencies.oculus]]
> >    modId = "embeddium"
> >    versionRange = "[0.2.14,)"
> >    ordering = "NONE"
> >    side = "CLIENT"
> > 6. Save "mods.toml"
> > 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> > 8. say yes when it asks to copy files to archive
> 
> when I did this my game just crashed and reported an error and popped up the logs.

maybe also update forge? or neoforge? are you using java 17 or higher

i use neoforge  for 1.20.1

**Comment by 7777777-4547** [comment]
> I seem to have found a fix.
> 
> 1. open "oculus-mc1.20.1-1.6.13a.jar" with 7-zip
> 2. open the "META-INF" folder
> 3. drag the file "mods.toml" to desktop
> 4. open "mods.toml" from the desktop with notepad
> 5. delete
>    [[dependencies.oculus]]
>    modId = "embeddium"
>    versionRange = "[0.2.14,)"
>    ordering = "NONE"
>    side = "CLIENT"
> 6. Save "mods.toml"
> 7. drag the new "mods.toml" into the open "oculus-mc1.20.1-1.6.13a.jar/META-INF" in 7-zip
> 8. say yes when it asks to copy files to archive

Or just add `mandatory = false` in it: 
```toml
[[dependencies.oculus]]
modId = "embeddium"
mandatory = false
versionRange = "[0.2.14,)"
ordering = "NONE"
side = "CLIENT"
```
Get it from [this commit](https://github.com/Asek3/Oculus/commit/b613f2ecbe7b85dff91c8e9d0198181da1679b36#diff-3bc2a2f6cb6e625914eaf245e536e39108fbc2a24acd076bd6bbc2a60f56c214).
