### ISSUE TITLE
Flywheel and oculus are slashing at this point 

### ISSUE THREAD

**Issue by LittleLightz** [Asek3/Oculus#528]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.13.jar

### Sodium Version

not using it, using forge

### Operating System

win 11

### What is your GPU?

Nvidia RTX 4070

### Java Version

java 16?

### Reproduction Steps

clicked play button 
crashed half way through loading
[latest.log](https://github.com/Asek3/Oculus/files/13830516/latest.log)

### Additional context

Flywheel and oculus are clashing at this point 
using forge

**Comment by LittleLightz** [comment]
found out that I had create and flywheel clashing with different versions of flywheel

**Comment by Diversion98** [comment]
hey, im having this issue as well for several weeks now.
How did u get it to clash? flywheel is included with create now?

**Comment by LittleLightz** [comment]
> hey, im having this issue as well for several weeks now. How did u get it to clash? flywheel is included with create now?

Create has flywheel alleady, and any other version is an old version if you install flywheel by itself, create already has it installed,  so no need to instal create and flywheel,  just create.  think the clash was create clashing with the older version of flywheel.

**Comment by Diversion98** [comment]
apparently the mod "Iris & Oculus Flywheel Compat" is not up to date with the latest oculus so thats why my modpack is crashing
