### ISSUE TITLE
Blocks are not visible

### ISSUE THREAD

**Issue by Dr-WeiAL** [Asek3/Oculus#53]
### What happened?

Rendering problem

### Screenshots

![2022-04-18_17 37 54](https://user-images.githubusercontent.com/47446553/163790217-e91cc31e-e0d6-426d-afcf-91d94daa42a8.png)
![2022-04-18_17 38 08](https://user-images.githubusercontent.com/47446553/163790225-f2bc687d-5b62-4bf5-96a5-68e10115dcfb.png)

### Relevant log output

[latest.log](https://github.com/Asek3/Oculus/files/8504916/latest.log)

### Minecraft Version

Minecraft 1.18.2

### Iris Version

oculus-mc1.18.2-1.2.2b

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 10

### What is your GPU?

RTX 2060

### Java Version

Java 17

### Additional context

I had this problem after I added a mixin.features.chunk_rendering=false in rubidium-mixins.properties, if I don't add it, the CTM will be invalid

**Comment by TheRealDadbeard** [comment]
I have the same issue

**Comment by Asek3** [comment]
Can you try without Oculus, only Rubidium?

**Comment by Dr-WeiAL** [comment]
> Can you try without Oculus, only Rubidium?

This problem does not occur with only Rubidium

**Comment by ascendedKappa** [comment]
I had the same issue but after turning off "Use Block Face Culling" under the Perfomance Tab in Rubidium, it was fixed. At least for about 6 hours it didn't occur again.

**Comment by Dr-WeiAL** [comment]
> I had the same issue but after turning off "Use Block Face Culling" under the Perfomance Tab in Rubidium, it was fixed. At least for about 6 hours it didn't occur again.

I tried it, and turning it off didn't work

**Comment by ascendedKappa** [comment]
I also had to reconnect but I assume that won't work ether, since in my case only one or two chunks were affected and not the whole world.

**Comment by Dr-WeiAL** [comment]
The rendering issue seems to have been resolved, so this can be turned off
