### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Aabaddon** [Asek3/Oculus#542]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.13.jar

### Rubidium / Embeddium Version

embeddium-0.3.0+mc1.20.1

### Operating System

windows 11

### What is your GPU?

nvidia GeForce RTX 3060

### Java Version

JDK-21

### Reproduction Steps

1. install oculus with embeddium
2. open the game
3. Game Crashes

### Additional context

incompat with lastest embeddium

**Comment by dima-dencep** [comment]
https://github.com/Asek3/Oculus/actions/runs/7759443612
