### ISSUE TITLE
Support For Distant Horizons through Rubidium and Oculus

### ISSUE THREAD

**Issue by Da1NOnlyCheezIt** [Asek3/Oculus#544]
**Problem Relation**
When enabling Distant Horizons, far chunks do not render, i.e. chunks 16+ on 16 chunk render distance do not render.

**Describe the solution you'd like**
Compatibility with Distant Horizons would be nice, as Oculus is forked alongside rubidium for forge.

**Describe alternatives you've considered**
Optifine breaks some forge modpacks, and rubidium + oculus being an option would be the only way for this to work appropriately.

**Additional context**
![image](https://github.com/Asek3/Oculus/assets/88004627/87911d11-69f1-4c7d-9e25-315ede917ae6)
this rendering
![image](https://github.com/Asek3/Oculus/assets/88004627/4f7d91ec-de11-4e7d-96b8-ce10ee82c119)
for this image

**Comment by VOLKOUL** [comment]
Bruh, the Distant Horizons Mod is already supported. Try using Embeddium, a better alternative to Rubidium. (it focuses more on compatibility, so my guess is that DH isn't supported by Rubidium)

**Comment by Da1NOnlyCheezIt** [comment]
> Bruh, the Distant Horizons Mod is already supported. Try using Embeddium, a better alternative to Rubidium. (it focuses more on compatibility, so my guess is that DH isn't supported by Rubidium)

so to summarize:
"bruh" - condescending tone, therefore my feature request is null because DH isn't supported by rubidium. Which, was the point of a feature request.
My bad for asking the creator if there is either a solution within their own codebase, or other; instead, why not try "hey, they probably won't work on this feature, another creator's rubidium fork, Embeddium, may have solution to your problem."
A lil kindness goes a long way friend.
