### ISSUE TITLE
[1.20.1][Oculus 1.6.15] Crash after selecting and applying a shader.

### ISSUE THREAD

**Issue by VOLKOUL** [Asek3/Oculus#545]
### Minecraft Version

1.20.1

### Oculus Version

Oculus mc1.20.1-1.6.15

### Rubidium / Embeddium Version

[1.20.1] Embeddium 0.3.1

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060 Laptop GPU

### Java Version

Uhh, default? Didn't touch anything.

### Reproduction Steps

1. Launch game
2. Enter World
3. Select shader (crash occurred when applying SEUS Renewed)

(The game is heavily modded)

### Crash Report file and latest.log

```shell
Crash Report: https://mclo.gs/xPJDmDZ
Latest Log: https://mclo.gs/sxb80jN
```

### Additional context

Using NeoForge 47.1.97 1.20.1

**Comment by dima-dencep** [comment]
Remove physicsmod
