### ISSUE TITLE
1.18.2: Picked shader does not load until refreshed

### ISSUE THREAD

**Issue by Vazkii** [Asek3/Oculus#55]
### What happened?

Loading a game with a shader set up results in no shader being enabled until you go to the Shader settings and press Apply.

The oculus.properties config is as such:
```
#This file stores configuration options for Oculus, such as the currently active shaderpack
#Mon Apr 18 21:10:33 WEST 2022
maxShadowRenderDistance=32
shaderPack=sed.zip
enableShaders=true
```

`sed.zip` is correctly placed, as nothing in the file other than the timestamp changes when the config is refreshed.

### Relevant log output

```shell
https://gist.github.com/Vazkii/24e2ec4afff5afe4777f572ba320291e
```

### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.2b.jar

### Sodium Version

rubidium-0.5.2a.jar

### Operating System

Windows 10

### What is your GPU?

RTX 2070

### Java Version

Java 17

### Additional context

Shader in question is Sildur's Enhanced Default

**Comment by Asek3** [comment]
Related to late config application. Fixed in next release
