### ISSUE TITLE
Minecraft doesn't load with Oculus 1.6.15 and Embedium 0.3.2

### ISSUE THREAD

**Issue by 0Navis0** [Asek3/Oculus#555]
### What happened?

Embedium 0.3.2 complains that Oculus 1.6.15 isn't installed when it is.
https://github.com/embeddedt/embeddium/issues/205

### Minecraft Version

Minecraft 1.20.1

### Oculus Version

Occulus 1.6.15

### Rubidium / Embeddium Version

Embeddium 0.3.2

### Operating System

Windows 11

### What is your GPU?

Nvdia GeForce GTX 1080

### Java Version

Java 17

**Comment by jasnowizard** [comment]
Yes I'm getting the same issue with 0.3.2 and 0.3.3, only 0.3.1 works with Oculus 1.6.15
