### ISSUE TITLE
1.18.2 - Create blocks (flywheel for example) & ponder system Incompatible

### ISSUE THREAD

**Issue by zachsai** [Asek3/Oculus#56]
### What happened?

![image](https://user-images.githubusercontent.com/63996164/163900377-cae5038a-150d-4bdd-a73e-9be293af9bee.png)
![image](https://user-images.githubusercontent.com/63996164/163900397-1ed87dea-6393-4374-97cf-f1a71931a1de.png)
You can see in the images what happens, oculus makes the rendering wonky

### Minecraft Version

1.18.2

### Iris Version

1.2.2b

### Sodium Version

0.5.2a

### Operating System

Windows 11

### What is your GPU?

1070

### Java Version

Java 17

**Comment by Asek3** [comment]
Resolved in 1.2.4
