### ISSUE TITLE
Distant Horizons LOD Shaders Not Blending/Applying Correctly

### ISSUE THREAD

**Issue by SimonMischenkoHawk** [Asek3/Oculus#564]
### What happened?

I manually compiled the 1.20.1 Teqed branch of Oculus earlier and noted the behavior with shaders was unusual. I later was told the DH support had been added to the latest 1.6.15a and found it was identical to the 1.20.1 Teqed branch with respect to shaders. Some shaders appear to modify brightness of DH's LODs, but not apply effects in nearly the way I expect. Bliss shaders seem to work on some Iris builds as shown here:

![image](https://github.com/Asek3/Oculus/assets/144265351/6908aa36-67cf-4c1e-81b6-fec538f6f4c9)

While the same shader on Oculus 1.6.15a looks like this:

![javaw_toJFMczfY1](https://github.com/Asek3/Oculus/assets/144265351/7c15c210-d2c1-4bbf-892f-b645c779015c)

Shaders that do render DH LODs have a clear seam where none is expected, as shown with this Complimentary shader that has been specifically modified to work with DH:

![javaw_Kb0Z5JOqJv](https://github.com/Asek3/Oculus/assets/144265351/4effcb84-50ec-4411-9cb8-74b6ba23e676)

I realize DH support is still new so I'm definitely not quick to judge re: intercompatibility, but I didn't see an issue created yet for these major visual bugs and wanted to make sure it's reported somewhere if this is not already known.

### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.15a.jar

### Rubidium / Embeddium Version

embeddium-0.3.4+mc1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

NVidia RTX 2070

### Java Version

Java 17

**Comment by hanbings** [comment]
Hello, what version of DH are you using? (A link would be nice) I'm also trying to get DH to work with oculus.

**Comment by SimonMischenkoHawk** [comment]
My recent testing (at the time of writing the above post) was using https://www.curseforge.com/minecraft/mc-mods/distant-horizons/download/4924664 from https://www.curseforge.com/minecraft/mc-mods/distant-horizons/files/4924664, though to get Oculus to compile from the Teqed branch I needed to add "DistantHorizons-2.0.0-a-1.20.1" to the libs folder after deleting "fabric.mod.json" to get it to build (because it's a hybrid jar).

I've been testing against "DistantHorizons-forge-2.0.2-a-dev-1.20.1" which is currently only available from their official discord ( https://discord.com/invite/xAB8G4cENx under #links ) but I suspect this and the previous attempts are a temporary dead end until they add official explicit support for Oculus.

This promising branch which has had Oculus support explicitly added/enabled is my current best bet: https://github.com/PlxelBuilder/Distant-Horizons-2.0.1a-Oculus-shadow-fix/releases/download/Release/DistantHorizons-2.0.1-a-1.20.1-Oculus-shadow-fix.jar ( from https://github.com/PlxelBuilder/Distant-Horizons-2.0.1a-Oculus-shadow-fix/releases/tag/Release ).

It comes from a longer thread of conversation happening here: https://gist.github.com/Steveplays28/52db568f297ded527da56dbe6deeec0e#gistcomment-4945509

**Comment by henrikx** [comment]
For everyone on Minecraft 1.16.5, you can use my fork of Oculus here with DH support backported from Iris 1.6.11
https://github.com/henrikx/Oculus/releases/tag/mc1.16.5-1.4.7-dh
