### ISSUE TITLE
@Inject annotation on iris$writeIrisConfig could not find any targets matching 'writeToDisk'

### ISSUE THREAD

**Issue by xukura** [Asek3/Oculus#568]
### Minecraft Version

1.20.1

### Oculus Version

oculus 1.6.15a

### Rubidium / Embeddium Version

rubidium 0.7.1a

### Operating System

Windows 11

### What is your GPU?

GTX 780 Ti

### Java Version

17

### Reproduction Steps

launch > crashes during loading

### Crash Report file and latest.log

```shell
latest.log - https://mclo.gs/t0JI6sY
debug.log - https://mclo.gs/9Bt4zsC
```

### Additional context

full modlist; i'm not sure why sodium shows up as a separate thing but it is not present:
- advancementplaques 1.5.1
- appleskin 2.5.1+mc1.20.1
- bookshelf 20.1.9
- darkpaintings 17.0.4
- forge 47.2.0
- geckolib 4.4.2
- iceberg 1.1.21
- jade 11.7.1
- jei 15.3.0.4
- minecraft 1.20.1
- mousetweaks 2.25
- notenoughanimations 1.7.1
- oculus 1.6.15a
- puzzlesaccessapi 8.0.7
- puzzleslib 8.1.17
- rubidium 0.7.1a
- skinlayers3d 1.6.2
- sodium 0.5.3
- visualworkbench 8.0.0
- xaerominimap 23.9.7
- xaeroworldmap 1.37.8

**Comment by dima-dencep** [comment]
use embeddium
