### ISSUE TITLE
[1.16.5] Log spam with Modern UI

### ISSUE THREAD

**Issue by ChromaPIE** [Asek3/Oculus#57]
### What happened?

There is no crash or any fatal problems, the log keeps spamming

`[Render thread/WARN] [Oculus/]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: modern_text`

When running Oculus with the mod Modern UI (https://www.curseforge.com/minecraft/mc-mods/modern-ui)

### Minecraft Version

1.16.5

### Iris Version

oculus-1.16.5-1.2.2

### Sodium Version

rubidium-0.2.5

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1650

### Java Version

Java 11

**Comment by Asek3** [comment]
Core shaders is unsupported by Iris/Oculus
