### ISSUE TITLE
There is a crashing issue

### ISSUE THREAD

**Issue by Protonm0KEN** [Asek3/Oculus#572]
### Minecraft Version

1.20.1

### Oculus Version

oculus mc1.20.1-1.6.15a.jar

### Rubidium / Embeddium Version

rubidium-mc1.20.1-0.7.1a.jar

### Operating System

Windows 11

### What is your GPU?

RTX 3070

### Java Version

Java 18

### Reproduction Steps

Pleease make compatible fo rmod support and help me with problem. I cant understand why its crashing cause code of running out is 1
I dont know why came is crashing optifine is disabled

### Additional context

Mods that is use
![image](https://github.com/Asek3/Oculus/assets/109662775/ec573245-c31a-47a6-a175-fc105435ed60)
![image](https://github.com/Asek3/Oculus/assets/109662775/dd682cb3-5cda-4f20-893c-3daf48f866f6)
![image](https://github.com/Asek3/Oculus/assets/109662775/e75c26dc-d1c6-48f9-9647-42f7200e883e)

**Comment by dima-dencep** [comment]
Use embeddium
