### ISSUE TITLE
1.18.2 Dev Branch Contains Potential Malware

### ISSUE THREAD

**Issue by Syclusion** [Asek3/Oculus#577]
### What happened?

This isn't a bug, but in trying to port some DH compat to the 1.18.2 version the branch gets marked as a virus

https://www.virustotal.com/gui/file/f3e92ad00ee7ae006dd2cb65f73cf4eb4a757fdd2a33c5f1135bae1270663ada?nocache=1

Specifically the apacheant version used in the libs folder.

### Minecraft Version

1.18.2

### Oculus Version

DEV

### Operating System

WIN11

### What is your GPU?

...

### Java Version

....

**Comment by GinkREAL** [comment]
let me know if you get it working

also they closed my similar report in https://github.com/Asek3/Oculus/issues/535, probably an abandoned branch rn
