### ISSUE TITLE
Banner pattern causes huge bottleneck while shaders enabled

### ISSUE THREAD

**Issue by liangmoe** [Asek3/Oculus#579]
### What happened?

FPS heavily drop down while rendering a good amount of banners

### Screenshots

original iris:
![2024-03-15_22 40 05](https://github.com/Asek3/Oculus/assets/135343248/7310a208-d155-4f20-af44-10b7177ac201)

oculus:
![2024-03-15_22 59 43](https://github.com/Asek3/Oculus/assets/135343248/fb6154e7-ef9c-4c17-9814-3c6dc247ca17)

banner pattern:
![image](https://github.com/Asek3/Oculus/assets/135343248/bb083c98-61b4-4ba4-82cd-669db3444578)

### Relevant log output

```shell
https://mclo.gs/Kpeg31r
```

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.15a.jar

### Rubidium / Embeddium Version

embeddium-0.3.9+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

RTX 3060ti

### Java Version

Java 17

### Additional context

Number of banners: 13x11=143

**Comment by dima-dencep** [comment]
The comparison is incorrect because oculus 1.6.15a is iris 1.6.15, not 1.6.17
