### ISSUE TITLE
GPU Bottleneck and general performance issues on 1.18.2/1.20.1 MC

### ISSUE THREAD

**Issue by Barerock** [Asek3/Oculus#584]
### What happened?

Attempting to get shaders like Nostalgia and Astralex to work on my other PC, which has a GTX 1060, I noticed that the GPU is heavily throttled to lower than 60% functionality. This persists through tests with no other mods than Embeddium and Oculus. For some older but less intense shaders like Sildur's Default Enhanced and Vanilla Plus by RRe36, percentage is capped as low as 20%. This problem limits the performant usage of PBR packs on higher end systems, namely a 3070, to name one annoying consequence.

This does _not_ occur using only Sodium and Iris. Using the Fabric counterparts completely resolves the issue.

Performance in general is enhanced without shaders, of course, but using shaders seems to introduce this throttling issue.

And as a defensive measure, before anyone says, "well just use Fabric." Many mods are not on Fabric, especially regarding the special scenario pack I have built where over 50 have non counterpart.

Of course, this may not be a high priority fix considering new versions and the Iris/Sodium teams' plans to port directly to Forge for their next major update.

### Minecraft Version

1.18.2 and 1.20.1

### Oculus Version

oculus-mc1.18.2-1.6.4/oculus-mc1.20.1-1.6.15a

### Rubidium / Embeddium Version

embeddium-0.3.10+mc1.18.2/embeddium-0.3.9+mc1.20.1

### Operating System

Windows 10/Windows 11

### What is your GPU?

NVIDIA GTX 1060/NVIDIA RTX 3070

### Java Version

Version 8 update 401 build 1.8.0_401-b10

### Additional context

Thanks for the hard work. I know exactly how hard it is dealing with end users <3

**Comment by dima-dencep** [comment]
Let me guess, have you compared oculus 1.6.15 and iris 1.6.17?

**Comment by Barerock** [comment]
Oculus 1.6.15 doesn't _exist_ on 1.18.2, the main topic of this report. Also, I tested this with 1.20.1 versions, meaning 1.6.15a and Iris 1.6.17.

I'll do it again tho just to compare further.

**Comment by Barerock** [comment]
Method is being done on a modern rig, so results will vary from the 1060 tests.

**Comment by Barerock** [comment]
Bottleneck seems to be better, but not gone.
1.20.1
Oculus 1.6.15a
Embeddium 0.3.9
Forge 47.2.20

My GPU seems to throttle at 70-80% while sitting around 120 fps with shaders and pbr active; without either active it settles around 232fps at 38% instead of maxing out at 250.

Render distance is 32 while all other settings are default.

On the same map on Iris, in the exact position as on Forge:
1.20.1
Iris 1.6.17
Sodium 0.5.8
Fabric 0.92.0

FPS sits between 238 and 240 with 43% GPU usage, fairly constant. So it also has a weird throttle, but not as much.
With shaders: I sit between 130 and 135 FPS at 90 -100% GPU usage, fairly constant. Stable 65-66C as well.

I think this barebones comparison proves that there's something going on with Oculus and its ability to use the GPU. My CPU is chillin' this whole time, even when loading land.

**Comment by Barerock** [comment]
On 1.18.2 this is the difference between getting 100FPS with Iris running Nostalgia shaders on a 1060 and getting 20 FPS with the exact same settings and map while using Oculus.

**Comment by dima-dencep** [comment]
Same as #579 
1.18.2 doesn't interest us

**Comment by Barerock** [comment]
> Same as #579 1.18.2 doesn't interest us

Great to know, sucks to suck.

**Comment by dima-dencep** [comment]
> oculus 1.6.15a is iris 1.6.15, not 1.6.17

**Comment by dima-dencep** [comment]
Also, don't use forge above 47.1.3 in your tests, good luck ❤️
