### ISSUE TITLE
will oculus be fitted with distant horizon

### ISSUE THREAD

**Issue by DUSTcang** [Asek3/Oculus#590]
will oculus be fitted with distant horizon

**Comment by DUSTcang** [comment]
The distant horizon has been popular recently, Iris as Oculus on fabric has make itself be supported for Distant Horizon.Distant Horizon is a mod that make Minecraft entirely new.But it is still only available on fabric.As a creator of Oculus to save us from the prison of optifine.l am sure that you can bring us fans a better Minecraft.And then l think Oculus will be more welcomed than now as you deserve it

**Comment by pizzav-xyz** [comment]
if so pls 1.20.1

**Comment by dima-dencep** [comment]
Iris still doesn't support dh properly

**Comment by pizzav-xyz** [comment]
> Iris still doesn't support dh properly

what about when it does?
