### ISSUE TITLE
Hard Crash with Shaders on and Using Shimmer With Oculus

### ISSUE THREAD

**Issue by Devilswarchild** [Asek3/Oculus#593]
### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.15a.jar

### Rubidium / Embeddium Version

embeddium-0.3.11+mc1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

Radeon 6900XT

### Java Version

Java 17

### Reproduction Steps

1. Enable Oculus, Embeddium and Shimmer
2. Enable Shaderpack
3. Launch Game/Load World Save
4. Crash

### Crash Report file and latest.log

```shell
MC version 1.20.1
Oculus Version: oculus-mc1.20.1-1.6.15a.jar
Embeddium Version: embeddium-0.3.11+mc1.20.1.jar
Shimmer Version: Shimmer-forge-1.20.1-0.2.4.jar

[Crash Report, debug.log, latest.log](https://gist.github.com/Devilswarchild/a7d98cf959ec59e08df13cfe50d5db52)
```

**Comment by dima-dencep** [comment]
shimmer issue
