### ISSUE TITLE
[1.18.1] Breaks Tinkers' Construct Slimeskull Helmets' item rendering

### ISSUE THREAD

**Issue by aethaerya** [Asek3/Oculus#6]
When Oculus is installed, the Slimeskull helmets in Tinkers' Construct appear as errored textures. They're still wearable, though, and wearing them doesn't seem to cause any crashes.

![image](https://user-images.githubusercontent.com/28931355/158064179-4e9677e0-97b0-4994-84ec-a9ecd09f848a.png)
![image](https://user-images.githubusercontent.com/28931355/158064188-352c9fbf-b78d-489f-8a82-1b3a957ceaa3.png)

Reproduce with: 
Tinkers' Construct 3.4.1.46
Mantle 1.8.31
Rubidium 0.5.0
Oculus 1.2.1
Forge 39.1.2

**Comment by aethaerya** [comment]
Since Oculus & Rubidium have been updated to 1.18.2 while Tinkers' hasn't yet, I'll update this issue when Tinkers' releases a 1.18.2 update.

**Comment by aethaerya** [comment]
Hey, Tinkers recently updated to 1.18.2 and I can confirm that the items are rendering correctly now.
Tested twice with Oculus enabled & disabled.
![image](https://user-images.githubusercontent.com/28931355/167448734-e2be910f-d75c-43f8-af2d-04d3460855b3.png)

**Comment by VirtualGaming1** [comment]
> Hey, Tinkers recently updated to 1.18.2 and I can confirm that the items are rendering correctly now. Tested twice with Oculus enabled & disabled. ![image](https://user-images.githubusercontent.com/28931355/167448734-e2be910f-d75c-43f8-af2d-04d3460855b3.png)

What version of MC you are using?

**Comment by aethaerya** [comment]
I opened this issue when Rb & Oculus were still on 1.18.1. They received updates to 1.18.2 first while TiC remained on 1.18.1 for a bit longer and now that TiC has updated to 1.18.2, this issue no longer exists between the three mods. I'll be closing this issue now as I'd forgotten to do it with my last comment.
