### ISSUE TITLE
Oculus causing crashes.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Oculus#60]
Crashes when loading minecraft.
Oculus: 1.16.5-0.2.5
logs:
[latest.log](https://github.com/Asek3/Rubidium/files/8543159/latest.log)

Crash Report:
[crash-2022-04-22_10.59.47-client.txt](https://github.com/Asek3/Rubidium/files/8543162/crash-2022-04-22_10.59.47-client.txt)

**Comment by Asek3** [comment]
Related to Oculus

**Comment by Asek3** [comment]
Fixed since 1.4
