### ISSUE TITLE
Oculus Beta 1.6.15aDH for Forge 1.20.1 issue with deleting worlds

### ISSUE THREAD

**Issue by 3ncanis** [Asek3/Oculus#603]
### What happened?

Using the Distant Horizons Oculus beta, I am unable to delete worlds I've created in the same session. If I try to manually delete these worlds in the .minecraft/saves/ folder I am also unable to delete them because it says they're open in a program. If I close Minecraft and relaunch I am able to delete these worlds.

### Minecraft Version

1.20.1

### Oculus Version

1.6.15aDH

### Rubidium / Embeddium Version

Embeddium 0.3.14

### Operating System

Windows 11

### What is your GPU?

RTX 4090

### Java Version

17

**Comment by Leonniclass** [comment]
Experiencing the same
