### ISSUE TITLE
[1.7.0][1.20.1][NeoForge] Crash when applying shaders (Chocapic13) (might be Connector related)

### ISSUE THREAD

**Issue by VOLKOUL** [Asek3/Oculus#610]
### Minecraft Version

1.20.1

### Oculus Version

Oculus mc1.20.1-1.7.0

### Rubidium / Embeddium Version

[1.20.1] Embeddium 0.3.14

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060 Laptop GPU

### Java Version

-

### Reproduction Steps

Apply shaders

### Crash Report file and latest.log

```shell
Crash: https://mclo.gs/1ANtPzo
Latest log:  https://mclo.gs/ZmOpvTE

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/coderbot/iris/compat/sodium/impl/vertex_format/IrisChunkMeshAttributes
Exit Code: -1

(Nvidium maybe???)
```

### Additional context

Crashed when applied Chocapic13 shaders in the nether. (using BetterNether on Connector, along with other ~300 mods)

Had to use an external site since GitHub doesn't allow for reports exceeding 65536 characters

**Comment by dima-dencep** [comment]
Remove littletiles

**Comment by dima-dencep** [comment]
(This mod has not yet been updated to support oculus 1.7)
