### ISSUE TITLE
[1.20.1] Oculus 1.7.0 bug with the Armourer's Workshop mod

### ISSUE THREAD

**Issue by CiciHoneyBee** [Asek3/Oculus#611]
### What happened?

Hello! I had updated Oculus to 1.7.0 in my modpack and noticed a bug with the Armourer's Workshop mod while shaders were enabled. When wearing an AW skin while in third person, the skin expanded and blocked the entire screen. I was using both unbound and reimagined complementary shaders.

### Screenshots

Player wearing AW skin in Oculus 1.6.15a:

![Screenshot (218)](https://github.com/Asek3/Oculus/assets/166247139/467a8482-679d-4d02-8a9e-b765ed44759d)

Player wearing AW skin in Oculus 1.7.0:

![Screenshot (219)](https://github.com/Asek3/Oculus/assets/166247139/d2bb4c23-fdc1-4ff8-b948-9ca8184aca3c)

### Minecraft Version

Minecraft 1.20.1

### Oculus Version

Oculus 1.7.0

### Rubidium / Embeddium Version

Embeddium 0.3.14

### Operating System

Windows 11 Pro

### What is your GPU?

NVIDIA GEFORCE RTX 3060

### Java Version

Java 17

**Comment by dima-dencep** [comment]
This mod has not been updated to support iris (oculus) 1.7, you can let them know about it

**Comment by CiciHoneyBee** [comment]
I will, thank you very much
