### ISSUE TITLE
Port of Oculus to 1.12.2 to work alongside Vintagium (Sodium 1.12 port)?

### ISSUE THREAD

**Issue by stealthusk** [Asek3/Oculus#616]
I was just wondering if it would be possible somehow to do this? It would complement the Sodium port very well. I love shaders and would love to use both of them together! Hope you take this feature suggestion into consideration. Thank you.

https://github.com/Asek3/sodium-1.12

**Comment by dima-dencep** [comment]
https://github.com/Asek3/Oculus/tree/1.12.2

**Comment by ArikGolub** [comment]
How can I get jar files for vintagium and oculus for 1.12.2?

**Comment by ArikGolub** [comment]
> How can I get jar files for vintagium and oculus for 1.12.2?

Do I have to compile them myself in Intellij IDEA?
