### ISSUE TITLE
Distant Horizon crashes with oculus present 

### ISSUE THREAD

**Issue by Crankonator** [Asek3/Oculus#618]
### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.17+mc1.20.1-all

### Operating System

windows 11

### What is your GPU?

Nvidia RTX 3060 12gb

### Java Version

java 17 i think

### Reproduction Steps

1. click play
2. Let game load
3. game crashes just before reaching the main menu
[crash-2024-05-03_16.16.01-client.txt](https://github.com/Asek3/Oculus/files/15205028/crash-2024-05-03_16.16.01-client.txt)
[latest (7).log](https://github.com/Asek3/Oculus/files/15205029/latest.7.log)

**Comment by Crankonator** [comment]
thanks for the context, much appreciated

**Comment by Crankonator** [comment]
marking issues as invalid doesn't make them go away you know

**Comment by dima-dencep** [comment]
I don't care, you could have read the discord before creating this issue

**Comment by Crankonator** [comment]
You are quite an unbecoming individual, and anyone who willingly chose to work with you should be ashamed to have let you handle public interactions as you clearly can't handle it like a normal person.  
Since you seem to have forgotten I will take on the task of informing you of what is said on the Oculus GitHub Issue creation page, so listen closely now.

"Join the Discord for support using Oculus!
It's easier for our support staff to help you through our Discord server, so please if you are looking for support, go there. Of course, if you have found an actual bug/crash, please open an issue."

Let's break this down!

"Join the Discord for support using Oculus!
It's easier for our support staff to help you through our Discord server, so please if you are looking for support, go there."

In this section you inform us that I should go to your Discord server IF I am looking for support.
I am not looking for support, I'm here to inform you guys of a crash caused by YOUR mod, I don't need help finding out WHY it crashed, I already know why, so that statement doesn't apply to me.

This is where it gets juicy!!!!!

"Of course, if you have found an actual bug/crash, please open an issue."

WHAT?! THAT'S CRAZY!!!! 
So you're telling me that if I have found an actual crash, I should open an issue?!

So now that you know what the Oculus GitHub Issue creation page says, I hope you can get your little act together and stop bringing down Asek3's reputation with your bad manners and childish behaviour.

Here's a little recap of the past few closed issues so we can see your actual impact!
Closed with context or proper response: 8
Closed with poor/bad reason or no reason: 28
Closed by another person: 8
"Use Embeddium": 4

If Asek3 sees this, i hope you realise your buddy's bad attitude towards the public brings down your reputation as well as his own(although his reputation has already hit rock bottom)

**Comment by dima-dencep** [comment]
Thank you for your time, but thankfully it won't change anything and I will continue to do what I think is right.

I haven't gotten paid since I started working on oculus, I will never look at a million identical issues and in each one describe what is wrong, if your issue is closed for no reason you can consider it your skill issue 😘

Asek definitely has nothing to do with this, and there's no need to bring him into this, he knows exactly what I'm doing.
