### ISSUE TITLE
Crashing on the latest version of Embeddium

### ISSUE THREAD

**Issue by Zanklev** [Asek3/Oculus#620]
### Minecraft Version

Minecraft 1.20.1

### Oculus Version

Oculus mc1.20.1-1.7.0

### Rubidium / Embeddium Version

Embeddium 0.3.18

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 3080

### Java Version

Adoptium 22

### Reproduction Steps

Install both Embeddium and Oculus
Launch Game
Create/Load World
Crash

[crash-2024-05-06_21.26.03-client.txt](https://github.com/Asek3/Oculus/files/15229435/crash-2024-05-06_21.26.03-client.txt)
[latest.log](https://github.com/Asek3/Oculus/files/15229437/latest.log)

**Comment by dima-dencep** [comment]
betterclouds issue
