### ISSUE TITLE
render crash while using Physics Mod and oculus(detailed issue)

### ISSUE THREAD

**Issue by nekohacker591** [Asek3/Oculus#625]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.14+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

RTX A4500

### Java Version

Java 16

### Reproduction Steps

load into overworld psyics mod matrix object is loaded and then the sceeen gos blank via error
Suspected Mods: 
	Physics Mod (physicsmod), Version: 3.0.12
		at TRANSFORMER/physicsmod@3.0.12/net.diebuddies.compat.Iris.setNormalMatrix(Iris.java:101)

	Oculus (oculus), Version: 1.7.0
		Issue tracker URL: https://github.com/Asek3/Oculus/issues
		Mixin class: net.irisshaders.iris.mixin.LevelRendererAccessor
		Target: net.minecraft.client.renderer.LevelRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.invokeRenderChunkLayer(LevelRenderer.java)

	Embeddium (embeddium), Version: 0.3.14+mc1.20.1
		Mixin class: me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin
		Target: net.minecraft.client.renderer.LevelRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:33205)

here is the file logs
[latest.log](https://github.com/Asek3/Oculus/files/15280796/latest.log)
[crash-2024-05-10_19.18.08-client.txt](https://github.com/Asek3/Oculus/files/15280798/crash-2024-05-10_19.18.08-client.txt)

### Additional context

is the pro version of the mod.
crashs in the over world but not the nether
overlord loads but after rending a instince from the Physics Mod the game crashs

**Comment by dima-dencep** [comment]
I don't know what happened here, it's not an oculus issue anyway
