### ISSUE TITLE
Crashing when trying to render a skeleton skull with shaders (Server)

### ISSUE THREAD

**Issue by SyntaxError73** [Asek3/Oculus#628]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

embeddium-0.3.18+mc1.20.1-all

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce 2060 Super

### Java Version

Java 17.0.5

### Reproduction Steps

1. Have a shader and oculus active
2. be near a skeleton skull
3. Game crashes

### Crash Report file and latest.log

[crash-2024-05-08_12.54.47-client.txt](https://github.com/Asek3/Oculus/files/15284238/crash-2024-05-08_12.54.47-client.txt)

### Additional context

This happened to my friend in the same server as well with the same setup.

**Comment by dima-dencep** [comment]
CustomPlayerModels issue
