### ISSUE TITLE
Crash on World Load with Distant Horizons

### ISSUE THREAD

**Issue by Nygosaki** [Asek3/Oculus#638]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.19+mc1.20.1-all.jar

### Operating System

macOS Sonoma 14.5

### What is your GPU?

M2 Pro

### Java Version

Java 17

### Reproduction Steps

1. Install Distant Horizons (DistantHorizons-forge-2.0.4-a-dev-1.20.1.jar)
2. Install Oculus (oculus-mc1.20.1-1.7.0.jar)
3. Install Embeddium (embeddium-0.3.19+mc1.20.1-all.jar)
4. Create a world

[latest.log](https://github.com/Asek3/Oculus/files/15456204/latest.log)
[hs_err_pid54170.log](https://github.com/Asek3/Oculus/files/15456203/hs_err_pid54170.log)

### Additional context

Oculus 1.7 states that it has "Distant Horizon 2.0.4+ support".
The issues described happen even when using the nightly/dev build of Distant Horizons 2.0.4 (from the discord).

**Comment by dima-dencep** [comment]
I think the problem is with your hardware, perhaps the problem is with DH itself.
