### ISSUE TITLE
Oculus failes to compile with an unknown block in layer.translucent

### ISSUE THREAD

**Issue by SpacEagle17** [Asek3/Oculus#639]
### What happened?

The following breaks with Oculus but noth with iris
```
layer.translucent = glass glass_pane beacon \
\
betternether:cincinnasite_frame
```
The above is an entry for block.properties
Normal block entries such as `block.1 = glass moddedGlass:purple_glass` works fine.
Oculus seems to fail to compile if an unknown block is used for layer.translucent.
By unknown block I mean a block that is from a mod one is not using. For example a vanilla setup with only oculus

### Screenshots

![Screenshot_2024-05-30-19-03-42-556_com discord](https://github.com/Asek3/Oculus/assets/46494907/0d7f22fc-1ff9-4f3f-bf8f-ef22bc85b8fe)

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Operating System

Windows 11

### What is your GPU?

GTX 1660

### Java Version

Java 17

### Additional context

This is reproducible by many people and causes issues with the pack I'm developing

**Comment by dima-dencep** [comment]
Fixed
