### ISSUE TITLE
Game cannot start

### ISSUE THREAD

**Issue by IsMaldonado-dev** [Asek3/Oculus#643]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

rubidium-mc1.20.1-0.7.1a

### Operating System

Windows 10

### What is your GPU?

Radeon Vega 7

### Java Version

Java 17.0.8

### Reproduction Steps

1. Open the Launcher
2. Select Forge 1.20.1- 47.3.1 version
3. Game Crashes

### Crash Report file and latest.log
[crash-2024-06-12_10.25.54-client.txt](https://github.com/user-attachments/files/15806779/crash-2024-06-12_10.25.54-client.txt)

### Additional context

The game starts with rubidium, but when I add oculus to the "mods" folder, the game crashes on startup.
![Sin título](https://github.com/Asek3/Oculus/assets/172514126/6f40fcd4-bfb0-480a-9021-b60c0ee7e4e6)

**Comment by dima-dencep** [comment]
Update oculus and use embeddium

**Comment by IsMaldonado-dev** [comment]
> Update oculus and use embeddium

there isn't a newer version of oculus, the oculus-mc1.20.1-1.7.0 is the lastest. But i will try with embeddium

**Comment by IsMaldonado-dev** [comment]
> Update oculus and use embeddium

with Embeddium works perfectly!
