### ISSUE TITLE
Fix support for Mekanism

### ISSUE THREAD

**Issue by I4LYT** [Asek3/Oculus#646]
### What happened?

I can't use my _Mekasuit_ from _Mekanism_ because yall f**k up their rendering so DON'T DO ANYTHING TO THIER CODE, aka
don't apply Oculus/Iris code to _Mekanism_ 

### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.19+mc1.20.1-all.jar

### Operating System

Windows 11 23H2

### What is your GPU?

NVIDIA Geforce RTX 4070 Super

### Java Version

Java 17

**Comment by I4LYT** [comment]
bro mekanism discord says that this is what's happening

**Comment by dima-dencep** [comment]
We don't change the mekanism code, the problem is that they too use shaders to render different things, which breaks if iris/oculus shaders are active.
