### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by ErythroCraft** [Asek3/Oculus#647]
I have seen many bug reports, but I don't know why.

At me Oculus 1.20.1 is working with most popular mods. 196 mods

Can you create a 1.20.4 Version please?

THX

**Comment by dima-dencep** [comment]
https://github.com/IrisShaders/Iris/tree/multiloader-1.21
https://github.com/IrisShaders/Iris/tree/multiloader-1.20.6
https://github.com/IrisShaders/Iris/tree/multiloader-1.20.1
