### ISSUE TITLE
Oculus bug incorrect display of emotecraft+ bendy-lib + embendium + oculus

### ISSUE THREAD

**Issue by deadrabbit12** [Asek3/Oculus#655]
### What happened?

Oculus bug incorrect display of emotecraft+ bendy-lib animations with the embendium + oculus mod (emendium itself works correctly in the beta version, but osulus also works correctly without it, please enable full support for this mod)

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

embeddium-0.3.22-git-1012d03+mc1.20.1.jar

### Operating System

windows 10

### What is your GPU?

amd rx460 2G

### Java Version

java 21

**Comment by deadrabbit12** [comment]
The developer Embendium wrote to me (https://github.com/embeddedt/embeddium/issues/321 )

[embeddedt](https://github.com/embeddedt) commented
I cannot fix it on my end. Iris/Oculus are designed very poorly, and duplicate substantial amounts of Sodium code inside them, so even after I fix a bug, Oculus often undoes the fix when installed.

**Comment by Cuyoya** [comment]
Having this same issue, and would love a solution soon since it's shown to be a fixable issue.

**Comment by dima-dencep** [comment]
I fixed but embeddedt redid the patch, anyway this bug is in the original iris and sodium
