### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by Silvertail4764** [Asek3/Oculus#656]
### What happened?

Crashing when booting with Neoforge 1.20.1

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

rubidium-mc1.20.1-0.7.1a.jar

### Operating System

Windows 11

### What is your GPU?

RTX 2070 S

### Java Version

Open JDK 17.0.8 64 bit (Default)

### Additional context

[crash-2024-06-29_19.01.15-client.txt](https://github.com/user-attachments/files/16042463/crash-2024-06-29_19.01.15-client.txt)

**Comment by dima-dencep** [comment]
Use embeddium
