### ISSUE TITLE
Oculus adds light to blocks that are affected by the Multi Mine mod.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Oculus#66]
### What happened?

Oculus adds light to blocks that are affected by the Multi Mine mod.

Oculus: 1.16.5-1.2.3
Multi Mine: 1.16.5

Visual representation of the bug:
https://www.youtube.com/watch?v=bCPY6-_RBpc

### Minecraft Version

1.16.5

### Iris Version

Oculus 1.16.5-1.2.3

### Sodium Version

Rubidium 1.16.5-0.2.6

### Operating System

Win 10

### What is your GPU?

Nvidia Geforce RTX 3070ti

### Java Version

Java 8

### Additional context

Only happens when shaders are applied (not sure if it depends on what shaders you use but, in the video above I was using complimentary shaders).

**Comment by Asek3** [comment]
Should be fixed in 1.4.8
