### ISSUE TITLE
The game crashed whilst rendering entity

### ISSUE THREAD

**Issue by battousan** [Asek3/Oculus#660]
### Minecraft Version

1.20.1

### Oculus Version

1.7.0

### Rubidium / Embeddium Version

0.3.19

### Operating System

Windows 10

### What is your GPU?

Nvidia 4080

### Java Version

Java 17

### Reproduction Steps

I get the following error code every 30 minutes of game play. Curseforge 47.3.1
Mod: TNP 7 Ver: 1.9.0
Mem:  -Xmx14336m -Xms14336m
Error: The game crashed whilst rendering entity in world Error: java.lang.OutOfMemoryError: Failed to resize buffer from 2145388032 bytes to -2147482112 bytes
[crash-2024-07-05_16.35.48-client.txt](https://github.com/user-attachments/files/16114587/crash-2024-07-05_16.35.48-client.txt)
[2024-07-05-2.log](https://github.com/user-attachments/files/16114589/2024-07-05-2.log)

### Additional context

.

**Comment by dima-dencep** [comment]
Downgrade forge

**Comment by BenjiLangQc** [comment]
Downgrade to which version? I also get this error
