### ISSUE TITLE
1.21 Version of Oculus

### ISSUE THREAD

**Issue by Anthem007** [Asek3/Oculus#662]
I have started a new modded server through Neoforge for me and my friends on Minecraft 1.21, however I am unable to run shaders on it.

It would be great to see a 1.21 version of oculus made so many people can enjoy modded minecraft with shaders through Forge/Neoforge.

**Comment by dima-dencep** [comment]
Use iris

**Comment by NovaViper** [comment]
@dima-dencep There's a version of Iris and Sodium that work on NeoForge now? There aren't any publicly available versions on either CurseForge of Modrinth and the [website](www.irisshaders.dev) for Iris doesn't indicate that this is the case either.

**Comment by dima-dencep** [comment]
Check out Irisshaders's discord
