### ISSUE TITLE
oculus 1.7.0 runs buggy in MC1.20.1 as well as incompatibility with other mods

### ISSUE THREAD

**Issue by BaiSoon0267** [Asek3/Oculus#664]
### Minecraft Version

Minecraft 1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

rubidium-mc1.20.1-0.7.1a.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 4060 Laptop 

### Java Version

Java 17.0.11

### Reproduction Steps

Windows 11
Minecraft  1.20.1
Forge 47.3.5
Java 17.0.11
Mixin 0.8.5
HMCL Launcher 3.5.8
No shaderpacks , No Resourcepacks
Mods involved : Oculus（1.7.0/1.6.9）、Connector、Rubidium

I submitted log file and zip file,it's a bug crash content that loads 「oculus-mc1.20.1-1.7.0.jar」 separately.

[minecraft-exported-logs-2024-07-12T22-05-56.log](https://github.com/user-attachments/files/16195293/minecraft-exported-logs-2024-07-12T22-05-56.log)

[minecraft-exported-crash-info-2024-07-12T22-06-02.zip](https://github.com/user-attachments/files/16195301/minecraft-exported-crash-info-2024-07-12T22-06-02.zip)

1.Only loading 「oculus-mc1.20.1-1.7.0.jar」 will not be able to run the game in the above environment.

The HMCL Launcher report " Could not initialize class con.mojang.blaze3d.systems.RenderSystem ".

2..Load the game successfully by loading the 「Connector-beta.44+1.20.1.jar」 at the same time as the 「oculus-mc1.20.1-1.7.0.jar」.

3.Loading the 「rubidium-mc1.20.1-0.7.1a.jar」 while loading the 「oculus-mc1.20.1-1.7.0.jar」 will not be able to run the game in the above environment.( This isn't the reason for rubidium, as I can run the game by loading rubidium alone.)

The HMCL Launcher report " Some mod injections fail ".

4.Loading 「oculus-mc1.20.1-1.7.0.jar」, 「Connector-beta.44+1.20.1.jar」, and 「rubidium-mc1.20.1-0.7.1a.jar」 at the same time will not be able to run the game successfully.（Note that I was able to run the game successfully by just loading connetcot with rubidium.）

The HMCL Launcher report " The current game cannot continue to run because Mixin is unable to apply oculus mods ".

5.Interestingly, I was able to load the game successfully by loading the 「oculus-mc1.20.1-1.6.9.jar」 separately.Also run the game by loading 「Connector-beta.44+1.20.1.jar」 and 「rubidium-mc1.20.1-0.7.1a.jar」 together with 「oculus-mc1.20.1-1.6.9.jar」.

**Comment by dima-dencep** [comment]
Use embeddium
