### ISSUE TITLE
(Not Resolved) Incompatibility with OC2:R

### ISSUE THREAD

**Issue by hickorysb** [Asek3/Oculus#666]
### What happened?

Oculus causes the projector from OpenComputers 2: Reimagined to render over top of people in an awkward incorrect order.

### Screenshots

With Oculus:
![2024-07-19_03 09 18](https://github.com/user-attachments/assets/88cbf0b2-ba9b-4896-8be2-0fc07d8ec0b8)
![2024-07-19_03 09 24](https://github.com/user-attachments/assets/a5973f45-7197-46b4-a156-78b74a0b6510)
![2024-07-19_03 09 26](https://github.com/user-attachments/assets/a171b30b-0586-4957-9a24-63c0d1432426)

Without Oculus:
![2024-07-19_03 17 23](https://github.com/user-attachments/assets/6890283e-7d7a-473f-88a2-b0b4331b2629)
![2024-07-19_03 17 27](https://github.com/user-attachments/assets/bb65dab3-b49f-40ea-9feb-f4ec0d649a1e)
![2024-07-19_03 17 29](https://github.com/user-attachments/assets/a68eba9f-a210-4546-a478-cecc62ab828b)

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.25+mc1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 4070 Ti

### Java Version

Java 17

### Additional context

Happens on multiple computers, both in and out of dev environment. Any help in resolving this incompatibility would be appreciated, whether it's resolved on my end (I am the maintainer of OC2:R) or yours. Embeddium++ is also installed, but it's presence does not alter the outcome.

Log:
[debug.log](https://github.com/user-attachments/files/16311187/debug.log)
[latest.log](https://github.com/user-attachments/files/16311188/latest.log)

**Comment by dima-dencep** [comment]
As I see it happening without the oculus, so

**Comment by hickorysb** [comment]
Could you double check and provide info on what versions of each mod you have? I and several others have tested this extensively and only have the issue described within when Oculus is installed. As you can see in the screenshots provided without Oculus it is fine. Enabling or disabling Oculus was the only thing that changed between those screenshots sets.

**Comment by dima-dencep** [comment]
Look at your own screenshots...

**Comment by hickorysb** [comment]
I have, the thing happening in the ones labeled "without oculus" are exactly what's supposed to happen. It's a projector, when you are *in front of the projector* it should project on your back. When you are behind the projector it shouldn't (see screenshot one of both sets). Looking at screenshot two,  when close to the surface the projector is projecting on to it is not projecting onto the players back like it should with Oculus.
