### ISSUE TITLE
Shader Glitch with Supplementeries Jar

### ISSUE THREAD

**Issue by Hiconel** [Asek3/Oculus#67]
### What happened?

With the shaders enabled and jars from the Supplementaries Mod close by, you get this weird visual bug where white dots appear, while being close to said jars. The dots always seem to appear approximately at the same spot on the screen and disapear when you move further away.

I have tried it with Complementary shaders v4.4 as well as BSL v8.1.02.1, Sildurs Vibrant Shaders v1.29 (dots are black instead of white) and SEUS PTGI E12, with SEUS being the only one where no dots appear. 

With the settings "Potato" and "Low" the issue also doesn't appear when using Complementary Shaders.

### Screenshots

![image](https://user-images.githubusercontent.com/1748758/165849863-df26037a-9214-43c2-95cb-a46d2c865db1.png)

Each placed jar within a certain radius creates a white dot. You can even write with it, like I did here. (Complementary)

![image](https://user-images.githubusercontent.com/1748758/165850278-1d619d5a-8905-4fdc-bce0-355297faae9d.png)

The further away you are, the less you see of it. The direction you are facing doesn't matter. Only distance seems to be important. (Complementary)

![image](https://user-images.githubusercontent.com/1748758/165856182-24076da5-9dae-4a90-a35f-990c1dcd6512.png)

Here the direction you are facing does seem to matter a little. (Sildurs)

### Minecraft Version

Minecraft 1.18.2

### Iris Version

oculus-mc1.18.2-1.2.4

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 2070

### Java Version

Java 17

### Additional context

It's not really a huge issue, but I thought worth mentioning. Also a huge thank you for getting Create working with Oculus! Absolutely amazing 😍

**Comment by Hiconel** [comment]
I use the Create Mod and noticed that these spots don't appear when you use ' /flywheel backend off '

**Comment by Asek3** [comment]
Should be fixed on latest Flywheel and Oculus versions. If not, plz tell

**Comment by Hiconel** [comment]
Yes, it's working properly now. Thanks!
