### ISSUE TITLE
Mod Arrows Not Rendering

### ISSUE THREAD

**Issue by D3monzHunt3r** [Asek3/Oculus#677]
### What happened?

**I'm putting together a modpack for a group of friends and am currently using:**
Embeddium, Em. Dynamic Lights, and Oculus with shaders on Forge 1.20.1

I'm using a mod called Fabulous Fletching which adds custom arrows. Without shaders they work fine but with shaders the custom arrows don't render at all. They remain fully functional, particles and all, but with shaders enabled they just disappear...

I don't know if it's an Oculus issue but I've been trying to figure this out for hours and I have no idea what's going on lol

### Screenshots

![image_2024-08-16_234653003](https://github.com/user-attachments/assets/e914f293-2356-4a5b-8550-db5085ce65d3)
![image_2024-08-16_234701468](https://github.com/user-attachments/assets/e59386ec-b334-4605-8ff8-1a67358706be)

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.30+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

RTX 3060ti

### Java Version

Java 21 I think?

### Additional context

 Particles and extra effects still appear, as well as the tracer when shooting. They deal damage, the 2D item displays when dropped, and the plain vanilla arrow works like usual (as well as the potion arrows)

**Comment by dima-dencep** [comment]
no logs - no bugs
