### ISSUE TITLE
Shader Pack Settings option not working in the menu 1.20.1

### ISSUE THREAD

**Issue by FruitSanwich** [Asek3/Oculus#679]
### What happened?

So when running my forge modpack (using curse launcher) the game loaded up fine but the shader pack (chocapic13) is seemingly not working. I went into the shader pack menu on oculus and it's enabled but not working. When I tried to click on the settings option in the shader menu it does nothing. I intentionally ran just oculus and the shader to see if mod conflict is the issue, but the problem persists.
I'm gonna test if this is just a problem with either my laptop or chocapic, but I figured I'd throw this out there just incase.

### Screenshots

![Minecraft Forge_ 1 20 1 - Singleplayer 8_22_2024 1_39_45 PM](https://github.com/user-attachments/assets/8f42c606-778b-4976-9d1d-9e1c262fe022)

### Minecraft Version

1.20.1

### Oculus Version

1.7.0

### Rubidium / Embeddium Version

embeddium 0.3.30

### Operating System

Windows 10

### What is your GPU?

intel hd 620

### Java Version

java 17 (probably)

**Comment by dima-dencep** [comment]
shader issue
