### ISSUE TITLE
Extremely Bad Performance with 1.2.4

### ISSUE THREAD

**Issue by TheRealDadbeard** [Asek3/Oculus#68]
### What happened?

I only have around 36fps instead of over 100 after installing 1.2.4

### Minecraft Version

1.18.2

### Iris Version

1.2.4

### Sodium Version

0.5.2a

### Operating System

Windows 11

### What is your GPU?

RTX 2070

### Java Version

17

### Additional context

[latest.log](https://github.com/Asek3/Oculus/files/8587142/latest.log)

**Comment by SmokePuddingEveryday** [comment]
Remove ImmersiveEnginnering and see if the performance problem continues. In my case on 1.16.5, it was the reason for the performance decrease.

**Comment by TheRealDadbeard** [comment]
Nice, I tried but for some reason ATM7 doesn't create a world without it activated. Maybe there is a dependency that I don't know of.

**Comment by Asek3** [comment]
Should be fixed since 1.4
