### ISSUE TITLE
Easy Villagers cause a visual bug

### ISSUE THREAD

**Issue by DracoHero** [Asek3/Oculus#681]
### What happened?

I have discovered that with the Easy Villagers mod and the Oculus Shader system, it causes this visual error in the villagers in which their "sleeves" do not appear

### Screenshots

![2024-08-23_02 04 16](https://github.com/user-attachments/assets/d7b18c75-c5ff-417b-8097-c5090cb275ad)

### Minecraft Version

1.20.1

### Oculus Version

1.7.0

### Rubidium / Embeddium Version

Embeddium 0.3.30-mc1.20.1

### Operating System

Windows 11

### What is your GPU?

RTX 4060

### Java Version

Java 17

**Comment by dima-dencep** [comment]
no logs - no bugs
