### ISSUE TITLE
Embeddium  Oculus + Create 0.51f crash

### ISSUE THREAD

**Issue by ApertureScience9592** [Asek3/Oculus#688]
### Minecraft Version

FML 1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.15a

### Rubidium / Embeddium Version

Embeddium-0.3.31

### Operating System

Win11

### What is your GPU?

Nvidia GTX 1650

### Java Version

Java 17

### Reproduction Steps

Enable shaders
Place down a basin from create
Game will crash (not all vertexs filled)

### Crash Report file and latest.log

[crash-2024-09-04_19.43.00-client.txt](https://github.com/user-attachments/files/16896792/crash-2024-09-04_19.43.00-client.txt)

### Additional context

Oculus will crash with Embeddium if it isn't 1.6.15a.

**Comment by Guuuitouuu** [comment]
Delete Distant Horizons, it had some issues with Create and Oculus

**Comment by dima-dencep** [comment]
Not an oculus bug
