### ISSUE TITLE
Oculus stops Custom Entity Optifine Models loading on 1.20.1 Forge.

### ISSUE THREAD

**Issue by Crafty1340** [Asek3/Oculus#690]
### What happened?

I have resource packs that retexture the mobs, they require Optifine to work, I have both EMF and ETF and the Models don't load, why? Even with Shaders disables, the Models still don't load...

### Screenshots

![image](https://github.com/user-attachments/assets/dcb6f3e8-8b2a-4099-9bc1-8324f08d3b47)
![image](https://github.com/user-attachments/assets/d40003f0-5889-47f8-8374-b6d404c9f1a2)

The links are the images, one with Oculus and one Without Oculus.

### Relevant log output

```shell
There is none, this isn't a crash.
```

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

embeddium-0.3.31+mc1.20.1

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 3060

### Java Version

Java 8

### Additional context

Why is this happening? Please fix! Also, don't judge my resource packs please...

**Comment by mpustovoi** [comment]
At least, provide `latest.log` if there's no crash. It may help to find some issues during models loading.

**Comment by dima-dencep** [comment]
NO LOGS - NO BUGS

**Comment by IDragen** [comment]
There is a mod called EntityModelShaderFix for version 1.20.1 that fixed the problem.
