### ISSUE TITLE
Custom keybinds

### ISSUE THREAD

**Issue by kaka34665** [Asek3/Oculus#695]
It's really annoying when I also got timeless and classics zero since it also uses R as reload. I use shaders so it just freezes a bit because R is also the key for reloading shaders. I really don't want to disable shaders just to use guns..

Simply make keybinds customizable, and especially the key for reloading shaders. That is all I can ask.

**Comment by mpustovoi** [comment]
Really?
Open the settings and go to the `Controls` page. Scroll down and you will find the `Oculus` section.

**Comment by kaka34665** [comment]
> Really? Open the settings and go to the `Controls` page. Scroll down and you will find the `Oculus` section.

How? The only thing I know is managing shaders

**Comment by kaka34665** [comment]
> Really? Open the settings and go to the `Controls` page. Scroll down and you will find the `Oculus` section.

Alr it works. Cheers lad

**Comment by mpustovoi** [comment]
Good. Then I guess it's worth closing the issue.
