### ISSUE TITLE
Crash On Startup (Oculus Problem?)

### ISSUE THREAD

**Issue by SnowXDev** [Asek3/Oculus#696]
### Minecraft Version

Minecraft 1.20.1 (Forge 47.3.0)

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.31+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060 Super

### Java Version

Java 17?

### Reproduction Steps

1. Launch Game
2. Loads for a second or two.
3. Crashes to launcher.

### Crash Report file and latest.log

```shell
- Crash Report
https://mclo.gs/JoZM7Td
```

### Additional context

Without Embeddium & Oculus installed, everything boots fine.
However as soon as either or both are enabled, game crashes on startup.

**Comment by MrRokhead** [comment]
I'm having the exact same problem. Embeddium complaining about Oculus. If you check the logs it's one of the first lines. I'm not sure why this problem is suddenly happening, when they've worked fine together in the past.

**Comment by SettingDust** [comment]
chunkanimator

**Comment by MrRokhead** [comment]
> chunkanimator

I don't have chunkanimator but have the same issue.

**Comment by SettingDust** [comment]
> I don't have chunkanimator but have the same issue.

You've not posted your crash report. I just type in the reason from crash report

**Comment by MrRokhead** [comment]
---- Minecraft Crash Report ----
// Embeddium instance tainted by mods: [oculus, embeddium_extra]
// Please do not reach out for Embeddium support without removing these mods first.

[https://mclo.gs/L9qan3g](url) 

I also tried removing Embeddium Extra, and launching it then just looked like this 

---- Minecraft Crash Report ----
// Embeddium instance tainted by mods: [oculus]
// Please do not reach out for Embeddium support without removing these mods first.

[https://mclo.gs/zwM5lr4](url)

**Comment by MrRokhead** [comment]
After some testing, the unreleased latest version of Oculus, 1.20.1 new, worked with Distant Horizons, Oculus, and Embeddium/Rubidium. I am able to open the game and play. 

However, now the moment I try to turn on any shader, the whole game crashes.

Halp D:

**Comment by MrRokhead** [comment]
Well disabling Iris/Oculus & Geckolib compat and Iris/Oculus & Flywheel compat worked. I hope that doesn't mean it'll never work with those :/ Maybe its just because its the unreleased version of Oculus.

**Comment by dima-dencep** [comment]
Not an oculus bug
