### ISSUE TITLE
(Not only) Immersive Railroading models turning compeltely invisible

### ISSUE THREAD

**Issue by CZECHsimon** [Asek3/Oculus#697]
### What happened?

The way Oculus works somehow manages to turn some mod models completely invisible. (Not only Immersive Railroading, but it's the most notable one) The same also applies to Immersive Engineering, where the fix was quite simple - Disable VOD rendering in the mod's config. Unfortunately, Immersive Railroading doesn't have the luxury of that. The models turn completely invisible when enabling shaders. My guess is that Oculus is overriding IR rendering pipeline. We've been waiting for a fix since 2022! This is not the first Github issue report regarding this! (I'm pretty much just bumping this issue)

### Screenshots

![image](https://github.com/user-attachments/assets/fbd0efc8-91a5-4f19-8aa2-66be75619ffe)
![image](https://github.com/user-attachments/assets/b646f674-4a41-44dc-9261-9592c021ea3f)
![image](https://github.com/user-attachments/assets/7ea4cb51-e73d-45c8-afad-c0deb1ce0280)
![image](https://github.com/user-attachments/assets/bfb44250-2a0a-4fdf-8db8-5d22d453859b)

### Relevant log output

```shell
No log errors found
```

### Minecraft Version

Forge 1.16.5

### Oculus Version

oculus-mc1.16.5-1.4.8

### Rubidium / Embeddium Version

rubidium-mc1.16.5-0.2.13

### Operating System

Windows 10/11 

### What is your GPU?

ROG STRIX RTX 4080 Super OC (16GB)

### Java Version

Java Oracle 21.0.3

**Comment by mpustovoi** [comment]
1. Have you tried Embeddium instead of Rubidium?
2. Provide the `latest.log` anyway.

**Comment by dima-dencep** [comment]
Use embeddium

**Comment by Larky2k** [comment]
Just to say does it on embeddium as well.

**Comment by the-plastic-potato** [comment]
i have same issue

**Comment by the-plastic-potato** [comment]
try messing with other shaderpacks or shaderpack settings
