### ISSUE TITLE
Incompatibility with Architectuary (1.18.2)

### ISSUE THREAD

**Issue by drakosoldier298** [Asek3/Oculus#7]
When loading with architectuary 3.7.37 it seems to freak out.

https://0x0.st/oqfQ.txt

Ive experienced that even with not enough crashes its unplayable as then if your PC doesn't crash the games text renders as unknown font, which is just rectangles.

**Comment by drakosoldier298** [comment]
Architectuary is aware of this for a different mod, https://github.com/shedaniel/BetterLoadingScreen/issues/1

but has given no information on if they are working on fixing it.

**Comment by Asek3** [comment]
Obviously not Oculus' issue
