### ISSUE TITLE
Issues with Create

### ISSUE THREAD

**Issue by ruiluth** [Asek3/Oculus#70]
### What happened?

Many items from the Create mod simply don't render with Oculus. Whether moving or still, they're completely invisible. Create is completely unplayable with Oculus installed.

### Screenshots

![2022-04-29_23 22 11](https://user-images.githubusercontent.com/10102450/166090885-1d1dc9e9-55c1-4498-a029-cec022785fcf.png)
![2022-04-29_23 26 01](https://user-images.githubusercontent.com/10102450/166090887-8ea14e4d-6b9f-4e32-b492-cd79abc9e4b5.png)

### Minecraft Version

1.18.2

### Iris Version

Oculus 1.2.2b

### Sodium Version

Rubidium 0.5.2a

### Operating System

Linux Mint 20.2

### What is your GPU?

Nvidia GeForce 1660 Super

### Java Version

default (Java 16?)

**Comment by KarinMiku** [comment]
download/update the latest release of oculus 1.2.4

**Comment by Asek3** [comment]
Update Oculus
