### ISSUE TITLE
Unidentifiable crash within BYG Lush Stacks biome w/shaders turned on

### ISSUE THREAD

**Issue by Runburner** [Asek3/Oculus#703]
### Minecraft Version

Minecraft 1.19.2

### Oculus Version

oculus-mc1.19.2-1.6.9.jar

### Rubidium / Embeddium Version

embeddium-0.3.18.1+mc1.19.2.jar

### Operating System

Windows 11

### What is your GPU?

GeForce RTX 4080

### Java Version

Java 17

### Reproduction Steps

1. Use modpack https://modrinth.com/modpack/between-horizons/version/1.0.5
2. Use a shader of choice. I have used Complimentary, BSL, and Solas.
3. Load into a new world
4. Locate a Lush Stacks biome from BYG
5. Go towards the ocean floor
6. Game will either crash to desktop or go black screen and become completely unresponsive requiring a kill

### Crash Report file and latest.log

[latest.log](https://github.com/user-attachments/files/17267544/latest.log)
[crash-2024-10-05_18.03.12-client.txt](https://github.com/user-attachments/files/17267543/crash-2024-10-05_18.03.12-client.txt)

### Additional context

This is happening not only on my system but also several of my friends that play the game. I have tested on my desktop and laptop. We all have RTX cards ranging from 2080 Super, 4070, and 4080. All Windows 11 systems. This issue ONLY happens if shaders are turned on. I have tried to determine if its a mob or something but have been unsuccessful in narrowing down the cause. I was hoping to narrow it down to assist with this crash report but couldn't seem to narrow it down anymore.

**Comment by dima-dencep** [comment]
Not an oculus bug
