### ISSUE TITLE
minecraft all the way up to 1.21.1 and newer than that version

### ISSUE THREAD

**Issue by ShadeError03** [Asek3/Oculus#706]
**Is your feature request related to a problem? Please describe.**
I cant play with shaders on 1.21.1 because this hasn't been updated 10/15/2024

**Describe the solution you'd like**
Make a version of Oculus for 1.21.1 and the remaining versions please

**Describe alternatives you've considered**
playing on older versions but I need shaders for 1.21.1
**Additional context**

**Comment by dima-dencep** [comment]
Use iris

**Comment by alexiokay** [comment]
iris doesnt work with custom shaders. Oculus worked in 1.20.1
