### ISSUE TITLE
Oculus crashing with Create Mod and Embeddium

### ISSUE THREAD

**Issue by mauuuuuuuu** [Asek3/Oculus#709]
### Minecraft Version

Minecraft 1.21.1

### Oculus Version

oculus-mc1.20.1-1.7.0

### Rubidium / Embeddium Version

embeddium-0.3.28+mc1.20.1

### Operating System

Windows 11

### What is your GPU?

Radeon RX6800

### Java Version

Java 8

### Reproduction Steps

Having a modpack with Embeddium, Create and Distant Horizons and Oculus. The game always crashes. When deleting Oculus the game works. 
I tried using different Sodium forks - none work. 
[crash-2024-10-25_21.40.39-client.txt](https://github.com/user-attachments/files/17526875/crash-2024-10-25_21.40.39-client.txt)
[latest.log](https://github.com/user-attachments/files/17526878/latest.log)

**Comment by Pultex** [comment]
on newest yes works with 
oculus-mc1.20.1-1.6.15a
for me 
1.20.1 minecraft
no Distant Horizons

**Comment by mpustovoi** [comment]
Latest 1.20.1 version of Oculus isn't compatible with Distant Horizons v2.2.X. This issue has already been reported: https://github.com/Asek3/Oculus/issues/683.

If you want to use Distant Horizons with Oculus, use Oculus v1.7.0 & Distant Horizons v2.1.2-a. These are working fine for me.

As for Create, I doubt its compatibility with Distant Horizons at all. However, I didn't have to try.

**Comment by dima-dencep** [comment]
Not an oculus bug

**Comment by mauuuuuuuu** [comment]
I moved to Fabric anyway. Found a Minecraft version to get all three mods running. Thanks.

________________________________
Von: dima_dencep ***@***.***>
Gesendet: Mittwoch, 30. Oktober 2024 16:46
An: Asek3/Oculus ***@***.***>
Cc: mauuuuuuuu ***@***.***>; Author ***@***.***>
Betreff: Re: [Asek3/Oculus] Oculus crashing with Create Mod and Embeddium (Issue #709)


Not an oculus bug
