### ISSUE TITLE
Oculus Crash after X minutes

### ISSUE THREAD

**Issue by ModpackFailedSuccesfully** [Asek3/Oculus#712]
### Minecraft Version

Minecraft 1.20.1

### Oculus Version

Oculus mc1.20.1-1.6.15a

### Rubidium / Embeddium Version

Embeddium 0.3.31+mc1.20.1

### Operating System

Windows 10

### What is your GPU?

Nvidia 4070

### Java Version

Java 21

### Reproduction Steps

1.Launch game with lot of mods
2.Enable "Complimentary Shaders - Reimagined r5.2.2
3.Try to explore , in some places game crashes after 1 hour in other after 10 min

### Crash Report file and latest.log

```shell
https://gist.github.com/ModpackFailedSuccesfully/b4eb6fdf9f8f410abb10f6f3c29da281
```

### Additional context

This issue is on my friend PC ,I (rx 6600 same mods) doesn't have it at all
1 When we started world we could play for even 2-3 hours without crash
2 The more we explored (more chunks discovered) the more often after 1+ hour game crashed
3 When we went long distance to a Jungle biome friend started crashing after 10 min ,while I ,on same save was able to stay in that place for unlimited time
4 After removing Oculus we played for 5 hours and still not a single crash

**Comment by mpustovoi** [comment]
According to `java.lang.OutOfMemoryError` it seems that a Minecraft instance didn't have enough allocated memory. I doubt this could be an Oculus bug at all.
Check how many gigabytes of RAM are allocated for Minecraft. Try setting this value to 4, 6 or 8 GB, depending on the size of your modpack, if you currently have much less RAM allocated.
