### ISSUE TITLE
Oculus making Draconic Evolution tools invisible 

### ISSUE THREAD

**Issue by caiucaindo** [Asek3/Oculus#718]
When playing with Oculus and Draconic Revolution, almost all Draconic tools become invisible in third-person view or when dropped on the ground. They can only be seen when held in the first-person view. Even if no shaders or configurations are active in Oculus, this bug persists just by having both mods in the game. I contacted the folks at Draconic, and they informed me that it is a problem with Oculus itself, which they cannot resolve, only you can. It's an issue that has existed since 2022 and has not been fixed until today.

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.31+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1050

### Java Version

Java 17

**Comment by dima-dencep** [comment]
#645
