### ISSUE TITLE
Any support for Distant Horizons 2.3?

### ISSUE THREAD

**Issue by SongOfCarp** [Asek3/Oculus#726]
Distant Horizons has updated to 2.3 recently and requires oculus 1.8.0, which confusing me because I only find oculus 1.7.0 here or on modrinth.

**Comment by IamKayrox** [comment]
Yeah, that's because Oculus is a port of Iris, Iris already has a version 1.8, the only thing you can do now is wait for the Oculus dev to update the mod to 1.8

**Comment by IvorAmlug** [comment]
Bringin Oculus to the stand of Iris 1.8 would be neat in general since the Iris 1.20 versions at least the NeoForge/Forge build are somewhat "dead" or paused and the early versions that were released miss many compats Embeddium and Oculus have (for example create compat and Valkyren Skies Compat).
