### ISSUE TITLE
Bend Emotes [Emote Craft]

### ISSUE THREAD

**Issue by Shisuiicaro** [Asek3/Oculus#727]
### What happened?

Bend emotes from bendylib or https://modrinth.com/resourcepack/emotebendhttps://modrinth.com/resourcepack/emotebend aren't working, they work fine with embeddium bug not with oculus, its working with the iris 1.7.5 (tester version)

### Minecraft Version

1.20.1

### Oculus Version

Latest

### Rubidium / Embeddium Version

Latest

### Operating System

Windows 11

### What is your GPU?

Vega 8

### Java Version

Java 17

**Comment by Shisuiicaro** [comment]
its working with iris, why not planned then?

**Comment by dima-dencep** [comment]
But not on 1.20.1
We will release an oculus update when we have the power and it will have this fix.

**Comment by Shisuiicaro** [comment]
Ok thanks very much
