### ISSUE TITLE
Crash related to Dynamic Lights.

### ISSUE THREAD

**Issue by MagmaSlime123** [Asek3/Oculus#728]
### Additional Content

Please remove this mod if you're not interested in it. The last commit was 8 months ago.

### Minecraft Version

1.16.5.

### Oculus Version

1.4.8

### Rubidium / Embeddium Version

0.3.18

### Operating System

Windows 11.

### What is your GPU?

AMD 6650 XT.

### Java Version

Minecraft has used Java 8 until 1.17. This is 1.16.5, so you should know this already.

### Reproduction Steps

Run around in a world for a while, game will crash randomly. I do not know how to reproduce this easily.

### Crash Report file and latest.log

```shell
https://pastebin.com/gYrVDzn8
```

### Additional context

Forge puts the mod list in crash reports. See the Pastebin above for that.

**Comment by MagmaSlime123** [comment]
No response isn't helpful. Please explain.

**Comment by dima-dencep** [comment]
I don't see the oculus issue, embeddium is trying to update the lights and dynamiclightsreforged is crashing because of CME
