### ISSUE TITLE
neo forge

### ISSUE THREAD

**Issue by Hk-5** [Asek3/Oculus#730]
**Is your feature request related to a problem? Please describe.**
there aren't really any mods i can think of for neoforge that give shaders 
**Describe the solution you'd like**
Neo already has embedium it just needs a addon hence 
me asking

**Additional context**
make a fork of oculus for neo plz so i can add it to mod packs that use it

**Comment by MagmaSlime123** [comment]
Dead mod. Last commit was 8 months ago.

**Comment by Hk-5** [comment]
9k

**Comment by Hk-5** [comment]
Ok

**Comment by kakashi1464** [comment]
use iris instead
