### ISSUE TITLE
Newest oculus 1.20.1-1.7.0 breaks Corail Tombstones grave fog and soul

### ISSUE THREAD

**Issue by Ezoteric** [Asek3/Oculus#733]
### What happened?

Corail Tombstones grave fog and soul wont show anymore with latest version mc1.20.1-1.7.0
It however still works on mc1.20.1-1.6.15a, see screenshot.

### Screenshots

![image_2024-12-05_005235568](https://github.com/user-attachments/assets/2f171652-4842-4392-84d6-7ac9586d2633)
This is what it should look like and screenshot is taken with mc1.20.1-1.6.15a, When you install mc1.20.1-1.7.0 both dont work anymore

### Minecraft Version

MC 1.20.1 Forge 47.3.0

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.31+mc1.20.1.jar

### Operating System

Win 10

### What is your GPU?

Nvidia 1070

### Java Version

java 8

**Comment by Corail31** [comment]
@Ezoteric In 1.20.1, grave smoke can only work with some shaderpacks like BSL Shaders.
You can disable the grave smoke in gui (/tbgui config, fog_density to none) if you want to use a shaderpack not displaying it correctly.
**If you use Iris 1.8.0 on 1.21.1 (Neoforge), you can use any shaderpack without any problem ;)**
Example in 1.20.1 with BSL Shaders and the same version of Oculus/Embeddium as you (Note that 1.7.0 requires Corail Tombstone 8.8.3+).
![oculus-bsl-shader](https://github.com/user-attachments/assets/ef94e302-2d9d-4917-ac92-577b05d4fbbf)

**Comment by Ezoteric** [comment]
Yeah updating your mod also did the trick :) 
Thnx a lot

Ill close this.

**Comment by Ezoteric** [comment]
Yeah updating your mod also did the trick :)
Thnx a lot

Ill close this.
