### ISSUE TITLE
Shader crashes with Create mod

### ISSUE THREAD

**Issue by MisterReus** [Asek3/Oculus#74]
### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.4

### Sodium Version

rubidium-0.5.2

### Operating System

Windows 10

### What is your GPU?

GTX 1650 Mobile

### Java Version

Java 17

### Reproduction Steps

1. Disable shaders
2. Move to an area with Create mod contraptions (cogs, shafts, waterwheels, etc.)
3. Enable shaders
4. Game crashes

[crash-2022-05-01_16.27.18-client.txt](https://github.com/Asek3/Oculus/files/8598527/crash-2022-05-01_16.27.18-client.txt)

[latest.log](https://github.com/Asek3/Oculus/files/8598528/latest.log)

### Crash Report file and latest.log

[crash-2022-05-01_16.27.18-client.txt](https://github.com/Asek3/Oculus/files/8598527/crash-2022-05-01_16.27.18-client.txt)
[latest.log](https://github.com/Asek3/Oculus/files/8598528/latest.log)

**Comment by Matthysse** [comment]
It's a problem with Flywheel, if you do /flywheel backend off, you won't crash and will be able to use shaders and see create contraptions. Would be nice if we could see a compatibility with flywheel and shaders, or for the moment, if the flywheel backend could be disabled automatically when enabling shaders, and re-enabled when disabling shaders.

**Comment by MisterReus** [comment]
> 

Damn thanks for the fix, works pretty well on my modded server for now. Yeah, at least a notice would've helped regarding this issue but hey, it's a free mod that's still in development, can't complain too much here

**Comment by Asek3** [comment]
Update mods.
