### ISSUE TITLE
[1.18.2] Character rendering problem with Minecolonies

### ISSUE THREAD

**Issue by BradClc** [Asek3/Oculus#84]
### What happened?

Reproduce with:
minecolonies-1.18.2-1.0.720-ALPHA

### Screenshots

Without Oculus:
![2022-05-13_00 14 23](https://user-images.githubusercontent.com/88281511/168123022-8bfa2992-f057-4aea-a9cb-2f2e6218fbbb.png)
With Oculus:
![2022-05-13_00 19 13](https://user-images.githubusercontent.com/88281511/168123156-6568c832-9c84-4eeb-8383-24b71ac903b4.png)
![2022-05-12_21 51 11](https://user-images.githubusercontent.com/88281511/168123218-ab8656f2-51b3-430c-87c0-c8003a049cfa.png)

Only change oculus,always install rubidium

### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.4

### Sodium Version

rubidium-0.5.2a

### Operating System

Win10

### What is your GPU?

GTX1650

### Java Version

java17

**Comment by pa1nki113r** [comment]
I can confirm I'm seeing this issue as well

Minecraft Version
1.18.2

Iris Version
oculus-mc1.18.2-1.2.4

Sodium Version
rubidium-0.5.2a

Operating System
Win10

What is your GPU?
AMD 6800XT

**Comment by pa1nki113r** [comment]
From a user in the minecolonies discord:

"Found it in oculus's codebase. They're overwriting the base rendercode of mojang which is causing a problem with the calls that minecolonies are making to render.

MRenderTypes.java from minecolonies is calling the same code that MixinVertexFormat.java from oculus is changing."

**Comment by BradClc** [comment]
That's a shame, unless the author wants to change it.

**Comment by KaiserThompson** [comment]
So I actually was the one who left that comment on minecolonies discord and located exactly where that render code is in minecolonies. Lines 106-144 in renderbipedcitizen.java. It appears that oculus's changes to the rendercode breaks their matrix code causing shearing if multiple are on screen at once. This seems like oculus is trying to render them all as one entity rather than the seperate entities they should be rendered as.

**Comment by vuanx** [comment]
This was so annoying that I had to go back to Optifine. This is a duplicate of issue #5 btw

**Comment by nickmuenster** [comment]
Hey i hope this is the right place to ask. I have the same issue. is there a way to fix that? or a workaround?
Maybe a way to disable the notification symbols all together?

since oculus has the same issue after all

**Comment by oliverrook** [comment]
I can confirm this even happens with shaders disabled.

**Comment by Waterspark63** [comment]
> Hey i hope this is the right place to ask. I have the same issue. is there a way to fix that? or a workaround? Maybe a way to disable the notification symbols all together?
> 
> since oculus has the same issue after all

I don't really know if bumping is allowed or not ( let me know if it isn't please! ) but is there any work around, that could for the moment fix this, or is the only option really ignoring it/removing Oculus?

**Comment by greanthai420** [comment]
Same problem here, I hope we see a resolution soon

**Comment by Shadows-of-Fire** [comment]
Will be fixed via https://github.com/ldtteam/minecolonies/pull/8588

Until then, you can apply this fix manually via this small mixin mod: (you will need to remove it after minecolonies applies the fix). https://github.com/Shadows-of-Fire/minecolonies/releases/tag/mixin

**Comment by BradClc** [comment]
Cheers!<minecolonies-1.18.2-1.0.984-ALPHA >Fixed this issue
