### ISSUE TITLE
[1.18.2] Crash with SEUS

### ISSUE THREAD

**Issue by itsdinkd** [Asek3/Oculus#88]
### Minecraft Version

1.18.1

### Iris Version

oculus 1.18.2

### Sodium Version

rubidium

### Operating System

w10

### What is your GPU?

2080

### Java Version

17

### Reproduction Steps

1. Turn on SEUS HRR
2. Explore a world with TerraForged
3. crash

### Crash Report file and latest.log

```shell
https://gist.github.com/itsdinkd/8649977e82f78cc5c60a2b410acd0e45
```

**Comment by Asek3** [comment]
Update Flywheel and Oculus
