### ISSUE TITLE
Oculus block bug

### ISSUE THREAD

**Issue by Rumaruka** [Asek3/Oculus#91]
### What happened?

Hi
I have problem:In modpack with oculus-1.2.3-pre and ComplementaryShaders_v4.4 blocks are "highlighted" after click, 
but with  BSL_v8.1.02.3 I don`t have with problem ¯\_(ツ)_/¯

### Screenshots
https://imgur.com/a/jjgSYLZ

### Minecraft Version

1.16.5

### Iris Version

oculus-1.2.3-pre

### Sodium Version

rubidium-0.2.6

### Operating System

Windows 11

### What is your GPU?

Geforce GTX 1050 Ti

### Java Version

Java 1.8

**Comment by mythpan1** [comment]
I have the same issue, the box looks like the x-ray 
![2022-06-04 (2)](https://user-images.githubusercontent.com/43778494/171982471-10d24359-8211-4591-8c2f-e84b134e5785.png)
![2022-06-04 (4)](https://user-images.githubusercontent.com/43778494/171982624-a25d3445-e77f-4d58-8273-7c59ad3b4d6f.png)

**Comment by Asek3** [comment]
fixed
