### ISSUE TITLE
ComputerCraft/CC:Tweaked Monitor & Pocket Computer don't render properly

### ISSUE THREAD

**Issue by RoboSkyrat** [Asek3/Oculus#92]
### What happened?

Using Continuum shaders with ComputerCraft/CC:Tweaked causes monitors and pocket computers to not display properly.
Disabling the shader fixes the issue entirely.

### Screenshots

![Screenshot](https://pray-to-the.yiff.church/i/j4zx3rp9.png)

### Minecraft Version

Minecraft 1.18.2

### Iris Version

oculus-mc1.18.2-1.2.4.jar

### Sodium Version

rubidium-0.5.2a.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce 3070 TI

### Java Version

Java 17.0.1

**Comment by Gilberry** [comment]
This issue has been fixed on the main fabric iris branch as of update 1.2.4-build.38. Hopefully this fix gets ported over to oculus when possible.

**Comment by matpratta** [comment]
Using the latest Rubidium (0.5.3) + Oculus (1.2.5) versions here and can confirm the issue. Tried different shaders (BSL, Continuum, SEUS, etc) and all of them presented the same issue.


![2022-07-21_22 31 30](https://user-images.githubusercontent.com/532195/180342483-6676da11-ce0d-491c-a724-8601a3e82250.png)

**Comment by Asek3** [comment]
Fixed in latest CC:Tweaked versions
