### ISSUE TITLE
Floating Transparent Objects Stuck on Screen

### ISSUE THREAD

**Issue by AmpedNormal** [Asek3/Oculus#94]
### What happened?

Using All the mods 7 latest version (0.4.9)
Previously had the issue where chests were transparent and I thought this was linked as the shapes of the objects roughly matched the chests I had. Disabling Botania Shaders and Flywheel Backend fixed the transparent chests (made sure to restart game after changing) but left this issue.

The bug itself is hard to describe, it's like grey shapes that change position based on the direction I'm looking
https://youtu.be/KppXGS3UISI
Here's a video just to show what it looks like, look to the top of the screen.

Tried with Sildurs, SUES renewed and both had the issue. Tried the SUES HRR test and it got waaay worse, the shapes became darker and covered about 50% of the screen.

### Screenshots

https://youtu.be/KppXGS3UISI
video is unlisted so let me know if link doesn't work

### Minecraft Version

1.81.2

### Iris Version

oculus-mc1.18.2-1.2.4

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce 2060 Super

### Java Version

17.0.1.12.1

**Comment by MVandal80** [comment]
I've experienced a similar issue, where hexagonal artifacts would show on the screen. They would move slightly depending on my character's position. After experimenting, it seems to be related to shadows. If I increase the shadow resolution, the artifacts get smaller or disappear.

**Comment by AmpedNormal** [comment]
> I've experienced a similar issue, where hexagonal artifacts would show on the screen. They would move slightly depending on my character's position. After experimenting, it seems to be related to shadows. If I increase the shadow resolution, the artifacts get smaller or disappear.

That fixed it yeah, bumped shadow res up to max and boom they're gone.

**Comment by aethaerya** [comment]
https://github.com/Asek3/Oculus/issues/76

**Comment by Asek3** [comment]
Should be fixed on latest Flywheel and Oculus versions. If not, plz tell
