### ISSUE TITLE
Rendering issue in version 1.2.5 on 1.16.5 where mobs don't flash red when damaged.

### ISSUE THREAD

**Issue by Vaguely-Interesting** [Asek3/Oculus#96]
### What happened?

When I use version 1.2.5 for 1.16.5 mobs don't flash red when damaged after a certain amount of time (they do at first for a minute or two). The same thing happened on version 1.2.3. There's also a rendering issue with the wither storm from [Cracker's Wither Storm Mod](https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod) where the entire entity glows. (As far as I know it's only this one mob but there could be more)

### Minecraft Version

1.16.5

### Iris Version

1.2.5

### Sodium Version

0.2.6

### Operating System

Windows 10

### What is your GPU?

Geforce GTX 1070 TI

### Java Version

Java 8

**Comment by SmokePuddingEveryday** [comment]
Experiencing the same issue with mobs

**Comment by Asek3** [comment]
Fixed in 1.4.8
