### ISSUE TITLE
random dots and invisible blocks

### ISSUE THREAD

**Issue by quantumchan** [Asek3/Oculus#98]
### What happened?

blocks like chests and other blocks have become invisible. and when exploring the world black dots show up on screen. I've experimented with different shaders but it seams its a problem with oculus.

### Screenshots

![Minecraft_ 1 18 2 6_8_2022 2_10_22 PM](https://user-images.githubusercontent.com/103629893/172708523-dd9dcef9-36d5-4ee4-b66b-1600ffa4bb8d.png)
![Minecraft_ 1 18 2 6_8_2022 2_10_45 PM](https://user-images.githubusercontent.com/103629893/172708591-d00414d2-c4a8-4558-8e92-889766af5ce0.png)

### Minecraft Version

mincraft 1.18.2

### Iris Version

oculus-mc1.18.2-1.2.5.jar

### Sodium Version

idk

### Operating System

windows 11

### What is your GPU?

NVIDIA GeForce RTX 3070

### Java Version

java 11

**Comment by inverspe** [comment]
you might as well put more details such as mods and so on

**Comment by desvandev** [comment]
You need to disable Flywheel client shader in config.
The file is flywheel-client.toml, and then just put `backend = "OFF"`

**Comment by quantumchan** [comment]
> You need to disable Flywheel client shader in config. The file is flywheel-client.toml, and then just put `backend = "OFF"`

how do i do that?

**Comment by desvandev** [comment]
> > You need to disable Flywheel client shader in config. The file is flywheel-client.toml, and then just put `backend = "OFF"`
> 
> how do i do that?

There's actually an easier way, just type `/flywheel backend off`

**Comment by quantumchan** [comment]
> > > You need to disable Flywheel client shader in config. The file is flywheel-client.toml, and then just put `backend = "OFF"`
> > 
> > 
> > how do i do that?
> 
> There's actually an easier way, just type `/flywheel backend off`

What file do I open to do it

**Comment by zEpiixz** [comment]
> 

You just type that ingame in the chat and its done.

**Comment by Brickmaster1** [comment]
Hi I was having the same problem and these solutions kinda fixed it but I feel it should still be addressed as when you turn the backend off this happens.
![2022-06-10_18 13 51](https://user-images.githubusercontent.com/90284936/173157676-5804bf80-4d45-4793-a72e-a57aeef96b69.png)

**Comment by desvandev** [comment]
> Hi I was having the same problem and these solutions kinda fixed it but I feel it should still be addressed as when you turn the backend off this happens.

Didn't notice that, thank you for pointing it out. Anyway, I disabled shaders for now since there are other little stuff that look weird (specially Mahou effects)

**Comment by Asek3** [comment]
Should be fixed on latest Flywheel and Oculus versions. If not, plz tell
